### ISSUE TITLE
DESIGN: Request to be a provider

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1008]
@rlaferla

**Comment by rlaferla** [comment]
<img width="836" alt="image" src="https://user-images.githubusercontent.com/1135694/216159018-d8b8930a-1b43-43da-985a-880bb128fbbd.png">

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/1135694/216159067-0df1c6ab-0eaa-453f-8927-43c3aa3077f3.png">
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/1135694/216159182-9435e700-63a8-40a4-b298-2f7eb10d8b1e.png">

**Mainnet**

- A user who already has a MSA id, selects `request_to_be_a_provider()` extrinsic from the MSA pallet.
- The user enters the `provider_name` and submits the transaction.
- A motion proposal is created for the Council to review and vote on.
- The proposal includes the MSA id of the user who made the request.
- A Council member votes on the proposal (`Aye` or `Nay`)
- When one member votes `Aye`, the motion is approved and the `create_provider()` call is executed with the provided MSA id.
- The user is now a provider.

Development/Test (Rococo)
- A user who already has a MSA id, selects `create_provider()` extrinsic from the MSA pallet.
- The user enters the `provider_name`, the `msa_id` is optional and is ignored.  They sign and submit the transaction.
- The user's account origin is checked to ensure that it is signed.
- The user's account is checked to see if they have a MSA id.  If there is no MSA id, an error is generated and transaction fails.
- The user's MSA is checked to see if they are already a provider.  If they are already a provider, an error is generated and the transaction fails.
- QUESTION: Do we need to check if the provider name is already in use by another provider?
- If all checks pass, the user's MSA is now a provider with the given name.

**Comment by rlaferla** [comment]
QUESTION:  How does a MSA unregister as a provider?

**Comment by rlaferla** [comment]
QUESTION:  How does a MSA change their provider name?

**Comment by rlaferla** [comment]
One consideration is that the user's account may somehow get disassociated from their MSA (perhaps via `retire_msa()`) between motion creation and approval/execution.  We may want to pass their account instead of the MSA id in `create_provider()`

**Comment by rlaferla** [comment]
We are currently considering overloading the `create_provider()` extrinsic to work for both _Mainnet_ (includes the `AccountId`) and for local/_Rococo_ (does not include the `AccountId`.)  Alternatively, we could have a second extrinsic, `create_provider_via_governance()` that has an `AccountId` parameter.

**Comment by rlaferla** [comment]
The `create_provider()` extrinsic needs to be deprecated and unit tests rewritten to use the new provider creation process.

**Comment by p5150j** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blockchain-Team-638f7004a2c37722fe2850e8/issues/LibertyDSNP/frequency/1008?planning-poker) with Zenhub @rlaferla

**Comment by rlaferla** [comment]
Implemented by #321
