### ISSUE TITLE
[Capacity] Allocate a certain amount of block space for capacity transactions

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1016]
needs to be groomed

**Comment by p5150j** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blockchain-Team-638f7004a2c37722fe2850e8/issues/LibertyDSNP/frequency/1016?planning-poker) with Zenhub @enddynayn @johnmela @shannonwells

**Comment by enddynayn** [comment]
@shannonwells nope. This is a ticket for the next phase of Capacity, where we want to allocate a certain amount of block space for Capacity transactions.

**Comment by wilwade** [comment]
Duplicate of #141
