### ISSUE TITLE
[Private Graph] Check schema settings in stateful pallet extrinsic

### ISSUE THREAD

**Issue by aramikm** [LibertyDSNP/frequency#1040]
### Description
To be able to support append only or signature required schema settings we will need to check the action against stored schema in schema settings.

### AC
- Check optional<signature payload> and it the signature matches up for signature required schemas settings on itemized and paginated
- check non append actions against append only schemas of stored in schema settings

**Comment by p5150j** [comment]
Related to #1047

**Comment by saraswatpuneet** [comment]
@aramikm  for this i believe

1. Prevent remove and upsert(mostly update)  actions for AppendOnly is activate AND/OR
2. If SignatureRequired is activated, then all extrinsic must check for signature before adding/upserting 

That is it right?

**Comment by saraswatpuneet** [comment]
Merged
