### ISSUE TITLE
[private graph] More generic child tree utility

### ISSUE THREAD

**Issue by aramikm** [LibertyDSNP/frequency#1042]
### Description
Currently we have a child tree utility that allow us to interact with a child tree but it lacks some generic items such as
- Generic hash function
- Generic Key type

Not having a generic key type forces us to decode all keys to `Vec<u8>` first and then we can decode to the desired key type.

### AC
- Support Generic Reversible hash function
- Support Generic Key Type

### Additional info
for an example of how this can be done we can look at https://github.com/paritytech/substrate/blob/38c3e5ee10be760115a77a115ef0ac6ba381542b/frame/support/src/storage/generator/double_map.rs#L76

**Comment by p5150j** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blockchain-Team-638f7004a2c37722fe2850e8/issues/LibertyDSNP/frequency/1042?planning-poker) with Zenhub @aramikm @JoeCap08055 @saraswatpuneet
