### ISSUE TITLE
Configure additional GitHub environments

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#1091]
Besides posting release assets on the GitHub release page, we also deploy and upload assets  to the following locations:

1. GitHub Pages
2. Docker Hub
3. NPM

A [GitHub environment is already set up for item 1](https://github.com/LibertyDSNP/frequency/settings/environments) (GitHub Pages). It may be useful to set up additional environments for the remaining 2 (Docker Hub and NPM), so the deployment status for all three can be posted and tracked on the main project page here (see image below). Secrets, deployment branches, etc. can also be scope each environment individually to improve security. 

![Screenshot 2023-02-15 at 10 15 09 AM](https://user-images.githubusercontent.com/4452412/219117391-567dc122-c556-4472-8c72-fd50e6567c63.png)

**Comment by wilwade** [comment]
I think that feeling aligns with mine. Ok to not do for now.
