### ISSUE TITLE
Publish release assets in backup locations

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#1092]
We currently publish docker images to DockerHub and npm packages to NPM. If one of those sites are down, access to the artifacts will be restricted. As a backup, consider utilizing [GitHub Packages ](https://github.com/LibertyDSNP/frequency/packages) which support Container and NPM registries. 

![Screenshot 2023-02-15 at 10 35 42 AM](https://user-images.githubusercontent.com/4452412/219121537-d15917e3-a688-48fa-a666-6201bf0e1325.png)

References:
- [Working with the Container registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry)
- [Working with the NPM registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry)

**Comment by wilwade** [comment]
It's fine , but I don't think it is worth it for now. (Side note that GitHub's npm is great for private npm packages)

**Comment by wilwade** [comment]
Archive
