### ISSUE TITLE
Remove old workflows from actions history

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#1097]
The list of workflows under "All Workflows" is getting longer  and longer as it shows every workflow we've ever used in the past, including dupes. There is no way to clean up through GitHub yet, but there are some scripted workarounds maybe worth looking at. See https://github.com/orgs/community/discussions/26256

![Screenshot 2023-02-16 at 8 08 41 AM](https://user-images.githubusercontent.com/4452412/219422647-4dd28b69-cdc5-4d07-b75a-6ea453751e2b.png)

**Comment by wilwade** [comment]
Removed a few of these. (Release only has one now for example)
Archiving for now.

**Comment by wilwade** [comment]
I just did a few by hand. Many had just a few runs from tests
