### ISSUE TITLE
On-chain Schema JSON Validation Prior to Registration

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#111]
As a user, I should NOT be able to register an malformed schema so that all schemas registered on-chain are valid JSON

## Acceptance Criteria
- [x] Schema with invalid JSON should be rejected from being registered
- [x] Schema with valid JSON should be allowed to be registered

## Notes
- [serde](https://serde.rs/) parsing

This replaces https://github.com/LibertyDSNP/mrc/issues/29 for now.

**Comment by mehtaishita** [comment]
Reopening issue for Serde-json-core PR.
