### ISSUE TITLE
Missing type: "module" specifier in @frequency/api-augment JS package

### ISSUE THREAD

**Issue by jacogr** [LibertyDSNP/frequency#1116]
The `package.json` uses an export map with `"default": "./esm/index.js"` however the default package type is set to commonjs by Node. It would be great if you could add the missing package specifier as `"type": "module"`

Either here

https://github.com/LibertyDSNP/frequency/blob/6a0875de5f79cbf26997d2d5ff41ed925950ec5c/js/api-augment/package.json#L14

Or here 

https://github.com/LibertyDSNP/frequency/blob/6a0875de5f79cbf26997d2d5ff41ed925950ec5c/js/api-augment/scripts/package.js#L26

**Comment by wilwade** [comment]
Fix PR: https://github.com/polkadot-js/apps/pull/9322

**Comment by jacogr** [comment]
It seems to work for the apps UI (where I first noticed the issue), however the setup is maybe not 100% correct.

https://github.com/LibertyDSNP/frequency/blob/fe9b1cd26d13ba4a2ff828855ec39e8d0954fed6/js/api-augment/scripts/package.cjs#L26-L32

So by default Node with use `type: "commonjs"` when not specified. The `default` key would then refer to that package type and here it is setup to point to the esm version. I believe it does work, after the changes, on cjs environments since `require` is explicitly specified. 

However we do double up between `default` & `import` now. Fully correct (with no duplication) would be -

1. Keep cjs, remove `require`, adjust `default` (for the package type) to point to cjs.

```json
"exports": {
  ".": {
    "types": "./index.d.ts",
    "import": "./esm/index.js",
    "default": "./cjs/index.js"
  }
```

2. Or... swap to esm, remove `import` (`default` points to the package-specified type) -

```json
"type": "module",
"exports": {
  ".": {
    "types": "./index.d.ts",
    "require": "./cjs/index.js",
    "default": "./esm/index.js"
  }
```

However, the as-is key duplication seems to work, so going to close it since it does solve my specific usage issues.

**Comment by wilwade** [comment]
It pulls in the `type: module` from the base package.json, so I guess it doesn't need the default and the import, but this is still an evolving js standard. Let's keep an eye out if this causes trouble, but I think it might be better to have both until more things support the exports field.
