### ISSUE TITLE
Verification Options for Substrate

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1119]
Security is hard to get right in blockchains. It's even harder to make sure that code is correct while still actively developing the product: code changes are frequent, requirements are changing, and the codebase is growing.

Explore options for verifying blockchain code, specifically for the Substrate blockchain framework to try to verify the code of the Interlay blockchain.

The tool should be integrated into the Rust toolchain (no DSLs)

Please see:
https://harz.dev/blog/rust-verification/

Timebox:
2 days.

**Comment by rlaferla** [comment]
https://www.youtube.com/watch?v=vMGilPbIotw

**Comment by rlaferla** [comment]
I tried using **Mirai** and found no project issues, just issues with the dependencies.  However, I am skeptical of the results and filed an issue with the Mirai project for confirmation.  https://github.com/facebookexperimental/MIRAI/issues/1206

**Comment by rlaferla** [comment]
I also tried using the _Prusti_ extension for _VSCode_ but was not able to because it was expecting the `x86_64` version of OpenJDK but my system is an Apple Silicon m2 (`arm64`).  I filed an issue with the _Prusti_ project.  https://github.com/viperproject/prusti-dev/issues/1399. I will try the CLI version now.

**Comment by rlaferla** [comment]
The **Prusti** cli generated only errors of type:  `[Prusti internal error]` and `[Prusti: unsupported feature]`

**Comment by rlaferla** [comment]
**Prusti** https://github.com/viperproject/prusti-dev
**Kani** https://github.com/model-checking/kani
**Mirai** https://github.com/facebookexperimental/MIRAI

**Comment by rlaferla** [comment]
A new one that I found and will try:

**Miri** https://github.com/rust-lang/miri

**Comment by rlaferla** [comment]
For Kani, I ran into the same issue as the blog article author:
<img width="691" alt="image" src="https://user-images.githubusercontent.com/1135694/233672631-a133f20f-aa62-497a-bf81-7a979bdc5289.png">
