### ISSUE TITLE
[Chore] Organize Frequency pallet unit test duplicate code into a common module

### ISSUE THREAD

**Issue by johnmela** [LibertyDSNP/frequency#1127]
- Create a folder: `common/tests`
- Place common functions, macros, and constants related to all unit tests in `common/tests/src/lib.rs`. Examples of common code structures include (but are not limited to):
  - Setting up externalities for storage
  - Testing a signed origin
- Code related to mocking a specific pallet may be placed in `common/tests/src/<pallet_name>.rs`. 

Suggestion: Might be best if this is several small PRs to make it easy to review.

**Comment by JoeCap08055** [comment]
Would also be great to organize the tests themselves into "unit" (utilized mocking for any inter-pallet calls) and "integration" (make actual inter-pallet calls). (We do currently have both kinds of tests).

☝🏻 probably a separate issue, though

**Comment by rlaferla** [comment]
Breaking this into separate smaller issues:

#1209 #1210 #1211
