### ISSUE TITLE
Implement Docker Hub Vulnerability Scanning

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#1137]
Starting February 24, 2023, Docker will begin rolling out changes to the technology that supports the Docker Hub Vulnerability Scanning feature. It gives us ability to receive a vulnerability scanning feature native to Docker, with tighter integration into developer workflows, and additional functionality like dependency scanning.

Docker Hub Vulnerability Scanning is available for users subscribed to Docker Pro, Team, or a Business subscription. 

**References:**

- [Hub Vulnerability Scanning](https://docs.docker.com/docker-hub/vulnerability-scanning/)

**Comment by wilwade** [comment]
Archiving for now.
