### ISSUE TITLE
[GraphSDK] Design doc 

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1146]
We would like to get a design doc started for the larger scope of GraphSDK.

Example/boilerplate:
https://github.com/Liberty30/graph-sdk

Spike needs:
- design doc artifact / UML 
- mono repo approach 

Open questions:
- what other sdks would we need?
- relationship with wallet?

**Comment by aramikm** [comment]
uploading to share in design doc
![graph-sdk drawio](https://user-images.githubusercontent.com/9152501/222261121-185d4d9d-1ecb-4ffa-8fe0-8612e58d7b27.png)
