### ISSUE TITLE
[GraphSDK] Aggressive paginating algo 

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1148]
Blocked by #7
Implement defined Algorithm to calculate and compute the results of changes for graphs.

## Additional data
Located at https://github.com/LibertyDSNP/frequency/blob/main/designdocs/graph_sdk.md

**Comment by aramikm** [comment]
This is partially implemented for non aggressive mode but we would need the page size calculations and aggressive mode to be able to close it.

**Comment by JoeCap08055** [comment]
Wrong repository
