### ISSUE TITLE
Optimization: Hashset for delegation mutation

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#1155]
In #1131 we use a slower contains solution for delegation mutation to find the difference between the sets. Replacing it with a hashset is likely be worth the cost of creation of the set.

Function: `upsert_schema_permissions`

```
Self::ensure_all_schema_ids_are_valid(&schema_ids)?;

// Create revoke and insert lists
let mut revoke_ids: Vec<SchemaId> = Vec::new();
let mut insert_ids: Vec<SchemaId> = Vec::new();

let existing_keys= delegation.schema_permissions.keys().into_iter();

for existing_schema_id in existing_keys {
  if !schema_ids.contains(&existing_schema_id) {
    match delegation.schema_permissions.get(&existing_schema_id) {
      Some(block) =>
	  if *block == T::BlockNumber::zero() {
            revoke_ids.push(*existing_schema_id);
	  },
      None => {},
    }
  }
}
```

Suggestion:

- Generate a set for schema_ids
- Replace `schema_ids.contains` with `schema_ids_set.has` (or the correct set function)
- `O(n * existing_key_count)` -> `O(n + existing_key_count)`

Something like tinyset: https://crates.io/crates/tinyset could work with default features disabled.
hashbrown is already used in substrate, but not in a no_std env as far as I can tell, but might work: https://github.com/rust-lang/hashbrown#features

_Originally posted by @wilwade in https://github.com/LibertyDSNP/frequency/pull/1131#discussion_r1120322082_

**Comment by allanperlee** [comment]
@aramikm Can I take this challenge too?

**Comment by aramikm** [comment]
@allanperlee  Sounds good. I'll assign it to me so nobody else takes it.

**Comment by aramikm** [comment]
I tried **tinyset** and it didn't work, even though it has **default-features = false**  still it doesn't work in in **no_std**.

**Comment by aramikm** [comment]
I did some benchmarking comparing current implementation with BTreeSet for 10, 100, 1000 items inside both schema_ids and existing_keys. Here's what I found

```
test tests::current_10   ... bench:          81 ns/iter (+/- 3)
test tests::current_100  ... bench:       3,671 ns/iter (+/- 48)
test tests::current_1000 ... bench:     320,893 ns/iter (+/- 5,360)
test tests::tree_10        ... bench:          79 ns/iter (+/- 1)
test tests::tree_100       ... bench:         286 ns/iter (+/- 11)
test tests::tree_1000      ... bench:       2,102 ns/iter (+/- 31)
```


if the schema_ids and existing keys arer in the order of tens it does not make sense to change it but if in order of hundreds or more then it will be helpful
