### ISSUE TITLE
[User handles] set current MSA ID max to 2^32 

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1171]
As a user I should not be required to have a handle to create a MSA.

Acceptance Criteria:
- can create an MSA without a handle 
- `msa::create` still works 
- `createSponsoredAccountWithDelegation` should still work 

Constraints:
- we make the assumption the handle system is contained to the 32 bit space 

Current storage configuration:

```
/// Message Source Id or msaId is the unique identifier for Message Source Accounts
pub type MessageSourceId = u64;
```

**Comment by rlaferla** [comment]
The current MSA id (MessageSourceId) is a unsigned 64 bit value (u64). In this new scheme, users without handles will have MSA ids from 0 to (2^32) - 1.  Users with handles will have MSA ids in from (2^32) to (2^64) -1.

**Comment by rlaferla** [comment]
We need to review the Frequency code base to ensure that there are no assumptions that a MSA id is an incremental sequence.
