### ISSUE TITLE
[User handles] msa retire set key count to 0

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1175]
As a , user I do not want my msa to be used after I retire it. 

Acceptance Criteria:
- After a MSA has been retired I should not be able to make a new MSA id with the same id. 

Dependencies:
#1173 && #1174

Ethical Considerations:
-  retired should not be able to be recovered 
- we want to make sure the msa doesn't retain key info

**Comment by rlaferla** [comment]
This is already implemented so this is really about writing integration/unit tests to make sure that these criteria are met.
