### ISSUE TITLE
RPC to get Messages from IPFS Payload Locations

### ISSUE THREAD

**Issue by saraswatpuneet** [LibertyDSNP/frequency#119]
Given that a schema can be created with Payload Location IPFS (#190)

I want to receive in the `get_messages_by_schema` RPC to get back the cid that I used when I called `add_ipfs_message`

# Acceptance Criteria
- [x] I can call an RPC to retrieve previously added IPFS messages with a `cid` field that is the IPFS cid
- [x] When I call an RPC to to retrieve previously added IPFS messages, I should *not* receive the `msa_id` field

## Remember
- [ ] Update api-augment interface

# Examples
- IPFS, Parquet: `{ index, block_number, provider_msa_id, payload_length, cid }` 
- Avro, OnChain: `{index, block_number, provider_msa_id, payload_length, msa_id,  payload: <bytes> }`
- `MessageResponse`
  - Required
    - index
    - block_number
    - provider_msa_id
  - IPFS Only
    - cid
    - payload_length
  - On-chain only
    - msa_id
    - payload

# Notes
- Use `#[cfg_attr(feature = "std", serde(skip_serializing_if = "Option::is_none"))]` on top of optionals

### Arch Notes/Questions
- Do we need to make `MessageResponse` dependent on `Schema`? At least such that the data is dependent on the Payload Location and Model Type? **Yes**
- Do we want to have consistent data in `MessageResponse` even if the payload is a CID instead of the payload? Or should it be custom to that Schema? **Custom to schema**
- Discussion Notes
  - eg Custom
      - IPFS, Parquet: `{ index, block_number, provider_msa_id, payload_length, cid }` 
      - Avro, OnChain: `{index, block_number, msa_id, provider_msa_id, payload: <object from bytes> }`
   - Standard: **_Not using this_**
      - IPFS, Parquet: `{ index, block_number, provider_msa_id, msa_id: <Optional> payload_length, payload: <cid> }` 
      - Avro, OnChain: `{index, block_number, provider_msa_id, msa_id, payload_length: <null | payload bytes length>, payload: <bytes or object> }`
- Should payload be decoded (different story) for Avro? 
  - **No**. We want library developers to be able to encode and decode using bidirectional tools

### Implementation Sub Tasks
- [x] Message Response with the proper optional fields
- [x] Build message response using custom data fields
- [x] Update message response in API across all tests
- [x] Update message response in API possibly across other pallets
- [x] Write unit test: get_messages_by_schema_returns_ipfs_cid_required_fields
- [x] Write more unit test ....(more to come)

**Comment by aramikm** [comment]
>  I should receive the payload length data so I can validate the file I receive from IPFS

currently it seems like we are not storing `payload_length` or the `ipfs file location` in messages.


we have generic rpc to get messages with schema id, I'm not sure what we are trying to achieve here?

**Comment by saraswatpuneet** [comment]
@aramikm question ipfs file location? 
I think we just have to know the cid and any gateway gives file back right?

We can store the payload_length that way the get from IPFS gateway content length can be matched with stored payload_length 

So as long as we are storing the cid and length we are good unless we run own IPFS gateway then we can specify a location per se

**Comment by wilwade** [comment]
@aramikm / @saraswatpuneet The PR #247  was merged. So `add_ipfs_message` is the extrinsic for adding an IPFS message.

**Comment by aramikm** [comment]
@saraswatpuneet yes by location I meant `cid`

@wilwade There is an extrinsic but it's not storing any of mentioned data
