### ISSUE TITLE
[Batched Messages] Spike: Define Schema for Batched Messages

### ISSUE THREAD

**Issue by saraswatpuneet** [LibertyDSNP/frequency#120]
# Things to Figure Out

As a user, I want to publish a batch of messages, so that others can read those messages.

## Acceptance Criteria
- [ ] How do others know how to read the data I share?
    - Schemas
    - Data format
    - How do two independent actors go from MRC Schema with no messages each arrive at the same Parquet file given the same messages?
- [ ] How do others know the data I shared is from me or a delegate?
    - Validation
    - Delegation (MRC Batches don't support delegation, that is up the protocol to define aka the DSNP Id)
- [ ] How I let other people know that I created a batch file and how they can get and read it?
    - Who: Announcer MSA Id
    - Where: IFPS URI
    - What: Schema Id
    - How: File Format
- [ ] As a user who wants to read messages, I want to be able to call an rpc to get a paginated list of batch file metadata (aka ipfs uris) for a particular data structure (aka a given Schema Id)
- [ ] (Not this story) As the network, we want to limit spam even if that spam is off-chain. To that end we want to charge capacity for off-chain messages
    - Current Solution: Make announcers provide the file size along with the other metadata for the batch. Charge extra capacity based on this file size. Consumers of that batch file are only expected to download the file size number of bytes and anything more than that should be disregard such that lying about file size is useless as others will merely receive bad files.

### Properties of Batches

We think this all leads to Parquet files (with compression and bloom filters)

- Low bandwidth
- Small storage
- Easy to parse
- Searchable/filterable on header data download
- Scalable to large number of entries

# OLD

Consumer of network should be provided the schema defining a batch announcement

# Acceptance Criteria
- [ ] Document and present options for handling batch reference posted to the chain

# Description
See [BatchAnnouncementParams](https://github.com/LibertyDSNP/mrc/blob/main/designdocs/batched_messages.md#types)
For more details on a batch announcement schema types

Things to consider/Need Details:
- How do we structure the data for the batch reference posted to the chain?
  - e.g. Should batch announcement type schema be registered with schema pallet and if so define the schema type as well as publish schema_id
  - Should the structure be completely fixed
  - How does this schema get registered, if it's stored in Schema storage in the schema pallet -- Genesis config?

Remember: Schemas have an choice at creation:
1. The avro data for each message is stored on-chain
2. The data for each message is in a batch

**Comment by wilwade** [comment]
Ref: #166
