### ISSUE TITLE
Unit Test Reorganization: Apply builder pattern to unit tests

### ISSUE THREAD

**Issue by rlaferla** [LibertyDSNP/frequency#1210]
As a developer, I want organized unit tests so that developing, managing, running tests are easier and clearer.

**Acceptance Criteria:**

Mocks will provide a default test builder implementation with various utility functions.
Tests will use the new builder pattern but won't be rewritten/deconstructed.

**Comment by rlaferla** [comment]
https://jmmv.dev/2020/12/builder-pattern-for-tests.html

**Comment by rlaferla** [comment]
https://github.com/paritytech/substrate/blob/master/frame/balances/src/tests_local.rs

**Comment by wilwade** [comment]
Closing for now. The patterns are changing for Substrate as well.
