### ISSUE TITLE
Polkadot UI: Ensure capacity tx can be called with empty token balance

### ISSUE THREAD

**Issue by enddynayn** [LibertyDSNP/frequency#1214]
**Description**
Users who have Capacity should not be required to hold any token balance.

**Acceptance Criteria**
- As a provider who has Capacity, I should be able to submit transactions and pay with capacity without holding any tokens.
- As a provider with Capacity, I should be able to submit a transaction and pay with capacity using Polkadot UI without holding any tokens.

**Comment by mattheworris** [comment]
@enddynayn The Polkadot UI requires a 0.0100 existential deposit. I could not get the funds to go below that using the Polkadot UI. I completed a capacity transaction that cost more than the available token balance. What is the best way to document this result? Screen recording or detailed instructions to reproduce?

**Comment by enddynayn** [comment]
@wilwade I think I left the comment in the wrong ticket.

**Comment by mattheworris** [comment]
This screen recording demonstrates how to set up and execute a payWithCapacity transaction with an account with no tokens.
https://www.loom.com/share/bc7dd0c08f0e4983b36fb643c4355a94
