### ISSUE TITLE
warning: public documentation for `add_schema` links to private item

### ISSUE THREAD

**Issue by rlaferla** [LibertyDSNP/frequency#1221]
warning: `pallet-schemas-runtime-api` (lib doc) generated 1 warning
warning: public documentation for `add_schema` links to private item `CurrentSchemaIdentifierMaximum`
   --> pallets/schemas/src/lib.rs:332:3
    |
332 | /         /// Build the [`Schema`] and insert it into storage
333 | |         /// Updates the [`CurrentSchemaIdentifierMaximum`] storage
    | |__________________________________________________________________^
    |
    = note: the link appears in this line:
            
            Updates the [`CurrentSchemaIdentifierMaximum`] storage
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: this link will resolve properly if you pass `--document-private-items`
    = note: `#[warn(rustdoc::private_intra_doc_links)]` on by default

**Comment by aramikm** [comment]
I think we have a couple of other warnings like this. Just wanted to make sure if we are addressing one we are addressing them all at the same time.
