### ISSUE TITLE
[Capacity] end to end video demo of Capacity for internal use

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1222]
As an unfinished team member that isnt on the blockchain team I would like an exhaustive recoded demo video of what has been built and how to use it.

**Comment by mattheworris** [comment]
Here is a link to the Demo Day for Capacity. Enddy gives a great overview of how capacity works.
https://drive.google.com/drive/folders/1thMDNxYCIhCqwHW2IfJZ-1kwXimHa0Ae
