### ISSUE TITLE
Testing "types" should not need a runtime execution environment

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/frequency#1227]
We have a lot of tests of structs in `types.rs` files with implementation of traits which are run under `new_test_ext().execute_with()` which shouldn't need this, and it keeps them from being proper unit tests but also slows down execution.  Just removing this runtime execution may not be enough. For example, if there is an `assert_noop` it will tell you that you need a runtime environment. Try `assert_err` first.

Note: there are types in common/primitives that implement some traits inside a pallet, and are tested in the pallet. Does this actually make sense? Either way, let's still try to pull their testing out of a runtime execution.

AC:
Testing implementation of traits by types does not rely on constructing a runtime:
  - [ ] MSA pallet
  - [ ] Schemas pallet
  - [ ] Messages palllet
  - [ ] Capacity pallet (in a development branch)
  - [ ] Common primitives?  may want to put this in another ticket

**Comment by p5150j** [comment]
@shannonwells is this still relevant? can we nuke this?

**Comment by wilwade** [comment]
These are all fixed now.
