### ISSUE TITLE
Improve benchmark script

### ISSUE THREAD

**Issue by aramikm** [LibertyDSNP/frequency#1231]
1. Rename `run_all_benchmarks.sh` -> `run_benchmarks.sh` as "all" in the name implies that this script runs benchmarks for all pallets and doesn't have selective pallet support. Maybe misleading to some developers. Perhaps the old `run_benchmarks.sh` can be removed or deprecated as this new script seems to do its job already.

1. Instead of creating a new make target for each pallet (just think of 1000s pallets), we can create one universal target that passes pallet name as an argument. Something like this:
   ```make
   .PHONY: benchmarks
   benchmarks:
     ./scripts/run_benchmark.sh -p $(pallet)
   ```
   Then call it with:
   
   `$ make benchmarks pallet="<pallet_name>"`

**Comment by JoeCap08055** [comment]
A few comments:

1. `make` doesn't work that way; you can't pass parameters to targets like a standard command-line. You _could_, perhaps, do this:
```
PALLETS=<pallet_name[,pallet_name]> make benchmarks
```
and change the target command to be:
```
.PHONY: benchmarks
benchmarks:
   ./scripts/run_benchmark.sh $(PALLETS)
```

You could also write a rule like:
```
benchmarks-%:
   ./scripts/run_benchmark.sh $*
```

However, we should consider that doing so would mean auto-complete for shells would not list the available benchmark targets in this case. If we want to preserve auto-complete for command shells, we could do something like this:
```
BENCH_TARGETS=benchmarks-messages benchmarks-msa benchmarks-schemas. benchmarks-stateful-storage benchmarks-overhead

$(BENCH_TARGETS):
   ./scripts/run_benchmark.sh ${@:benchmarks-%=%)
```

**Comment by JoeCap08055** [comment]
> @JoeCap08055 Hm... 🤷🏻 It works for me in the linked PR: #1241:
> 
> ```shell
> # Run benchmarks for msa pallet
> $ make benchmarks pallet="msa"
> ./scripts/run_benchmark.sh -p msa
>     Updating git repository `https://github.com/paritytech/substrate`
>     Updating git repository `https://github.com/paritytech/cumulus`
>     ...
> ```
> 
> ```shell
> # Run benchmarks for schemas pallet
> $ make benchmarks pallet="schemas"
> ./scripts/run_benchmark.sh -p schemas
>     Updating crates.io index
>     ...
> ```
> 
> Unless I am missing something here.

What I mean by "preserving CLI auto-complete" is that the way you have it now, if the user types `make bench<TAB>` in a properly configured shell, they'll see:
```
benchmarks
```
as this is the only configured target. There is no assistance provided to the user to indicated valid pallet names to add to the command. But if we create individual targets as I've listed above, typing `make bench<TAB>` yields:
```
benchmarks-messages benchmarks-msa benchmarks-overhead benchmarks-schemas benchmarks-stateful-storage
```

**Comment by JoeCap08055** [comment]
Yes, please close.
