### ISSUE TITLE
[Bug] validate_cid can cause a panic

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#1233]
> Unsafe unwrap() in rust-multihash dependency

The extrinsic add_ipfs_message in [pallets/messages/src/lib.rs](https://github.com/LibertyDSNP/frequency/blob/c6c53f3d8b246da402a8bc97f51b2d98d8341398/pallets/messages/src/lib.rs#L222) invokes `validate_cid()` function in which a call to `Cid::read_bytes()` is also made. This function uses the [rust-multihash](https://github.com/multiformats/rust-multihash) dependency where the function [read_u64](https://github.com/multiformats/rust-multihash/blob/master/src/multihash.rs#LL360C14-L360C24) contains [Ok(decode::u64(&b[..=i]).unwrap()](https://github.com/multiformats/rust-multihash/blob/master/src/multihash.rs#L368). If the unwrap() fails, this could potentially cause nodes to panic. Thus, it could provide attackers a low cost opportunity to perform a DoS attack against the whole parachain.
Issue

The below code invokes Cid::read_bytes where, if cid_b is not in a correct format, a panic could happen.
```
pub fn validate_cid(in_cid: &Vec<u8>) -> Result<Vec<u8>, DispatchError> {
		...
		ensure!(Cid::read_bytes(&cid_b[..]).is_ok(), Error::<T>::InvalidCid);
		...
}
```

The below call can be used to reproduce the unwrap() issue and cause a crash:

`RuntimeCall::Messages(Call::add_ipfs_message { schema_id: 0, cid: [0, 1, 0, 1, 203, 155, 0, 0, 0, 5, 67], payload_length: 407371785 })`

## Risk

Since this can be triggered by a call to an extrinsic an attacker could cause a validator node to crash by submitting a specific crafted extrinsic and cause them missing their block authoring slot. This could lead to a denial-of-service of the whole chain with only very low cost requirements for the attacker.

## Mitigation

There are multiple possibilities to mitigate the issue. The first one is forking the dependency, removing the unwrap() and matching the Error from there. A second possible fix would be to check for the read bytes to be formatted correctly (with a correct length for example) so the unwrap issue could never be triggered.

**Comment by rlaferla** [comment]
We need to add a unit test for this as well.

**Comment by mattheworris** [comment]
The following issue has been created to address the panic in the multihash repo:
https://github.com/multiformats/rust-multihash/issues/282
And the pull request:
https://github.com/multiformats/rust-multihash/pull/283

**Comment by mattheworris** [comment]
Updated Pull Request:
https://github.com/multiformats/rust-multihash/pull/293
