### ISSUE TITLE
[Handles] Create user handle with suffix

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1234]
As a network, _Frequency_ should allow users to choose their own handle. This extrinsic will allow users to create a handle with a numeric suffix generated.

### Acceptance criteria 

- Create an extrinsic `claim_handle()` that takes a display handle (UTF-8) and creates a unique handle for a MSA id.
- The extrinsic should take and verify the signed payload (display handle and MSA id)
~~- The stored handle must contain a retirement block number where 0 is active (not retired.)~~
- Create a canonical handle generator that takes a display handle (UTF-8) and returns a canonical base handle stripped of whitespace, homoglyphs and diacriticals.
- Create a suffix generator that returns a pseudo random suffix for a given base handle.
- Check for race conditions when multiple users attempt to claim the same handle

### Ref docs
Please see design doc (will add [once merged](https://github.com/LibertyDSNP/frequency/pull/1225))

### Subtasks:
- [x] #1254
- [x] #1255

**Comment by p5150j** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blockchain-Team-638f7004a2c37722fe2850e8/issues/LibertyDSNP/frequency/1234?planning-poker) with Zenhub @saraswatpuneet @rlaferla @johnmela

**Comment by saraswatpuneet** [comment]
@rlaferla  @johnmela  not sure if we want to even add the optional suffix in payload and in v1 this extrinsic can just accept handle name part and suffix we assign for everyone

Something I am questioning

**Comment by rlaferla** [comment]
No need for the suffix.

**Comment by enddynayn** [comment]
> Create a suffix generator that returns a pseudo random suffix for a given base handle
Why do we do this?
