### ISSUE TITLE
Bug fix: Integration Tests: missing await and run_integration_tests.sh script error

### ISSUE THREAD

**Issue by mattheworris** [LibertyDSNP/frequency#1242]
# Script Fix
./scripts/run_integration_tests.sh: line 11: ./scripts/scripts/kill_freq.sh: No such file or directory

In the case when executing `make integration-test` and there is no local node running already:
When the script exits, bash sends the EXIT signal. `trap` then runs `cleanup` which tries to run the `kill_freq.sh` but it is not in the correct directory.
- Fix: Change `trap` not to run on EXIT, as it is redundant.

# Integration Test Fix
  1) Capacity Transaction Tests
       pay_with_capacity testing
         should pay for a transaction with available capacity:
     RpcError: 1014: Priority is too low: (3009 vs 3009): The transaction has too low priority to replace another transaction already in the pool.

This error occurs because the previous transaction was missing `await`
- Fix: Add the missing `await`

**Comment by JoeCap08055** [comment]
`trap` needs to run on EXIT; otherwise if you Ctrl-C out of the script it won't kill the node. Better fix is to fix the command called by the trap so it performs correctly.

**Comment by mattheworris** [comment]
> 

In experimentation, I found that Ctrl-C would always run the `cleanup()` function when pressed, however, it's not always in the correct directory to run the `kill_freq.sh` script. `EXIT` happens after the last `if` clause and was redundant. 
Agreed, that fixing `cleanup` is also needed.
