### ISSUE TITLE
Scale Schema Creation Cost on Retention Period

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#125]
As the network, I want users who create schemas with long retention periods to be charged more for such retention so that users creating schemas try to minimize their retention periods.

Open Questions:
- What is the cost multiplier?
- Tokens or Capacity? A: Tokens

**Acceptance Criteria**
- [ ] Add a weight adjustment based on the length of the retention period
- [ ] Update weights and benchmarks
- [ ] Update documentation

**Comment by saraswatpuneet** [comment]
Are these token fee or capacity we are talking about that user will pay

**Comment by wilwade** [comment]
Tokens. Schema registration is all token based. Updated issue.

**Comment by wilwade** [comment]
Archive
