### ISSUE TITLE
[Handles] Spike: Homoglyphs handling and name processing 

### ISSUE THREAD

**Issue by saraswatpuneet** [LibertyDSNP/frequency#1252]
Goals

- [ ] Any standard, well vetted crates for homoglyphs or custom code using unicode normalization 
- [ ] Steps for name washing and cleaning (potentially some pseudo code)
- [ ] Blocklisting and cannot contain the following substrings: @, #, :, ., ``` and we will expands this is v2
- [ ] Make sure each options provided are url safe 
- [ ] ? define and explore unknowns (as the spike unfolds)

Output of the spike:

- document options compare and contrast vetted crates

Time box:
2 days

**Comment by rlaferla** [comment]
We can use Unicode normalization (NKFD) (preferred) or Punycode.

**Comment by rlaferla** [comment]
https://unicode.org/faq/normalization.html

**Comment by rlaferla** [comment]
We need clarity around what we are trying to prevent AND how we will prevent it.  

Let's say we have two user handles that are different except they are homoglyphs:

𝕊𝔸𝕄𝕄𝕐
SΑΜΜΥ

After the suffix is generated, if the suffix is the same, they remain homoglyphs.

𝕊𝔸𝕄𝕄𝕐-1234
SΑΜΜΥ-1234

However, if the suffix is different, you can distinguish one from the other so they are not strictly homoglyphs:

𝕊𝔸𝕄𝕄𝕐-1754
SΑΜΜΥ-5236

1.  Are we trying to ensure that the handle is unique for the **base+suffix** or just the **base**?
2. How do we determine that a handle "looks like" another handle?  This is similar to comparing strings using a case-insensitive comparison algorithm or rather doing a query that is case-insensitive.  This may be difficult to accomplish in a blockchain.

**Comment by saraswatpuneet** [comment]
1. For sure both 
2. There where the question comes if a homoglyph detector can take the 𝕊𝔸𝕄𝕄𝕐-1234 and spit out SΑΜΜΥ-1234 

But looking at two, I wonder we only case about homoglyph in ascii context ? When language is involved?

**Comment by rlaferla** [comment]
This is a problem because we would have to store a case/glyph-insensitive string (that we search against when determining availability/uniqueness) as well as the actual string (for display in the UI) which will take up more storage.  We may have to allow homoglyphs.

**Comment by johnmela** [comment]
I think we would have to use two storages like @rlaferla outlined in order to be able to search for availability against a homoglyph cleaned string and still be able to display foreign language characters stored in original formatting.

We would probably want to prevent
John.1234
john.1234

From being two separate usernames as well

**Comment by rlaferla** [comment]
One possible solution:  We store the "normalized" string ASSUMING there is a way to convert back to the presentation string.

**Comment by rlaferla** [comment]
We convert the user's requested handle to NKFD and check it's availability.  If it's available, we store the NKFD form.  We just need to explain how to convert NKFD back to the original form for display/presentation.

From the Unicode spec:

_Unicode NKFD is a normalization form that erases both canonical and compatibility differences, and produces a decomposed result: for example, the single ǆ character is converted to d + z + caron in this form._

**Comment by johnmela** [comment]
We will move forward with a solution that takes a list of known confusable unicode characters that are converted into a BTreeMap constructor in Rust. 

The BTreeMap will map each homoglyphic character (key) to its corresponding canonical form (value).

A function must then be written that takes in a string and replaces each homoglyphic characters(key) with its normalized counterpart (value) and returns a new string.

Then, we can determine if we should increase the size of the b tree to include handling diacriticals AND converting to lowercase from within the map OR if we should do some kind of post processing to handle lower case and diacriticals in a different way

**Comment by johnmela** [comment]
```
use unicode_normalization::UnicodeNormalization;
fn strip_diacriticals(input: &str) -> String {
    input.nfd()
         .filter(|c| !c.is_mark())
         .collect()
}
fn main() {
    let input = "rësumé";
    let stripped = strip_diacriticals(input);
    println!("{}", stripped); // prints "resume"
}
```
from Robert ^

We should test removing diacryticals with the above snippet
