### ISSUE TITLE
Design Doc for Registering Providers

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#129]
We want to limit which MSAs can do certain things and require additional information so that we can provide better safety and guarantees to users.

`Provider`: An MSA that is registered for being able to be delegated to and being the target of capacity rewards when a person stakes to the network for token rewards.

## Things to Include
- How to identify a provider (msa registration, separate?)
- Getting a list of providers
- How to discontinue being a provider
- Governance approval is NOT required
- What happens if the provider MSA id is removed?
- How can I become a provider?
  - Expected to be a token transaction
- Who can become a provider?
  - Anyone who pays the token transaction
- Run Discussion around gatekeeping and making sure that providers are possible for all (community run providers etc...)

## Limits
- Delegating. Users cannot just delegate to anyone and is limited to just providers
- Callback safety. Wallets or other applications interacting with a registered provider should use the chain published domain for callbacks
  - @shannonwells has some flows around callbacks that might be helpful

## Additional Information
- MSA Id attaches to this information
- Callback (domain)
  - prove ownership of domain?
    - Registrar pallet perhaps?
- Name (What if this is close to another? Should these be unique? utf-8 or ascii?)
- Logo URL? (optional? or forced to be on the domain?)
- Description? (optional?)
- Other?

## Notes
- Interactions are token transactions
- Future need: Capacity rewards when network staking (#40)

**Comment by mehtaishita** [comment]
To continue off of Enddy's comment about allowing delegation to a 'good friend' who isn't registered as a provider: 

What if a user can ask to delegate to another non-provider msa id, and in that workflow also allow the user to register as a temporary provider? Effectively, allowing various stages of being a provider such as 'Samaritan', 'professional' etc?
