### ISSUE TITLE
[Tech debt] add Frequency to nova-wallet/metadata-portal

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1295]
As Frequency we would like to be added to:
 
https://github.com/nova-wallet/metadata-portal

The live version of the Nova Wallet portal is here:
https://metadata.novasama.io/#/polkadot

**Comment by rlaferla** [comment]
https://github.com/nova-wallet/nova-utils/issues/1658

**Comment by rlaferla** [comment]
https://github.com/nova-wallet/nova-utils/pull/1660

**Comment by rlaferla** [comment]
Updated icon to white to meet Nova's common application guidelines

**Comment by rlaferla** [comment]
![image](https://github.com/LibertyDSNP/frequency/assets/1135694/a3c606fa-755d-4c92-a086-6bf27bb36e1a)
