### ISSUE TITLE
[Handles] project demo video 

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1306]
As an unfinished team member that isnt on the blockchain team I would like an exhaustive recoded demo video of what has been built and how to use it.

**Comment by rlaferla** [comment]
This was completed and added to the PR last week but due to a change to the retire_handle() extrinsic, I need to re-record it.

**Comment by rlaferla** [comment]
I recorded a new one this morning for the Readout meeting.

https://www.loom.com/share/50c706523ccb47159b8a7986d9d07997
