### ISSUE TITLE
[chore] rename integration-tests directory to e2e-tests

### ISSUE THREAD

**Issue by JoeCap08055** [LibertyDSNP/frequency#1315]
## Description
Since the tests in the current `integration-tests` directory are actually full system API tests against a running Frequency instance, they're really more appropriately named as "end-to-end" or "e2e" tests. Change the directory name to reflect that.

## Acceptance Criteria
- [ ] Directory renamed as `e2e-tests`
- [ ] Scripts renamed accordingly (`scripts/run_integration_tests.sh`)
- [ ] Makefile targets renamed `integration -> e2e`
- [ ] Makefile rules updated to reflect new target, directory and script names
- [ ] CI tasks updated accordingly

**Comment by enddynayn** [comment]
In the spirit of renaming. Can we also consider renaming scaffolding to config? Additionally, we also have extrinsicHelpers and helpers, which we can consider combining into one and pulling out of scaffolding.

**Comment by JoeCap08055** [comment]
> In the spirit of renaming. Can we also consider renaming scaffolding to config? We also have extrinsicHelpers and helpers, which we can consider combining into one and pulling out of scaffolding into its own helpers directory. We have a directory called scenarios which I think we are supposed to put all tests. However, it seems that we have fallen out of sync. Not sure if that should move that too.

I think maybe that's a subject for a separate issue, more of a refactoring than a simple renaming.
