### ISSUE TITLE
[Handles] investigating the unicode diacritical

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1334]
@johnmela will you explain what you found with the unicode diacritical issue below?

**Comment by johnmela** [comment]
The issue appears to be that UTF8 characters with diacritical marks can be either:
1. composed of two characters: a base character and a combining mark
2. a single character that contains both the base and the mark

For example:
The name `Álvaro` has an acute accent over the leading `A`. The `Á` can be encoded as codepoint `0x00C1`, a combined character that lives in the [Latin-1 Supplement](https://www.unicode.org/charts/PDF/U0080.pdf)

OR

as a combination of the ASCII capital A and the combining mark for the acute accent: two codepoints: `0x0041` + `0x0301`

The problem with our current implementation is that the combining marks character set is not within our allowed unicode character set ranges. Encoding `Álvaro` as `A` + the accent results in an error, while encoding it with the combined `Á` is accepted.

We either want to: 
1.) Include the ranges for combining marks 
or
2.) Experiment with one of the unicode normalization forms to combine marks in incoming UTF8 handle name
or
3.) Ignore it. Test out some common text keyboard input methods and see if we ever run into this issue with the common methods users will be inputting characters like these. Perhaps the common keyboards always spit out the combined marks and it won't matter.

**Comment by saraswatpuneet** [comment]
Notes:
* Would like to support combined marks and have the ability to catch homoglyphs for the same, example `Álvaro` should be accepted but ideally its canonical version should be `alvaro` .
