### ISSUE TITLE
[Handles] Create package under handles and move handles utilities into it

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1365]
- [x] Turn `pallets/handles/src/utils` into a package named `handle-utils`
- [x] Update outside references and dependencies
- [x] Minimal set of dependencies inside `handle-utils`
- [x] Make sure confusables generator still works
- [x] Add in no_std requirement `#![cfg_attr(not(feature = "std"), no_std)]`
- [x] Add in Strong Doc Lints (See: pallets/README.md)

**Comment by rlaferla** [comment]
The strong doc lints will be added post-merge.
