### ISSUE TITLE
[Handles] Signed Extension for retire_handle 

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1370]
## Goals 
Frequency `Pays::No` extrinsics should implement respective `SignedExtensions` for pre-dispatch checks. In the handles pallet, we would like to implement the same for `retire_handle`

Acceptance Criteria:

- [x] `retire_handle()` being a `Pays::No` type transaction should have some pre-dispatch checks via an implementation of `HandlesSignedExtension` (an example being [here](https://github.com/LibertyDSNP/frequency/blob/5b880d3c9bc2069d767ba0b2744a29419c537e8e/pallets/stateful-storage/src/stateful_signed_extension.rs))
- [x] Implement validation logic for `HandlesSignedExtension`, some possible validations that can be done in extension are listed below
- [x] Unit tests(if needed)

_**Possible validations from retire_handle that can be moved to signed extension(please refine implementation time)**_
- [x] Validate if `msa` exists, an example being [here](https://github.com/LibertyDSNP/frequency/blob/5b880d3c9bc2069d767ba0b2744a29419c537e8e/pallets/msa/src/lib.rs#L1568)
- [x] Check for existence of `Handle` of `msa_id`
- [x] Possible check for encoding? (If we are checking encoding while claiming, this might be a redundant one)

**Comment by rlaferla** [comment]
The only extrinsic currently that requires this is `retire_handle()` which requires the following validations:

- The caller (delegator) already has a MSA id
- The MSA has a user handle associated with it
- The user handle is in a valid UTF-8 encoding

**Comment by saraswatpuneet** [comment]
Leaving this for discussion but not a blocker
>  Possible check for encoding? (If we are checking encoding while claiming, this might be a redundant one)

**Comment by rlaferla** [comment]
Additionally, we probably don't want to run the user handle association check because it would require that storage was read twice.  That would leave only one validation.  Agree?
