### ISSUE TITLE
Bug: Settings not working for getSchemaById RPC

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#1393]
Expected: `getBySchemaId` RPC settings either returns the bitwise or the array of set bits.

Actual: Returns an empty array

### RPC Call Rococo Schema 17
![image](https://user-images.githubusercontent.com/1252199/231877038-b8e02a5e-0bfb-4270-8237-cab2ef87008b.png)

### State Call RPC Rococo Schema 17
![image](https://user-images.githubusercontent.com/1252199/231877072-034fbc1e-6d20-4a38-8e7d-c7a7a9dba950.png)

**Comment by aramikm** [comment]
This looks like a typescript metadata UI issue
