### ISSUE TITLE
Build/run Frequency runtime without a relay chain

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#1401]
When running the chain as a solo local chain without a parachain, I cannot upgrade because the local solo chain is still waiting for the relay chain which doesn't exist.

Currently in `runtime/frequency/src/lib.rs`:
```rust
type OnSetCode = cumulus_pallet_parachain_system::ParachainSetCode<Self>;
```

This should be `type OnSetCode = ()` when running without a parachain (aka feature `frequency-rococo-local`) however changing that requires removing the other bits of the parachain pallets and config as well.

All doable with feature flags, but a fair amount of them.

Might also be worth seeing if we want to add the instant sealing wasm to the release builds for wasm upgrades

**Comment by rlaferla** [comment]
While it now builds and runs with feature flags, we are going to explore (in a spike) using CLI flags in addition to feature flags to run the node with/without the relay chain.

**Comment by rlaferla** [comment]
The new node now works but needs more extensive testing.

**Comment by rlaferla** [comment]
Attempting to upgrade the runtime produces this error:
![image](https://user-images.githubusercontent.com/1135694/235684200-2fe63c22-65d6-42e8-b6c3-bd005649b8b6.png)

**Comment by rlaferla** [comment]
The runtime upgrade is now working.  The spec_name fix also now allows developers to use a debugger to debug (set breakpoints, etc...) runtime code including our custom pallets.  Developers using VSCode should use the CodeLLDB extension to enable debugging.  @mattheworris and I will add a VS code configuration script as well.

**Comment by rlaferla** [comment]
The CI workflow needs to be updated to build a no-relay node binary and use it for the integration tests.  When complete, we can convert this PR from draft to review.

**Comment by rlaferla** [comment]
The Wiki also needs to be updated to reflect the new `frequency-no-relay` feature flag.

**Comment by rlaferla** [comment]
https://github.com/LibertyDSNP/frequency/issues/1488

**Comment by rlaferla** [comment]
https://github.com/LibertyDSNP/frequency/issues/1487
