### ISSUE TITLE
[Bug] SmallRng produces different ranges as compared to unit test

### ISSUE THREAD

**Issue by saraswatpuneet** [LibertyDSNP/frequency#1407]
SmallRng is not deterministically portable. (https://github.com/rust-random/rand/issues/1310)

We need to switch.

Desires:
- Small
- Portable and Deterministic
- Fast

Options:

- https://sr.ht/~icefox/oorandom/
- https://blog.logrocket.com/comparing-random-number-generators-rust/
- https://github.com/wilwade/wasm-rand-test

**Comment by rlaferla** [comment]
`oorandom` performs better than `rand` by a factor of 2.
![](https://files.slack.com/files-pri/TQ8L37KCP-F053LJL3Z7D/image.png)

![](https://files.slack.com/files-pri/TQ8L37KCP-F05366BUY23/image.png)

**Comment by rlaferla** [comment]
`rand`

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/1135694/232572777-4758aad6-49da-40a4-8bcc-76013fe9da2a.png">

**Comment by rlaferla** [comment]
`oorandom`

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/1135694/232572895-721ee391-699c-4aba-8128-d436121aca1d.png">

**Comment by rlaferla** [comment]
oorandom is consistent between Rust (Apple Silicon m2) and WASM:

![image](https://user-images.githubusercontent.com/1135694/232573046-6ae301d6-5114-43ec-91a0-31ee9c9871f9.png)
![image](https://user-images.githubusercontent.com/1135694/232573080-26733c96-05c1-4a25-adb4-3c158a828384.png)

**Comment by rlaferla** [comment]
Using `rand` crate:
% subwasm info target/production/wbuild/frequency-runtime/frequency_runtime.compact.compressed.wasm
Running subwasm v0.18.0
:weight_lifter: Runtime size:		0.664 MB (695,950 bytes)
🗜 Compressed:			Yes, 71.72%
:sparkles: Reserved meta:		OK - [6D, 65, 74, 61]
:gift: Metadata version:		V14
:fire: Core version:		frequency-27 (frequency-0.tx1.au1)
:ballot_box_with_ballot: system.setCode hash:		0xbfd341fd5d01d35ebb7012ba446ca7a6016f10df9f091a7ae4258986340ed03d
:ballot_box_with_ballot: authorizeUpgrade hash:	0x0906385734446452e54c398d95e7448f451a8ef3438d7946135aae145d7bd5e8
:hash: Blake2-256 hash:		0x6c32711092141b9abb05a6752b9daced8d03b6b5b651f101e2a777dcc5732ff5
:package: IPFS:			https://www.ipfs.io/ipfs/Qmc3nqN6wWemeGYWYr1r3848QUM5h1RpGYBwGuNsScQUWR

**Comment by rlaferla** [comment]
Using `oorandom` crate:

% subwasm info target/production/wbuild/frequency-runtime/frequency_runtime.compact.compressed.wasm
Running subwasm v0.18.0
:weight_lifter: Runtime size:		0.664 MB (695,734 bytes)
:compression: Compressed:			Yes, 71.72%
:sparkles: Reserved meta:		OK - [6D, 65, 74, 61]
:gift: Metadata version:		V14
:fire: Core version:		frequency-27 (frequency-0.tx1.au1)
:ballot_box_with_ballot: system.setCode hash:		0x27a4e9af29d37d22004be7be49d364d2cea47baae890d702be037f7124902b36
:ballot_box_with_ballot: authorizeUpgrade hash:	0xd3fb8ce2737a51962ad055376f01ebef4490fc554388e64108f580f071f4b28a
:hash: Blake2-256 hash:		0xfccc650528bfe47e542b8434f36a13e185a55c73f6606b5a6b6005e65ee817a7
:package: IPFS:			https://www.ipfs.io/ipfs/Qmdb7kDSaMCubJqdUMNkjSMbZZZxZGN1L3P4xR6ocDmH1U (edited)
