### ISSUE TITLE
[Handles] Fuzz testing 

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1438]
As we started fuzz testing we needed an issue to dump any findings to track items.

**Comment by wilwade** [comment]
Testing a bunch of the other word lists and such. While we allow some "bad" strings through, they are usually things like unix commands and such not web or db issues.

All of the word lists work with the exception of just the ones that are in our explicit word list (admin, all, etc...) or have explicitly rejected characters.


Considered complete for now.
