### ISSUE TITLE
[Spike] polkadot xcm 

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1454]
The Cross-Consensus Message Format, or XCM, is a messaging format and language used to communicate between consensus systems.

One of Polkadot's main functionalities is interoperability amongst parachains and any other participating consensus-driven systems. XCM is the language through which complex, cross-consensus interactions can occur. Two blockchains can "speak" XCM to seamlessly interact with each other using a standard messaging format.

We would like to get a spike going to research and review the following 
- XCM configurations
- Testing connections XCM
- Send a message from one parachain to another.

**Comment by enddynayn** [comment]
We can close in favor of alternative state-proof verification approach
