### ISSUE TITLE
off-chain and on-chain runtime chain specifications don’t match

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1463]
Basically, the off-chain and on-chain runtime spec names don’t match.  This is preventing native code execution and prevents developers from using the debugger for palette and runtime code.

@rlaferla and @mattheworris in your session please add any details to this that aren't captured above.

**Comment by rlaferla** [comment]
This is addressed by #1401

**Comment by rlaferla** [comment]
In the PR for this issue, @mattheworris will add a configuration for VSCode debugging.  Developers should install the CodeLLDB extension which will allow interactive debugging of runtime/pallet code with a debugger inside VSCode.  The problem itself is already fixed with #1401.
