### ISSUE TITLE
Signing Tool

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1465]
We have a lot of things that are hard to setup because the signing is hard. Adding a key to an MSA via Polkadotjs UI is a pain. We should offer a web ui to do signing (and the actual submission as well?)

A tool that is close to this (although we should do it better than this): https://github.com/LibertyDSNP/time-release-ui
Features:

- Select network?
- Select signature
- Connect Polkadotjs Extension and select address
- Complete signature data (and encode correctly)
- Sign with Polkadotjs
- Display signature

Signing Data:

- handles.claim_handle
- msa.create_sponsored_account_with_delegation
- msa.grant_delegation
- msa.add_public_key_to_msa
- stateful_storage.apply_item_actions_with_signature
- stateful_storage.upsert_page_with_signature
- stateful_storage.delete_page_with_signature

**Comment by shannonwells** [comment]
The Signing UI is available here: https://libertydsnp.github.io/signing-ui/
