### ISSUE TITLE
Fix failing CI release workflow

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#1485]
The release workflow currently fails to build runtimes with the following error in "Build Deterministic WASM" job:

```
error: failed to run custom build command for `polkadot-runtime v0.9.36 (https://github.com/paritytech/polkadot?branch=release-v0.9.36#dc25abc7)`
```

Here is an example of the failed job: https://github.com/LibertyDSNP/frequency/actions/runs/4917731574/jobs/8783304925

It is believed to be fixed by this upcoming PR: https://github.com/LibertyDSNP/frequency/pull/1464

Blocked by:
- https://github.com/LibertyDSNP/frequency/pull/1464

**Comment by wilwade** [comment]
Related issue: https://github.com/chevdor/srtool-cli/issues/25
