### ISSUE TITLE
Integration tests on Rococo msa/

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1505]
Integration tests on Rococo msa/

https://github.com/LibertyDSNP/frequency/tree/main/integration-tests/msa

These should run both rococo and local. 
If we think we should skip any of these it will be up to the developers to make the judgment call on how valuable it would be to run on Rococo.

**Comment by johnmela** [comment]
This was completed in this PR https://github.com/LibertyDSNP/frequency/pull/1481
