### ISSUE TITLE
[Spike] Increase startup speed 

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1540]
We've seen some hints that our Frequency binary is slower to start than some other chains. Let's figure out why.

Timebox: 3 days MAX!

Outcomes:
- Issues created to fix (if any)
- Notes in this issue on how to test

Hints:
- Frequency Dev startup 2x slower than Acala and Moonbeam
    - Frequency startup (no-relay, manual) = 22 secs
    - Moonbeam startup (manual) = 9 secs
    - Acala (dev) = 12 secs
- When doing initial sync, Frequency timed out some health checks with OnFinality.

Ideas (so far):
- Takes a while to run hardware benchmarks? (Should we disable by default)
- ?

**Comment by rlaferla** [comment]
One possibility is that the no-relay node is assembling collators which is usually for parachains.

```
2023-07-31 13:21:39.320  INFO main pallet_collator_selection::pallet: assembling new collators for new session 0 at #0    
2023-07-31 13:21:39.320  INFO main pallet_collator_selection::pallet: assembling new collators for new session 1 at #0    

```

**Comment by rlaferla** [comment]
I think this issue is actually the difference between the `debug` and `release` builds.

The `debug` build of Frequency takes around 22 seconds but the `release` build only takes 6 seconds.  The `debug` build of Moonbeam  takes around 16 seconds and the `release` build only takes 8 seconds.
