### ISSUE TITLE
Remove/deprecate redundant error `StakingAccountNotFound`

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/frequency#1560]
`StakingAccountNotFound` is used only once when attempting to access a staking account that does not exist for a given AccountId, in `decrease_active_staking_balance`.  Everywhere else, the error `NotAStakingAccount` is used.

Acceptance criteria:
* `StakingAccountNotFound` is removed and/or deprecated
* `decrease_active_staking_balance` instead uses `NotAStakingAccount`
* The description for `NotAStakingAccount` is corrected to say (phrasing up to you) that it occurs when trying to access a staking account for an account id when there isn't one instead of specifically when it's the origin.

**Comment by f-gate** [comment]
i would like to pick this up if possible.

**Comment by wilwade** [comment]
Closed by #1669
