### ISSUE TITLE
Enable Warp Sync

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#1585]
Warp sync allows fast syncing and is currently not working. After #1270, we should be able to enable it.

Related:
- Moonbeam Upgrade PR that enabled warp sync for them with 0.9.40: https://github.com/PureStake/moonbeam/pull/2202
- Polkadot PR enabling Warp Sync: https://github.com/paritytech/polkadot/pull/3382

**Comment by rlaferla** [comment]
https://spec.polkadot.network/chap-sync

**Comment by rlaferla** [comment]
CLI options from Moonbeam:

```
--sync <SYNC_MODE>
          Blockchain syncing mode.
          
          - `full`: Download and validate full blockchain history.
          - `fast`: Download blocks and the latest state only.
          - `fast-unsafe`: Same as `fast`, but skip downloading state proofs.
          - `warp`: Download the latest state and proof.
          
          [default: full]

          Possible values:
          - full:
            Full sync. Download end verify all blocks
          - fast:
            Download blocks without executing them. Download latest state with proofs
          - fast-unsafe:
            Download blocks without executing them. Download latest state without proofs
          - warp:
            Prove finality and download the latest state

```

**Comment by rlaferla** [comment]
How do we test warp sync to ensure integrity of data and consensus?

**Comment by wilwade** [comment]
The security is based on the relay chain peering. If we have a state with a root that matches one on the relay chain, then we know that state is good.

For warping the relay chain, it is almost the same, except it is that the additional blocks are built on the warp'd block.

While it is possible to chose a bad warp provider it is no different that choosing a bad chain spec or connecting to a bad bootnode.
