### ISSUE TITLE
Make sure overhead block weights are generated correctly

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#1586]
I'm not sure this we should be using `No Relay` for overhead weights, as it doesn't include the parachain interaction overhead weights.

Talk with @JoeCap08055 who setup the overhead benchmarks and see what he thinks. The benchmarks look the same below, so perhaps this doesn't matter.

Needs to be resolved before the next release.

_Originally posted by @wilwade in https://github.com/LibertyDSNP/frequency/pull/1574#discussion_r1217995423_

**Comment by JoeCap08055** [comment]
I think `NoRelay` is fine... the point of the overhead benchmarks is to calculate the overhead in executing an extrinsic, not including consensus, which would be the part involving the relay chain. None of the substrate examples seem to show running in a relay chain environment. We're interesting in the effort involved in _creating_ a block, not _finalizing_ it.

**Comment by JoeCap08055** [comment]
For reference:
https://github.com/paritytech/substrate/blob/master/utils/frame/benchmarking-cli/src/overhead/README.md

**Comment by JoeCap08055** [comment]
For confirmation, could be worth asking Parity.
