### ISSUE TITLE
Deprecated associated function `sc_executor::NativeElseWasmExecutor::<D>::new`

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#1603]
We should remove the deprecated warning override in `node/service/src/service.rs`

warning: use of deprecated associated function `sc_executor::NativeElseWasmExecutor::<D>::new`: use `Self::new_with_wasm_executor` method instead of it

I left it as-is for debugging, but I will test with the new suggestion. (The name implies no native, but it's not clear)

_Originally posted by @mattheworris in https://github.com/LibertyDSNP/frequency/pull/1590#discussion_r1228547049_

**Comment by mattheworris** [comment]
Resolved in v1.0.0 upgrade: using `new_with_wasm_executor` now
