### ISSUE TITLE
Upgrade Accounts after upgrading to runtime v0.9.42

### ISSUE THREAD

**Issue by mattheworris** [LibertyDSNP/frequency#1604]
v.0.9.42 upgrade: #1590 
As per: (https://forum.polkadot.network/t/polkadot-release-analysis-v0-9-41-v0-9-42/2828/1) and (https://github.com/paritytech/substrate/pull/12951)

After introducing a runtime with this change in it, chains should ensure that all accounts are upgraded by repeatedly calling [upgrade_accounts](https://github.com/paritytech/substrate/blob/d59d30074e8e2224b2372a631a36e7a53d615310/frame/balances/src/lib.rs#L655-L686) giving it account IDs which are not yet upgraded. A script which does this shall be provided.

The goal of this issue is to make sure accounts get upgraded.

- [x] Rococo
- [x] Mainnet

**Comment by mattheworris** [comment]
Parity has provided the following script:

https://github.com/ggwpez/substrate-scripts/blob/master/upgrade-accounts.py

**Comment by shannonwells** [comment]
Script run on [Frequency-rococo](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.rococo.frequency.xyz#/explorer/query/0xfab350e25d4e3acbb54cd746bb2006b63da0aba12aeff5374fc092ad3df1e032)

## Note 
This script does not need special authorization; any account with token may use it. The script simply calls the Balances::upgrade_account extrinsic on each eligible account.

Here's a list of the 79 accounts that were upgraded:
```json
["5CrV2vKHjkTPYFt2wWodjM7VAWWeAz29JRKtDfW62ie5JT2N", "5DPuboPrbBJ8R9jU6H6vZQqdEXzEznfbFN7vhwFCjeieqSPa", "5H3cWDY3FSyQSMyL3tSZNS2KEhHDrT66J2mvfhXQxnsEtvpu", "5CqNHnruwJ9k1Sy3qhrfwcBhEjbRB1QSwYHRjufq8SLdssnf", "5CZfGaHCeY73B9zX1M3gYE8DZkEYJqmoWRy8JnzisWbUzCuT", "5HHYR3wMmvrb2CkhTgBP7Nj7T2ZDWLsG23MD47xKtTWRYMU9", "5EvTXx5eTU89ej27h3MpbPFhLYnamBqocEKFg37sbqUcneRs", "5GgFuDddCkd7Gd77jv9Cf3Kvf4M31wcZpyXgHvP3wxx1q9Po", "5FCBp12v7uycmb9q9xzdYXFwEnb53gNFgSUpTWAaxncb3Kyw", "5EbnaqsS2JZqHJ3UXHMQb3jD9bwWyZDTS65q3xx74peb3qth", "5DA1kdPGmMUnyxs6YJf6vAadJH3hAjUbMtBMwyd4RUweCKX7", "5FU1MMF9yvrFURaGEeYrUuFy3ZxG2hcqsJJy838wCfnkyt7u", "5F9WZZmgT1bc5GWZZVoMDsEYubPGCBQh4nKhvPzEAMLg1xXf", "5E9o6Sp8VPZ8aa8kAR88gisE3Uf9vrcEhrWyuWDahkMAhKHn", "5GsJwrr3sjnkwbU13w8NmE3NF7pZoCmrPqNyfpodrfV3Wct4", "5HT7ms3Lg2LVSdfTrZCVSyYK8U4TAVKpJjTKMPFaEdS3sd8m", "5F4R3YYeW7NFa7LBa5tMiCr9CJhqBvnhzAoegoAGyNMWHfLS", "5DXimJ2MoYKqw6CavTBUS6RZFCPjNaaw7jsGRQBhR6wDP6ya", "5E7BRKnT4yMk2GmSy1rjb1vYMNKawQjQYbaKhm8yJJBC4A7j", "5DUYC2SVDoW8aU8yBDmjsdhaWJEXtY6U9v8skvUaUDyfWZ6o", "5CXzEC3KecLEzdNGuFTKcDdPJZgYbi3Gm4AS4VyQSu4amx1K", "5CA5x7GiXAvZuHPTx49TFCB8YJCWrrkYg6sZ1fK6BZuxwfHH", "5EyLduUEpNfUox5HuogrhbKugAdHnsLHrysKSWL6u4TQFAra", "5HTMc16m5jqtfCM4Eo9SZhZPmsVSQUsiELiUcEDrcThQutag", "5FZvXTWPq1bxM7FccZggJFCDx7iFkeJWjRJLgmD7oDa8qBDV", "5Ecmm5v6rPPakTJ5e3sQH5YHxZbu16UJXbgv1vEowD93JwCa", "5Cu7YHhr9MUyGuuD96ZSCgCKkAw1LGDeovw1bzTg7CV2mcbA", "5Fbsvd6JW3cQdxc3XgKtNqvDzFThSZe299zEJpC7UfFTd2HH", "5CXnMFFgruHxAFtvCogwm8TFygWg1MWd9KhMnfEPbRdCpf74", "5FQpQF4ELifbUK4Zu7v12ezC9m4g6frNU7PFH4h3hQhmVK1Y", "5CBCJDFUH4ArK7JeNeiL2L6p1aJ4daePK9nR9qT3LC4e8i5i", "5CS7Avjba185JFza2EjyCnZMHQKEhd2JJWmbijjSnj4yuH8Y", "5Eeo3iqiphpAnzsY5ezckXCiFaxnn8PijphmwaxjiX7YJsVA", "5CWzQaAJFqYoF1bZWsvEnzMQDGokk2csTFBwfPpo1oNfBGkn", "5DMSK8uDymyfUiJYYZkWgRAcXoTSJ7nBiQNKyVzRrh4pRQWy", "5D5H1tDCpxZYutrNTBo1rqaZ3kdmfS4w7boZiEPenudLADxr", "5Fmm3njasniZUBagiJyfaikZALQfBHrXEp68E8bNWeV53kav", "5ETnrcfDwCTKZt5pLoKcLNbbwUcddkDAxEjtcgibAtkDhBBe", "5H3LMYGdGCAshoan7i7nj82wLFMaDKETZhyc7pARpDB7DK2M", "5G9UqeufBDWjTaNpwza6RjMMN3dYDWpx38kw8WgJyyaBVMHo", "5GsFNUxHqB6r1TQorv5MJdqwVn4qtkafeoq2A7EPCHR5B6sX", "5Gpj9RtkHz2CZ7kZDvNyXUGA7RKC1vG2nE5JdBHfdYZqkQZV", "5Deh6p5gTmyavv89ukA6Det5o9WvszTWUBbXTvszavWD4LrS", "5DA21R7n7GrvnSLLSCXosZeKhrNVVzhXJFZ382RHeNx4wFdy", "5CGMbwJgYMXJ3t6mrPQ8aYPLi6DJd96heFXv4RPcHv1SohAp", "5Gc33qRGVL2NGZ5NQ7Ec2AdxEM3wLNNNpQWQVn4WyK5ttiHh", "5DvkJd6Csj6WAyNzPokY9axSL63Wm3EmSP1dNoGuu8NaBZ2b", "5FBihf9Vpnq31sDMLuUf2S6ow1JcfV9mk6Ekzs28Yc5kcFnQ", "5DAHZs7iqXxWngCQyhYEj7a2KZKrPXY8SopCDxECTLR3Knxq", "5H3jNeq4gp7Tg1LW9mAhfkqp3cFu1GGpCPHdZNsPaNNRLCPo", "5C5wCszpdMLhQK1ovrCRiWLXbDbZa6CQzoFfX3pj5tR35dLW", "5DhbAAAGN8NoACsCS9VF8YWscH5niruxp64zhm47BhnxiyUN", "5F9cvFYQQi4sHfS1j2Wri97S5sqsz2H3WQxZmsfx1P8eh318", "5FTjjCB6Xe68uMJDWViaVzLgAbS66xef7qqNWCWtjwN3YaUW", "5E7a6BZwZ2oCrst13EtfjCkVarFuDjcLPNmNVETgtUuVtNEx", "5HmcreGLq25iA7fiyb6An4YVWC3k1Cq8SQgYn2Qpeepq24nV", "5DqepxvV4fvkTux9BAd7mo2R5VNz6hEEC8MbvWoAPYMVAcZL", "5DyaB63mD3Az99obmgvqK3ynHER7aqKSsN7eDNb12A4ryotf", "5Ev6tucLA3T48ESPWGd6z7XcTx4ibk4QjERP5i62ZaWWPc4w", "5CiJXZxsko8YZGhTZAwrhREUzjCVEGwNE7Fgrf1twbt8WsmY", "5HKXEFkNLeutZ2yZ9mbG2v5AbTDMXhza9VEfeDCiJGGBUyi3", "5GCQGX2pz2AEBqLxm845pmBdLK3f63hBbN4yj5tobfTztsx6", "5HQbXzL71awcL2m3B42jYhTWvdYvDqzSuPbAbxUpPmuzZ1Z3", "5EZG2Lb6nRNcgUJZa3Lh6V4HcamRYUC2QEbnmyjfNqPyTF5M", "5DPvW1bAVUVnRPxPUKjpqAN4Zb1vP3ZMec4zgJkp2gP4iopp", "5GuwBW3r4pzYuWhVv7dexxy4tMnCQtfgM8mk8cqeqxwunbwX", "5FsMWwJ7L6s1jjdRycJytFyPfuudofbZGW2wxYoeWFLQ3gT6", "5ECF2TovSXQ3htfxY11L1pQiW3aBwzi37p5ALshgm2BzuqFj", "5EnU45xQxHjuwemQGqaURdM5h5VLtmRtAkrrmcs9jjVVFcUC", "5EcSbFdU5Ui8apANFomhitkB12jAwi5AxUFKThTPrF8nzk4v", "5FC5D1Ht2BmtaLN5WxVUZpTAFTLatxhozXqecDx35p5WjrTT", "5C4qDiWc479hmAUDca3hhQvbyMtLUUzMf9AR1r8etXj4uzFR", "5EhJCUjo7JcFUgfyZD6QeENnp6ibzgWWwhjwMXZhenUDxufT", "5Dw9hdb8Wy3cMFf1ZpQh5HuK2GvMNMcxfka4JsM2GRpjqHSA", "5CVDhWtHofjGUJPiVGGx5R56RoXC1T1CdCn95LzpxpnyRheW", "5CnkanjUQbwNpDc1XBRf8LpVEd5Md4sWo71pLa8QMXhjh7ZP", "5G6aBZheBLpFsBkPYQCzvxoDGUjRYX5Rr7qemmJ5NwNjvrbY", "5Gy7GrfT6GkVUwjWme1KikHBFuN5hyDLxsALuXS8bNNTrUsK", "5D7U6u7Jz3wXu6TQh24B3fRHmnG1a6VLCMtm61aRUsJ8HD6J"]
```

**Comment by shannonwells** [comment]
There are only 23 accounts to convert on mainnet.

**Comment by shannonwells** [comment]
24 accounts on Mainnet upgraded.  [Transaction here](https://cloudflare-ipfs.com/ipns/dotapps.io/?rpc=wss%3A%2F%2F0.rpc.frequency.xyz#/extrinsics/decode/0xa90d840092e8dba6b1cbd25e32a786a128406a24ec3e7f8c0c17c65e7d146f14f0fd3e6901345cb770af9d0ba7091c8529242746e71da5d73091b5728cf6c54be1b5b1f72ddb78b419eccede9dcbc163460332677325670a50dcedafaa6a68a27886b5748f002101000a066030ec7cb48f85964c684978fb687b8806837aa36ed38201e2836bce893bc9d443945c98162126c17d4e25d23670c0384411b0dbae18de025448f6a6883bab3d70b037cc0becffb83a913e90b9f860ec18cf9b92863e92a17e347304a3909e9665102b35abe54aacb29e3e70e1ea0201aad153ac7a2b1d548ff4460a647525a963ca8f44440bfb630ee6cb79e6b8def51117da55705ef27584b8e630f6dec10a59fcac9ce9c9807732f092a84efde7cfbf77b4c3abedffadfb12cc63c6f683660592e8dba6b1cbd25e32a786a128406a24ec3e7f8c0c17c65e7d146f14f0fd3e6912a5a0df9fa8308e356708fc97736531fb8e815e49ec345d7acd087ed39ba5307440be697cd6bbdff1963f1cc8aeb22569316bb30eb88827dcef991d467d5e3acee0137a698a9a616193c80550185ea91387f16208544a8b47d477703b055b4b945f1fa930221ba69ee5ddcbbf53bece80a413c68e86cf4f3c232a6005d3b30d52f4b36c75e24da6a9d4b131678786f2209ab8fe9cddbae3f33cd474222504621643c53bca53a436249e2aeda7d6b93dec1e7f3955006eaaf66d45bf7aaf2d6b16738709376d7833f016a592fb9849e2e3a9de11468c83adae8a010599dc066dc6a3fc153ed81e1a974f2559888b0778ce1ce38540e7b0749109a463d0ac0b1ab2e2c06691cfd6c042d431b0830507b4414d6eeda4fedc800fd8416284d83f736ca4dba72792a5a1a976b5f75f2fcf37b246b821e6f6c82f730716e265f9ca096e68bbbeb2dfd1db5578f79cca307749e007c056d26e1010b16acf284e89727f3c96cebae385626211b324525b4b3037b80e9bebdb6b435d319fa282c394fd2ecc83b27c480b8160af96e9633a3c9a08e2726d8f3dec1254aca68ee67b15c4152e62379bcce8b728b9f55f4cbd63e8f55f0d937f64c8918b770dff42a3d32672f0895d9f599518ade88005f3b7be3717943b528915d2ad12aec76630769d111564394a6f1a59c6697841e9bd45e94870baafc139040c351e8edcfb21ece0c30bb0eef5bf0d69f815ba1c1524042fbe411609096e434c51fa15b3f959500d3d6f)
