### ISSUE TITLE
[user handles] handle swapping

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1627]
Currently, we don't support swapping a handle for a new one. Right now we need to retire & claim to meet this use case. Although this works, it makes for a poor provider/wallet developer experience.

As a provider/wallet, I would like a single extrinsic for swapping a handle + instruction what is the optimal way of listening handle changes on the blockchain. 

## Req
- Should be able to be called with Capacity

## Open Questions
- Should we instead just allow claiming a handle when an existing handle is already claimed? aka swap because a new handle is being claimed instead of throwing an error when a handle is claimed?

## Implementation Notes
- Should require the user signature just like claiming a handle

**Comment by rlaferla** [comment]
@wilwade wrote:

_We extend the ClaimHandle payload with an optional prior_handle
For a new claim with no existing handle `prior_handle` would be empty
For an "edit" `prior_handle` needs to be the current handle
We still use the current `claim_handle` extrinsic, but now error if:
There is a handle and it doesn't match the proir_handle
So we get the visibility for the user
We get lower chance of race conditions (although not removed)
We get explicit actions for developers
Questions: I think we can extend `ClaimHandle` payload without breaking existing setups, but not sure._

**Comment by rlaferla** [comment]
The old handle should be retired if the new claim handle call was successful.

**Comment by rlaferla** [comment]
![image](https://github.com/LibertyDSNP/frequency/assets/1135694/15e5a618-1399-414c-bdd4-d25a66da2759)

**Comment by wilwade** [comment]
@rlaferla Would we want HandleChanged or just emit both HandleRetired and HandleClaimed?

**Comment by rlaferla** [comment]
Another possibility is to add the old handle to `HandleClaimed` to be consistent with the `claim_handle()` extrinsic.

**Comment by rlaferla** [comment]
When considering deprecation and backwards compatibility and benchmarking, it is cleaner to create a separate `change_handle()` extrinsic than overloading `claim_handle()` to allow an optional old handle to indicate a change handle path.  For one, by not deprecating `claim_handle()`, there will be no need to remove it in the future nor for developers to make changes to their code.

**Comment by rlaferla** [comment]
After discussing this with @wilwade, we have decided to create a separate `change_handle()` extrinsic.

**Comment by rlaferla** [comment]
<img width="1259" alt="image" src="https://github.com/LibertyDSNP/frequency/assets/1135694/7f4febaf-c926-43cf-8a63-b94ec9b0407b">

**Comment by wilwade** [comment]
@rlaferla Just added an AC that might not have been clear before. This should be callable with pay_with_capacity.

**Comment by rlaferla** [comment]
<img width="1243" alt="image" src="https://github.com/LibertyDSNP/frequency/assets/1135694/6c2a87ea-258e-4ab5-bbe0-9850ac391bf8">
