### ISSUE TITLE
Read Time Validation against Avro Schemas

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#164]
As a user of MRC, I want the Custom RPC to validate schema before it passes messages to me so that all messages I get from the custom RPC are known to be valid.

## Questions
- Should there be a separate rpc for getting it without doing this check? Or a way to turn it off?

**Comment by saraswatpuneet** [comment]
Why would we need a read time validation of schema, as we can with confidence, say that messages stored on chain adhere to some valid schema 

Read time validation can just simply ensure that correct messages are being sent for the requested schema_id

**Comment by wilwade** [comment]
I should have noted, this is an alternative to validating data against schema at write time.

**Comment by saraswatpuneet** [comment]
I was thinking, if we can just do read time validation and basic validations write time, we should be able to support many formats since validation will be off chain, otherwise we will scramble for no_std versions for any format we support in future, that also speed up extensibility

**Comment by wilwade** [comment]
Moved to https://github.com/LibertyDSNP/frequency/issues/59
