### ISSUE TITLE
verify handles supported langs 

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#1646]
We got a list from a provider that support is needed, my guess is they are all Latin chars with the expectation of greek..
But it's worth a quick validation... 

```
Dutch
Norwegian
English
Italian
Korean
Polish
Arabic
Chinese
German
Czech
Hebrew
Spanish
Greek
Japanese
Swedish
Finnish
French
Portuguese
Danish
```

**Comment by wilwade** [comment]
Verification Results: One character missing.

- German
    - Missing Latin Extended Additional Range: 1E00–1EF for the char `ẞ`
    - https://www.unicode.org/charts/PDF/U1E00.pdf
    
Note: There will always be some characters missing from CJK, but it appears all that unicode supports are in.
