### ISSUE TITLE
Update Benchmarks to commit using a "Benchmark Runner" name

### ISSUE THREAD

**Issue by rlaferla** [LibertyDSNP/frequency#1650]
![image](https://github.com/LibertyDSNP/frequency/assets/1135694/7e172f9e-7f10-4e87-8acf-4a2a93df2f5c)

**Comment by wilwade** [comment]
Appears to be correct now.
<img width="415" alt="image" src="https://github.com/LibertyDSNP/frequency/assets/1252199/1e22a62c-d284-4664-9fea-6bf5e8d56a3f">
<img width="405" alt="image" src="https://github.com/LibertyDSNP/frequency/assets/1252199/eb46867e-5a0b-4017-a3dd-aa2e8872458e">
