### ISSUE TITLE
Review any apps/services that connect to the chain for WS/http port changes

### ISSUE THREAD

**Issue by rlaferla** [LibertyDSNP/frequency#1659]
- [x] Metadata Portal (uses `wss:` in config.toml)
- [x] DSNP metrics (uses `ws://localhost:9944`)
- [x] Reconnection service (might need update on provider side)
- [x] Faucet (uses `wss`)
- [x] [Faucet](https://github.com/search?q=repo%3ALibertyDSNP%2Ffrequency-testnet-faucet%209933&type=code) Test code
- [x] [DSNP Schemas](https://github.com/search?q=repo%3ALibertyDSNP%2Fschemas%209933&type=code): Docker File
- [x] [DSNP Schemas](https://github.com/search?q=repo%3ALibertyDSNP%2Fschemas%209933&type=code): Deploy Script

If the service is private add to https://docs.google.com/document/d/1ZtWjfaMcu82GY2VJy-ceaGxR016CR4P2xeO0dTF_LZk/edit?usp=sharing

**Comment by JoeCap08055** [comment]
The wallet-scanner has the option to take either an `http[s]` or `ws[s]` URL; I think currently devops has it deployed using http because we were having disconnection issues with wss.

**Comment by JoeCap08055** [comment]
reconnection-service also will parse an http connection URL, but it doesn't get used for that app, really, because it's difficult to call extrinsics using the Http interface.
