### ISSUE TITLE
Polkadotjs Assumes a 50% + 1 External Propose Majority

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#1664]
However, Frequency currently has it set to 3/5 a super majority.

This will mean the UI allows it to be closed before the correct majority is reached and will fail with BadOrigin (due to a lack of enough votes).

On Mainnet this is not an issue as the 3/5 is the same as a simple majority as there are 5 council members. (Testnet has 11).

Proposed: We should switch to a simple majority as well.

https://github.com/LibertyDSNP/frequency/blob/1535f15386791f79db8c808d22df7ad7c2883e0f/runtime/frequency/src/lib.rs#L611

```rust
/// A simple-majority of 50% + 1 can have the next scheduled referendum be a straight majority-carries vote.
type ExternalMajorityOrigin = EitherOfDiverse<
  pallet_collective::EnsureProportionAtLeast<AccountId, CouncilCollective, 1, 2>,
  frame_system::EnsureRoot<AccountId>,
>;
```

**Comment by rlaferla** [comment]
The commit hash doesn't appear to be correct.  It doesn't show any changes to lib.rs.

**Comment by wilwade** [comment]
@rlaferla that's just showing where it is. The inline code is the suggested change.
