### ISSUE TITLE
RPC and Runtime API returns incorrect information with complete provider revocation

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#1682]
Setup:
1. Add Schemas 1 and 2
1. Add Provider X
1. Add User A
2. User A delegates to Provider X with Schemas 1 and 2

Scenario:
1. Block 10 (Post-Setup)
2. Block 11: User calls `revoke_delegation_by_delegator` OR Provider calls `revoke_delegation_by_provider`
3. Block 12: Empty
4. Call RPC `check_delegations` and see that schemas 1 and 2 have been revoked (or check the chain state)
2. Call RPC `get_granted_schemas_by_msa_id` or Runtime API `get_granted_schemas_by_msa_id`

Scenario 1
1. Block 10 (Post-Setup)
2. Block 11: User calls `revoke_delegation_by_delegator`
3. Block 12: Empty
4. Call RPC `check_delegations` and see that schemas 1 and 2 have been revoked (or check the chain state)
2. Call RPC `get_granted_schemas_by_msa_id` or Runtime API `get_granted_schemas_by_msa_id`

Expected: Schemas 1 and 2 should show as revoked on block 11.

Actual: Schemas 1 and 2 shows as valid.

- [x] RPC `get_granted_schemas_by_msa_id` correctly shows completely revoked providers
- [x] RuntimeAPI `get_granted_schemas_by_msa_id` correctly shows completely revoked providers

**Comment by rlaferla** [comment]
Does `revoke_permissions_for_schemas()` need to be called when `revoke_delegation_by_delegator()` or `revoke_delegation_by_provider()` are invoked?

**Comment by wilwade** [comment]
Due to the cost of iteration, we have the top level value that effectively means, "all remaining zeros are revoked at block." While not ideal, that shouldn't reflect on the read where it can have the single standard response on the output.
