### ISSUE TITLE
Getting Capacity

### ISSUE THREAD

**Issue by enddynayn** [LibertyDSNP/frequency#169]
**Description**

As a service provider, I want to be able to stake token, so that I acquire Capacity

**Acceptance Criteria**:

- Display extrinsic in Polkadot UI.
- A balance of the total capacity associated to an MSA should increase by staking amount.
- Staking amount should be reserved from token account.
    - Token account free balance should decrease by staking amount
    - Token account reserved balance should increase by staking amount.
- Service provider should receive Capacity at 1 token to 1 Capacity.
- Validation:
    - the amount stake should be greater than 0.
    - a user should not be able to stake to a non-existing MsaId.
    - a user should not be able to stake to two different MsaIds with the same key.
    - a user staking does not need to have an MsaId association.
    
**Architecture**
1. create extrinsic
2. create storage
3. ~~To hold token for staking [NamedReserveableCurrency](https://substrate.stackexchange.com/questions/437/difference-between-reservablecurrency-and-namedreservablecurrency) trait implementation can be used.~~
4. use [LockableCurrency](https://paritytech.github.io/substrate/master/frame_support/traits/trait.LockableCurrency.html) instead for placing a hold. Here is a recipe to how to use LockableCurrency [Lock](https://substrate.recipes/currency.html)

Note the change from NamedReserveableCurrency to LockableCurrency is so that it opens up the possibility that stakers can use those tokens to vote in governance. Think of NamedReserveableCurrency as a deposit for an apartment rental. The money is yours but is withdrawn from your account and your balance is reduced. LockableCurrency is like a bank placing a hold on your funds. You can still see the those funds in your account but you cannot go below the holding amount.

```rust
 #[pallet::storage]
pub type CapacityOf<T: Config> = StorageMap<_, Blake2_128Concat, MessageSenderId, Details<T::Balance>>;

pub struct CapacityDetails {
	pub used: Balance,
	pub total_available: Balance,
}
```

```rust
#[pallet::storage]
pub type Staking<T: Config> = StorageMap<_, Blake2_128Concat, T::AccountId, StakingDetails<T::Balance>>;
pub struct StakingDetails<Balance> {
	pub msa_id: MessageSenderId,
	pub total_reserved: Balance,
}
```

```rust
pub fn stake(origin: OriginFor<T>, account: MessageSenderId, amount: BalanceOf<T>)
```

```rust
pub enum Event<T: Config> {
  Staked { account: T::AccountId, msa_id: MessageSenderId, amount: BalanceOf<T> },
```

**Comment by wilwade** [comment]
Duplicate
