### ISSUE TITLE
Capacity and Token security

### ISSUE THREAD

**Issue by enddynayn** [LibertyDSNP/frequency#170]
**Description**

As a staker, I want to reduce the exposure of my token account (A.K.A stash account) when making staking related actions, so that I can increase the security of my account.

**Acceptance Criteria**:

- I should be able to submit an unstaking action with a different account.

**Note:**

This can be accomplished in two ways:

1. Adding Proxy and setting costume config
2. Adding Stash/Controller model. 

Both achieve the same goal of limiting the exposure of your stash account. The proxy pallet is an abstraction over the stash/controller model. A Stash account is an account that you care a lot about and want minimize the amount of times you expose it when submitting transactions. A controller account is an account that the stash account can delegate too for making transactions on behalf of the stash account. 

Stash/Controller model will help reduce the exposure of using your stash account. For example, when taking actions to stake and unstake a controller account is used. As we implement more features like, adding the ability for users to increase stake, the stash account is required for submitting this kind of transaction. We can further limit this exposure by introducing the Proxy Pallet. The proxy pallet would allow delegating to another account to submit this transaction. We would need to configure, not modify, with additional capacity staking related extrinsic calls. 

Proxy will allow to abstract all delegation to the Proxy pallet. The pallet has a cost for storing the delegation and requires an additional cost.

**Adding Proxy**

- Does not change the interface for stashing
- Abstract the ability to delegate to a different account
- User pays for creating the delegation
- requires adding custom configuration to Proxy Pallet for capacity staking. (probably no code changes).
- Abstraction over stash/controller model

**Stash/Controller**

- update the pallet to add mapping between a stash and controller accounts.
- update the pallet to include a parameter for setting a controller account.
- would require more custom logic to switch a controller account here.
- Stash and controller account can be the same.
- Stash account is required for increasing the stake amount.

**Stash/Controller + Proxy**

- Further limit this exposure of stash account that may be required when increasing stake.
- Proxy pallet is used to delegate to a proxy and red

**Comment by wilwade** [comment]
Archived.
