### ISSUE TITLE
Adjusted weight fee calculation for capacity

### ISSUE THREAD

**Issue by enddynayn** [LibertyDSNP/frequency#1709]
**Description**
The adjustment weight fee seems to be miscalculated for capacity by including the `base_fee` and `len_fee`. According to the documentation on the documentation the adjusted_weight_fee is calculated:

```
 adjusted_weight_fee = targeted_fee_adjustment * weight_fee
```

We are currently adding both weight and length fees.
 
```
let adjusted_weight_fee = base_fee.saturating_add(weight_fee).saturating_add(len_fee);
let tip = Zero::zero();

fees = FeeDetails {
  inclusion_fee: Some(InclusionFee { base_fee, len_fee, adjusted_weight_fee }),
  tip,
};
```

https://github.com/LibertyDSNP/frequency/blob/501d622245cd2f886e13a3dd4c68ca1963c2bf19/pallets/frequency-tx-payment/src/lib.rs#L302

https://github.com/paritytech/substrate/blob/033d4e86cc7eff0066cd376b9375f815761d653c/frame/transaction-payment/src/types.rs#L47

Potential Solution
set adjusted-weight-fee to weight-fee.

**Comment by enddynayn** [comment]
After some discussions, we might have modified for Capacity. To not create confusion in the future perhaps the solution is to document the reasoning.

**Comment by saraswatpuneet** [comment]
I think to avoid confusion with the meaning of these terms with respect to usage within balances pallet, 

we should just return a number and thats all a consumer needs to know ideally (total capacity cost of a tx) ?
