### ISSUE TITLE
Capacity unstaking

### ISSUE THREAD

**Issue by enddynayn** [LibertyDSNP/frequency#171]
**Description** 
As a service provider, I want to be able to unstake token, so that I can use my tokens.

**Acceptance Criteria**:
- a thaw period should be [insert here the period]
- Account should reflect reserved amount to be reduced by unstaking amount
- Account free balance should increase by unstaking amount

**Comment by p5150j** [comment]
@enddynayn Thoughts on closing this one out as its invalidated by #817 #818 #819 and #820 now?

**Comment by wilwade** [comment]
Duplicate
