### ISSUE TITLE
[Question] Is this an improper way of using schema?

### ISSUE THREAD

**Issue by iamianM** [LibertyDSNP/frequency#174]
I'm thinking of using the schema to make querying more simple for me. My plan is to use the hash of a post as a part of the schema in order to easily grab all comments, votes, etc relating to a post? So for example, I have a post with a hash `1234` and someone makes a comment with `comment_data` equal to `abcd`, I will make a new schema `1234,comment_data` with it's data equal to `,abcd`, so just leave the first part as null since it's not needed. 
I'm just wondering if this is not how schema is intended to be used? It helps a lot with structuring a querying the data as I can easily querying all announcements related to the original as long as I keep the same structure for each schema.
I could also add identifiers such as post, comment, vote, etc beforehand to distinguish them when searching by MSA id.

**Comment by saraswatpuneet** [comment]
@wilwade  I believe we have to think about this.
This could be a very important requirement

- to Abe able to allow optional fields 
- good example be graphql schemas where ! Suggest required field.

Reason: we are accepting json schema so need some sort of flag per field

**Comment by wilwade** [comment]
I think all the schemas we are planning to support at launch all support optional fields.

## Avro
- Avro schemas use a "default" system to support optional. First, set the type to be a union type between null and your desired non-null type eg: `type: ["null", "string"]` and then set the default: `default: null`.
- Some examples: http://bytepadding.com/big-data/spark/avro/define-avro-schema-with-default-values/
- Documentation: https://avro.apache.org/docs/current/spec.html#schema_complex

## Parquet
We are working on also allowing for off-chain Parquet references. (DSNP uses this for large quantities of data).

Parquet supports optional through setting the repetition type which is part of the [nested encoding](https://parquet.apache.org/docs/file-format/nestedencoding/).

If you are using [ParquetJS](https://github.com/LibertyDSNP/parquetjs/), then just set `optional: true` in the `ParquetSchema` for a field and it will take care of it. (Other parquet libraries work the same way).
