### ISSUE TITLE
Prepaid (free) transactions should still increment the nonce for accounts that have an Account

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#1766]
Note: This is not a security issue. This is about expectations.

Correct: Given a tokenless account, executing one of the free transactions does not change the nonce from 0 to 1 because there is no nonce storage.

Strange: Given an account with tokens, executing one of the free transactions does not change the nonce, even with nonce storage.

This second case is unexpected. When sending a transaction on an account with the existential deposit, the nonce incrementing is expected, while if you have an account that gets reaped, then the nonce is expected to remain at 0.

Action:
- [ ] Update the `check_nonce.rs` file to use the `AccountInfo` information in addition to `info.pays_fee` to see if we will increment the nonce. Options/Ideas:
    - `nonce.is_zero()`?
    - Something using `AccountData`?
    - `account.providers > 0`?
- [ ] Update the e2e tests that call free transactions and remove the `'current'` flag on the signAndSend so that they increment the autononce system.

Relevant Rust Code:
```rust
if info.pays_fee == Pays::Yes {
    frame_system::Account::<T>::insert(who, account);
}
```

**Comment by aramikm** [comment]
@allanperlee Since I can not assign it to you based on Github restrictions, I'm assigning this to myself so nobody else takes it.

**Comment by allanperlee** [comment]
@aramikm I'm nearly finished with both issues, but I'm still encountering the same compilation issues, even after removing & installing rustup. What else can I troubleshoot for Ubuntu building?

**Comment by aramikm** [comment]
I would suggest to open a draft PR so we can verify if it's your local setup or something with the code.
