### ISSUE TITLE
Parachain didn't produce blocks

### ISSUE THREAD

**Issue by shanithkk** [LibertyDSNP/frequency#1801]
## Discription
after running the parachain locally, parachain didn't create any new blocks.

### Steps to reproduce
1. make start-relay
2. make register
3. make start-frequency
4.  make onboard

Expected Outcome:
parachain produce new blocks

Screenshot
<img width="1512" alt="Screenshot 2023-12-05 at 1 40 41 AM" src="https://github.com/LibertyDSNP/frequency/assets/59169878/0af8b72e-00c8-4a6a-854b-db5450c8ba2a">

**Comment by mattheworris** [comment]
@shanithkk Thanks for taking the time to write an issue. 

The `rococo-local.json` file is out of date. A fix to update the json file will be coming shortly.

In the meantime, you can update it locally by running `make specs-rococo-local`. 

Be sure to clear your chain databases before restarting your network (`rm -Rf /tmp/frequency` should take care of the parachain, the relay chain containers should not have persistent storage).

**Comment by shanithkk** [comment]
Hi @mattheworris, i was build a spec using parity/polkadot:latest image, im not able to fix this issue. but using `make specs-rococo-local`  its worked. 
i ran the frequency chain by using docker getting error like `[Relaychain] Bootnode with peer id 12D3KooWDLpRT9KFo6pKdkmdQQt599tmqVYpoeiHemY32Gf4RUpp is on a different chain (our genesis: 0x0307…0458 theirs: 0xfdd2…5ec3)`

**Comment by mattheworris** [comment]
`parity/polkadot:latest` may not be compatible with earlier versions. Parity has released a few updates recently and some may contain breaking changes.

Please make sure to remove any persistent storage that may be storing the chain state when starting your nodes. `rm -Rf /tmp/frequency` will remove the storage for the parachain node started by `make start-frequency` and the `make start-relay` containers should not have any persistent storage.

Ideally, the specs should be generated with the same version of polkadot as the relay chain nodes. 
Currently, the code is slightly mismatched, but after running `make specs-rococo-local` should work without any code changes. 

However, you can make sure all the versions of polkadot are the same by editing the following files. (Again, this will be corrected in an upcoming PR).

`make specs-rococo-local` is coded to use polkadot v1.0.0. You can update the polkadot version in `scripts/generate_relay_specs`.

`make start-relay` will use polkadot v1.1.0. You can update the polkadot version in `docker/docker-compose.yml`

**Comment by mattheworris** [comment]
`make start-relay` uses docker compose to run the polkadot relay nodes in containers. It requires that your system have docker running. For example, on macOS, Docker Desktop must be running.
