### ISSUE TITLE
Investigation: How is Capacity and Provider Boosting/Rewards affected by slashing?

### ISSUE THREAD

**Issue by mattheworris** [LibertyDSNP/frequency#1837]
As a developer, I want to know that capacity and provider boosting rewards are always issued correctly and that the capacity pallet handles situations where other operations slash tokens.

- [ ] Add e2e test(s) for overlap between tokens that are slashed and simultaneously staked to the network for capacity
  - When slashed tokens affect the balance staked for capacity, the capacity pallet should adjust its internal accounting to reflect the new balance
- [ ] Add e2e test(s) for overlap between tokens that are slashed and simultaneously staked to the network for provider boosting
   - When slashed tokens affect the balance staked for provider boosting, the capacity pallet should adjust its internal accounting to reflect the new balance

**Comment by enddynayn** [comment]
duplicate ticket closing: #1819
