### ISSUE TITLE
Discussion: Protection for Users when Providers don't Transact

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#1849]
Note: This was originally discussed as part of #1793. This is my attempt to draw all the options and ideas together into one issue.

## Situation

Some actions (see list below) require the user to pass signed data to a provider that the user expects the provider to transact on their behalf. However, if the provider fails to do so, even just in the case of a mistake or bug, it may be some time before the user will know that the failure occurred and the user may not even recall who was asked to perform the action and blame an incorrect party.

### Signature Required Actions
Signing data and then passing off to a provider is required by users who are relying on provider offered capacity.

#### Problem Extrinsics
- Creating an MSA
    - User wants to know for sure they have an account
- Creating / Changing Handle
    - User wants to know this is complete and not just local to the provider
- Signature Required Stateful Storage
    - Note: Delegation is not required, as the signature from the user is a one-time delegation
    - DSNP use cases with encryption and signing key rotations
    - Some use cases may not be an issue 
- Adding an MSA Control Key
    - Critical to be complete

#### Minimal Problems
- Adding a Delegation
    - This really is the provider's desire to have the delegation permissions

### Issues with Provider Transacting
- Transparency: The action may not occur, and the user is unaware that it didn't
    - Assumption: The Provider wishes to do the action (AddProvider)
    - Reality: Provider may make mistakes

### Issues with User Transacting using Provider Capacity
- Provider needs to know how much capacity they are using and when
- Provider needs to know that they WANT to do a transaction
- Provider needs to communicate back to the user
- Replay attacks

## Communication Issues

A large advantage of the existing system is that the flow does not require any secondary interactions. The user passes off data to the provider and the provider to the chain. Done. (User here meaning the wallet+ui the user is using)

- Current: `User -> Provider -> Chain`
- Desired (but might not be possible): `Provider -> User -> Chain`

Each specific solution below should have a flow as well

## General Solution: User performs the transaction instead of the Provider

```mermaid
sequenceDiagram
    actor A as User
    participant P as Provider
    participant W as Account Creation UI / Wallet
    participant F as Frequency

    A->>P: Visit Site
    P->>W: Request Login/Signup
    W->>+F: Check for MSAs, Handles, etc...
    F-->>-W: MSAs, Handles, Delegations, etc...
    W->>A: Select Account or Create New
    Note over A,F: Create Account Flow is complex.<br/>Login only requires just the Login Auth Signature
    A->>W: Select Create New
    W->>+A: Request Forms complete (Delegation approval, Handle, etc...)
    A-->>-W: Form Data
    W->>W: Signatures: AddProvider, handle, etc...
    Note over A,W: Alternative

    opt Must this be here?
        W->>+P: Request Payment Ticket
        P-->>-W: Payment Ticket
    end
    W->>+F: Submit Transactions
    Note over A,W: Transaction Failure?<br/>Inform user of failure and allow user to act, retry, etc...
    F-->>-W: Transaction Success

    W->>W: Login Auth Signature
    W->>P: Redirect to Provider with Auth Signature
    P->>+F: Check that Delegation & User Exists
    F-->>-P: Validated
    P->>A: Logged In


    Note over A,W: Current
    W->>P: Redirect to Provider with Signatures
    P->>+F: Transact for the user
    P->>A: Logged In
    F-->>-P: Validated

    Note over A,W: The end
```

Note: Do not change the solution numbering so that they may be referred to in the comments by number + name.

### Specific Solution 1: On-Chain Vouchers

Details/Original: https://github.com/LibertyDSNP/frequency/issues/1793#issuecomment-1897885165

- Summary: Provider posts a voucher for the user to the chain. That voucher allows the user to transact using the provider's capacity for a specific action
- Flow: User -> Provider -> Chain -> User -> Chain
- Chain Storage: Yes, per voucher
- User -> Provider Communication Requirement:
    - User Control Key Address
    - User action intent
- Notes/Questions
    - The provider could spend the capacity at voucher creation time thus have more control over when capacity is spent.
    - Could voucher could be communicated to the user directly instead of to the chain?
    - Could the voucher be for a capped amount of capacity instead of a specific action?

### Specific Solution 2: Mempool Coordination

Details/Original: https://github.com/LibertyDSNP/frequency/issues/1793#issuecomment-1900611378

- Summary: The provider and user use the mempool to coordinate the transaction.
- Flow: (User -> Mempool & Provider, Provider -> Mempool) -> Chain -> User -> Provider
- Chain Storage: No
- User -> Provider Communication Requirement:
    - User Control Key Address
    - Capacity amount or some other restriction?
- Notes/Questions
    - This is only useful if the provider can send something to the user and the chain so the user can then submit without needing more interactions with the provider.

### Specific Solution 3: Provider Signature/Transaction via API

- Summary: The user calls a Provider API to specifically transact. The provider can then approve or reject the request, but the user can track the chain result.
- Flow: User -> Provider -> User -> Chain
- Chain Storage: No
- User -> Provider Communication Requirement:
    - Complete transaction
- Notes/Questions
    - Could the provider submit, and just return the transaction hash to the user?
    - How standard could the API be?

**Comment by JoeCap08055** [comment]
> ### Specific Solution 1: On-Chain Vouchers
> Details/Original: [#1793 (comment)](https://github.com/LibertyDSNP/frequency/issues/1793#issuecomment-1897885165)
> 
> * Summary: Provider posts a voucher for the user to the chain. That voucher allows the user to transact using the provider's capacity for a specific action
> * Flow: User -> Provider -> Chain -> User -> Chain
> * Chain Storage: Yes, per voucher
> * User -> Provider Communication Requirement:
>   
>   * User Control Key Address
>   * User action intent
> * Notes/Questions
>   
>   * The provider could spend the capacity at voucher creation time thus have more control over when capacity is spent.

What would happen, then, if the user never used the voucher? Though I guess since capacity is renewable, not a tremendous deal. Still...

> ### Specific Solution 3: Provider Signature/Transaction via API
> * Summary: The user calls a Provider API to specifically transact. The provider can then approve or reject the request, but the user can track the chain result.
> * Flow: User -> Provider -> User -> Chain
> * Chain Storage: No
> * User -> Provider Communication Requirement:
>   
>   * Complete transaction
> * Notes/Questions
>   
>   * Could the provider submit, and just return the transaction hash to the user?
>   * How standard could the API be?

☝🏻, I like this last point--if we were going to require the Provider to supply an API, why not just have them execute it on-chain and return the result in the API response, or provide a hash for the user to track the status. Though overall Solution # 3 seems cumbersome as it requires Providers to implement an API.

**Comment by harry-evans** [comment]
I think any / all chain state used to coordinate the user and provider needs to be limited in duration:

- In the voucher case, maybe the provider can specify a timeframe up to a hard limit, but it must have some maximum, to avoid infinite chain growth. We might also need to consider other spam related limitations, depending on when / how capacity is debited.
- In the mempool case, I think maybe capacity itself can provide a limitation. Debiting it when submitted would definitely limit the mempool growth case. If the user side can be submitted before the provider side, I would assume that would also have a pretty short duration, with the assumption being providers should generally submit at the same time or before users.
- In the provider signature case, the transaction should also be limited to some maximum number of valid blocks, like most (all?) transactions are today.

I will say the provider signature case seems the most similar to how this use case is solved by other chains. I haven't seen many solutions that used vouchers or "complex" mempool matching for cost shifting. Even the provider signature case is different than other solutions, but it is the most similar.

I like the mempool case the most, from a provider & user perspective, but I think it also might be the most complicated and unfriendly from a chain state standpoint.

**Comment by wesbiggs** [comment]
> [In the Provider Signature/Transaction via API case] How standard could the API be?

I have been looking a lot at the [UCAN](https://ucan.xyz) approach to distributed auth/delegation which is well suited for this kind of use case.

1. User generates a keypair and gives the public key to the provider.
2. Provider gives the user a UCAN document delegating the ability to create an account with that specific public key and delegation permissions, for a specified time period. (The issuer is the provider, the audience is the did:key of the user, and the JWT is signed by the provider.)
3. User signs and submits the nested UCAN to the chain (in other words, the UCAN becomes the transaction payload).

One nice side effect of this approach is that the provider knows the user's public key and can use that to poll for their MSA creation event, even if the user fails to communicate it back to the provider.

**Comment by wilwade** [comment]
Notes from Community Call 2024-03-21

- Reframing on the User Question: Has the action happened?
    - Is there an independent monitor of the completion of the action?
    - Can this be a monitoring concern instead of a transaction submission problem
    - How can a user monitor these transactions?

## Next Steps
- Continue discussions in GitHub and future community calls around user self-account monitoring sort of ideas

**Comment by wilwade** [comment]
Closing for now as not direct chain concern.
