### ISSUE TITLE
Discussion: Provider Terms of Service representation On Chain

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#1875]
For the most part, the relationship between users and providers is managed off-chain. The MSA delegation system and the signature required extrinsics provide core write based approval, but doesn't manage any part of the relationship.

[Early discussions](https://github.com/LibertyDSNP/frequency/issues/20) of the delegation system included the idea of having a hash of the terms of service in the delegation. A provider would then need to update that delegation to move a user to the new terms of service. While liked, it presented several logistical problems. For example, there was no easy way to verify that the terms displayed to the user would match the hash. In addition to the issue of updating millions of delegations when a large provider changes their terms.

@harry-evans has proposed an idea (translated ) that resolves some of these issues such that the benefits may finally tip the scales.

## Core Problem

- The terms of service that an application provides to its users is a core piece of the relationship between user and provider. The terms may be against the spirit of Frequency or a group running standards on top of Frequency such as DSNP.
- Terms of Service are generally ignored by users until issues arise.
- Application changes in terms of service are not transparent

## Potential Solution

1. Provider ToS should be part of the Provider approval process and available for review by all
2. ToS is a part of the delegation via [technical details]
3. Updates to ToS happen via [tbd process]
4. Redelegation to sign ToS changes is required

Result: ToS Acceptance is now on chain and signed by the user's wallet.

### Possible Details
- ToS via [IPFS, link, hash, content, etc...] part of the provider metadata
- Storing it is a list of ToSs so that it is possible to generate diffs
- ToS File could contain structured data with human summary and such
- Non-Provider Delegation UI could show the ToS

## Open and Related Questions
- What are the legal structures around Terms of Service, display, and approval?
    - What about terms that are different depending on jurisdiction?
    - Does it count if the terms are "displayed" and approval collected by a wallet or wallet service?
- How much should Frequency be involved with the relationship between user and provider?
- How much should Frequency be involved with dictating the terms?
- Tangent: If a provider doesn't want to do any delegations (a self-sovereign user for example), do they need approval in the same way a provider with delegations does?

## References
- EFF on Terms of Service issues: https://www.eff.org/issues/terms-of-abuse

**Comment by wesbiggs** [comment]
While it does not go nearly as far as this proposal, the Consumer Reports [Data Rights Protocol](https://datarightsprotocol.org) defines a Business Discovery Document (see the spec, [§3.05.2](https://github.com/consumer-reports-innovation-lab/data-rights-protocol?tab=readme-ov-file#3052-business-discovery-document-schema)) that provides some general metadata about a business/provider, including linking to a ToS document.

I don't think this has enough rigor in terms of immutability and change tracking for all of the potential requirements you listed, but it's possibly something to align with.

**Comment by wilwade** [comment]
Community Call Notes for 2024-02-15

- Potential Problems
    - What if a provider just doesn't use it or only updates it on their website?
    - The large cost of 600k+ delegations needing to be changed
    - This is very narrow gate to push a wide variety of needs and legal requirements through.
        - Terms based on many different criteria (location, features, etc...)
    - What are the incentives for a provider to update ToS on chain instead of just keeping it at the application layer?
    - How would/could this be enforced?
- What if...
    - Could the ToS Signatures live off chain?
    - Just including in the delegation a hash/IPFS of the ToS agreed to?
- Is this two problems?
    - How to record the provider data
    - Where to record the acceptance of the terms
- What might this enable?
    - Wallet or wallet like application could display and verify acceptance instead the application.
    - Providers don't need to push out ToS updates over email
    - Wallet could detect and remove the delegation if the user doesn't accept and/or offer alternatives
    - User opt-in required for ToS changes

**Comment by wilwade** [comment]
Community Call notes for 2024-03-21

- Summary of the prior conversations
- @harry-evans
    - Re: Goal
        - Trying to capture some of the implied external nature, the human meaning of the permissions applied
    - Re: Load
        - ToS updates could be rolled out slowly
        - In theory providers could support multiple ToS at once for slower rollouts
- Re: How would/could this be enforced?
    - Currently Providers (on Mainnet) have an approval process. An option would be that updates to terms would need to be a part of the provider approval process.

## Next Steps
- Ask @wesbiggs to bring it up with the DSNP Advisors / Community Call

**Comment by wesbiggs** [comment]
Noted re: DSNP discussion.

It might be interesting to reverse the lens through which we are considering this. If the goal is _user_ agency and control, then shouldn't the provider be signing up to the user's terms of service?

This has a couple of interesting implications. (1) The scope of the terms that need to be captured on-chain is much narrower and better defined. The user need only define the terms under which the delegation they have authorized can access and manipulate data.  A provider might have other TOS, but those are out of scope. (2) This might better represent some sign-up processes that include optional opt-in/opt-out selections ("use my data for marketing purposes", "share my data with partners").

A user-driven TOS would give users clear, immutable records of their agreed contract. Violations of this by a provider could be easily shown to be in breach of that contract. IANAL, but I would think that would be pretty solid evidence for a class action suit, for example. If a provider wants more or different privileges from a user, they will need to request that the user sign an updated delegation record.

**Comment by wilwade** [comment]
Closing as discussion completed for now
