### ISSUE TITLE
Paseo Testnet Support

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#1881]
We are adding support for the new [Paseo Testnet](https://github.com/paseo-network/)!

**Pair strongly suggested**

## Notes / Separate Issues
- Do NOT remove Rococo for now
- e2e Tests should still run against Live Rococo.
- Testnet token is `XRQCY` on all public testnets. (`UNIT` on Local Testnet)
- [Paseo Spec](https://raw.githubusercontent.com/paritytech/polkadot-sdk/master/polkadot/node/service/chain-specs/paseo.json)
    - `protocolId` = `pas`

## Checklist
- [x] Paseo chain spec
- [x] Binary builds in the Release
- [ ] Docker builds
- [x] Rename feature `frequency-rococo-testnet` to `frequency-testnet`
- [ ] Update Readme
- [ ] Generate new Spec File (Using CI) and add it
- [x] Rename "Rococo Local Testnet" -> "Local Testnet"
- [ ] Update `.env.sample`
- [ ] Update Make commands
- [x] Bootnodes
    - [ ] Coming...

**Comment by saraswatpuneet** [comment]
this is old rococo chain spec that were removed and switched to generated files, we might have to bring this back for Paseo 

https://github.com/LibertyDSNP/frequency/blob/9e4caad770bd50118167fba580fd3810ae17c33d/node/service/src/chain_spec/frequency_rococo.rs
