### ISSUE TITLE
Support Different Payload Locations: On-Chain

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#189]
As a schema creator, I want to be able to set the location type for where messages for a schema are stored, so that in the future I can create a schema with off-chain support.

## Acceptance Criteria
- [x] When creating a new Schema, I should be required to specify an allowed Payload Location of "on-chain"
- [x] When getting a Schema from RPC, I should be able to know what the Payload Location is
- [x] When creating a new message, I should be required to use the proper method given the schema's payload location

**Comment by wilwade** [comment]
Helpful to be on top of @johnmela's issue #187

**Comment by shannonwells** [comment]
Reopening until we know that all 4 tasks have been completed.
