### ISSUE TITLE
Update GitHub Workflows after new version of `ci-base-image` is published.

### ISSUE THREAD

**Issue by mattheworris** [LibertyDSNP/frequency#1891]
The GitHub workflows depend on the `nightly-2023-07-13` toolchain being installed in `ci-base-image`.

When #1890 is merged, `ci-base-image` will be updated to use `nightly` instead.

GitHub workflows may fail after the merge, as the specific version of `nightly-2023-07-13` will not be installed correctly.

- [ ] Workflows need to be updated to `nightly` to match `ci-base-image`

**Comment by wilwade** [comment]
Closed with #1896
