### ISSUE TITLE
[Developer Docs] How Frequency Handles Deletion

### ISSUE THREAD

**Issue by saraswatpuneet** [LibertyDSNP/frequency#19]
"Deletion in a Decentralized World"

Basic points:
* Forgetting is hard to do
* Deleting in a centralized world isn't real either, it just pretends. (screenshots, etc..)
* Existence is hard to erase
* Content is easy for one service to erase, but there are lots of caches
* Deletion is always a request
* Most deletions should be respected, but perhaps not all (politicians, public figures, etc...)

TODO: Add link to spec meeting docs where this discussion took place

Notes: How about a blog post on this subject

**Comment by wilwade** [comment]
Archive
