### ISSUE TITLE
Submit Capacity Transactions

### ISSUE THREAD

**Issue by enddynayn** [LibertyDSNP/frequency#195]
As a user, I want to be able to distinguish capacity vs token transactions, so that I am able to submit capacity transactions.

**Acceptance Criteria**
- I should be able to submit a capacity transaction in Polkadot UI

**Note**
- There is no fee payment involved. The intent of this story is to distinguish a capacity transaction vs a token transaction in Polkadot UI.

**Comment by enddynayn** [comment]
Some options
1. @wilwade idea: write a macro that creates capacity extrinsics from token extrinsics.
2. A proxy extrinsic that takes `<T as Config>::Call` as an argument and wraps it with capacity logic.
3. A hybrid approach of 1 and 2.

**Comment by wilwade** [comment]
Duplicate
