### ISSUE TITLE
Spike: Figure out how Schema model types of Parquet work

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#214]
We want to support Parquet as a model type #188 

How can we define a model that defines a parquet file?

## Goals

If A and B are independently creating a parquet file, using the same input values, they should each return the same byte for byte file

- Support
    - Field Definitions (any supported by Parquet)
    - Compression information
    - Statistics information
    - Bloom filter information
    - Data Page version
- Maybe Support
    - Page size
    - Other Parquet file options?

## Option 1: Just use a Parquet File

Create and upload an example or template parquet file.

### Result: Likely Reject

- Good news
    - Empty or model files can be compressed and are very small
    - File contains all the field information
    - File contains, but harder to extract all the file metadata
- Bad: Empty and append data
    - Not many Parquet libraries support an empty file
    - Not many Parquet libraries support appending data to an existing Parquet file.
- Bad: Example file with one line of bad data
    - Hard to extract all the correct data out of a file to create a new one
    - Not many readers read out the correct metadata (parquetjs for example doesn't check some things until read time)

## Option 2: Field Definitions Only

This is possible via Thrift struct or some other data structure.

Fails: Most of the goals are not met by this.

Example Thrift
```thrift
message root {
  required int32 announcementType;
  required binary contentHash;
  required int64 createdAt (INTEGER(64,false));
  required int64 fromId (INTEGER(64,false));
  required binary url (STRING);
}
```

### Option 2a: Use Avro Schema

https://github.com/apache/parquet-mr/tree/master/parquet-avro

- Parquet supports Avro.
- Not really any better than thrift or other schema format for the system

## Option 3: New Setup

Build a new structure that supports what we want to support. [References Official Thrift Def](https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift).

Example of what it might look like:
```json
{
  "[columnName]": {
    "type": "[Type]",
    "compression": "[CompressionCodec]",
    "statistics": "[boolean]",
    "bloomFilter": "[boolean]",
    "optional": "[boolean]",
    "repeated": "[boolean for if this is LIST<T> instead of T]",
    "fields": "[optional recursion for MAP type]"
  }
}
```

We don't need to support LIST or MAP which could make it simpler for Parquet Model Type v1

**Comment by saraswatpuneet** [comment]
@wilwade  @dopatraman 
While I  believe Option 3 is definitely our best bet, however while we can say that frequency per se has a parquet model which is say V1 and we can have upgrades to V2, V3 etc pretty much like XCM. However few questions we should be thinking about

- **Extensibility** : We definitely dont want to create a frequencty type model which will be hard to upgrade. However this can be coded right into code/wasm which @dopatraman  showed in draft PR.
-
- **Custom Parquet**: We definitely cannot predict the evolution of Parquet.thrift and potential network partner's preference in parquet file, so we should consider a CUSTOM mode which will come with a warning of "What could go wrong or what will be the responsibility of schema creator "

- For custom mode we can consider avro as we are defining other schemas as such

- [This definition](https://github.com/LibertyDSNP/frequency/pull/230/files#diff-a90d904f1210831d046b14ab10a080c833399ef46ab4cb69e8ab208c74265a0a) was where I was thinking we define a Parquet Schema we support in genesis like Schema0 (conceptually) that way upgrades or extensibility will get easier along with governance this will also be useful to provide any curious one to get what Parquet format Frequency support right from the chain itself

**Comment by saraswatpuneet** [comment]
We should bake in version from start 

Like 

Parquet model be like 

{
 version:
model: Vec<u8>
} 
Kind of semantic 
Where model can be serialized parquet format we support like option 3
That way as we start supporting other features of parquet as part of frequency's parquet we can do version


## Note
We might just need to have just option 3 serialized stores on chain that says this is our current, default support for parquet and find a way for others to define their custom ones 

Some renditions of sorts.
This way we can upgrade our frequency supported parquet with say sudo call or governance than hardcoding that will require wasm updates 


Happy to think further

**Comment by wilwade** [comment]
@saraswatpuneet I think we can expand `ModelType: Parquet` without versioning and if we have a breaking version, just create a new `ModelType: Parquetv2`. I think a lot we could add (Map and List support for example) without breaking older models

**Comment by wilwade** [comment]
@saraswatpuneet Re Custom

I think we could add a Custom type eventually. aka a type where the model is defined by "something" but the chain just sees it as bytes. That said it could be abused in strange ways. I think that is part of why I like @dopatraman's struct version. Abuse is extremely limited. Even more than in the Avro case.

**Comment by saraswatpuneet** [comment]
I agree with leaving potholes in form generic data types and definitely working around strongly typed constructs leaving the room for future updates upgrades or versioning breaking types clear the path 


## Smart Contracts 
I vaguely remember how easily ink! Let's you define metadata contacts and consume it and think out loud in future we could have these a smart schemas per se
https://ink.substrate.io/how-it-works/

Leaving it here for future reference
