### ISSUE TITLE
Restructure Chain Specs

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#234]
We need several different chain specs

\* Independent: aka no parachain

- [x] Local development (independent with instant sealing)
- [x] Local development (Parachain, This is what we have now)
- [x] Rococo Testnet (Parachain, temporary slot)
- [x] Mainnet (Parachain, Polkadot)
- [x] Rococo Testnet (Parachain, Long-term slot)
- [x] Readme updates

Examples of how other chains have done it:

- [Acala](https://github.com/AcalaNetwork/Acala/tree/master/node/service/src/chain_spec)
- [Moonbeam](https://github.com/PureStake/moonbeam/tree/master/node/service/src/chain_spec)
- [Litentry](https://github.com/litentry/litentry-parachain/tree/dev/node/src/chain_specs)

**Comment by saraswatpuneet** [comment]
* Related Stories 
#257 #348 #350
