### ISSUE TITLE
[Governance] Create build with minimum democracy features required

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/frequency#248]
Starting with pallet_democracy, 
Make a minimalist branch with governance enabled that will build and run.

## Acceptance criteria

- [x] pallet_democracy is added to frequency plus any pallets it depends on
- [x] pallet_collective is added
- [x] weights generated for each new frame pallet
- [x] WeightInfo that uses the new weights is defined in the frame pallet config
- [x] define the Frequency Council with one member to fulfill requirements of pallet_democracy
- [ ] define the Technical Council with one member

**Comment by wilwade** [comment]
@shannonwells does #313 close this out?
