### ISSUE TITLE
[Frequency Message Store] Message on chain should be garbage-collected after retention period

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/frequency#25]
NOTE: There is a version of this in a PR from @aramikm, but it is one possible version: https://github.com/LibertyDSNP/mrc/pull/83

As a node operator, so that I minimize my costs, I want to remove old messages from on-chain storage.

# Description
See ["Cleanup (Retention Policy)"](https://github.com/Liberty30/mrc/blob/main/designdocs/MESSAGE_STORAGE.md#cleanup-retention-policy) section of Design Doc, implement garbage collection as specified.

# Acceptance Criteria
- [ ] Implement garbage collection based on retention period
- [ ] tests for same
- [ ] Benchmarks will probably need to be updated

**Comment by wilwade** [comment]
Archive
