### ISSUE TITLE
Crowdloan Reward Distribution

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#251]
As sudo, I want to be able to distribute the crowdloan rewards to participants.

## Acceptance Criteria
- [x] Example js script that executes this action from a list of wallet addresses and token amounts
- [x] `n` percent of total free and able to be transferred
- [x] `100-n` percent should be Locked with scheduled `0.25 * (100-n)` unlocking at 24, 48, 72, and 96 weeks

## Notes
- Likely want to use the [open-web3-stack vesting pallet](https://github.com/open-web3-stack/open-runtime-module-library/tree/master/vesting) over the [vesting pallet](https://paritytech.github.io/substrate/master/pallet_vesting/index.html)

**Comment by enddynayn** [comment]
I think we want to use [open-web3-stack vesting pallet](https://github.com/open-web3-stack/open-runtime-module-library/tree/master/vesting). This implementation allows for graded vesting periods.
