### ISSUE TITLE
Keep/use cached copy of dependencies for builds

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/frequency#261]
We don't want to get into the situation that we are 100% relying on npm or cargo to serve our dependencies in the case we need to produce a build and cannot due to those failing or someone taking down a needed dependency.
We would like to get some options to solve for this. Below are some ideas, but these are not exhaustive  and we would like to explore 'unknown unknowns'  

Example: Critical dependency is taken off the Internet, we need to still be able to make a build. (might still take some work, but should be able to do it)

## Bounds
- We don't want our repo to be "massive" (git sub-repo?)
- Rust dependencies are primary, npm would be a good extra, but low priority

## Potential Solutions (might be different cargo vs npm)
- DevOps running a cargo and npm service with caches
- vender folders See: https://doc.rust-lang.org/cargo/commands/cargo-vendor.html
- ???

Time Box: 2 days

**Comment by p5150j** [comment]
close not going to do
