### ISSUE TITLE
[Config][Genesis] Genesis Config

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/frequency#263]
## Settings
- [x] Update Bootnodes for [Frequency](https://github.com/LibertyDSNP/frequency/blob/main/node/service/src/chain_spec/frequency.rs#L150)
    - [x] "/dns/0.boot.frequency.xyz/tcp/30333/p2p/12D3KooWBd4aEArNvXECtt2JHQACBdFmeafpyfre3q81iM1xCcpP"
    - [x] "/dns/1.boot.frequency.xyz/tcp/30333/p2p/12D3KooWCW8d7Yz2d3Jcb49rWcNppRNEs1K2NZitCpPtrHSQb6dw"

- [x] Initial Token Mint amount: *1 billion* (#272)
- [x] Token Decimals *Set to 8*  (Currently set to `12`) #483 
- [x] Existential Deposit: *Set to 0.01 FRQCY* (Local, Rococo, and Mainnet)
- [x] Add telemetry endpoints for [frequency spec](https://github.com/LibertyDSNP/frequency/blob/main/node/service/src/chain_spec/frequency.rs) (Mainnet should have polkadot's)
    - [x] Mainnet: wss://telemetry.polkadot.io/submit/
    - [x] Rococo: wss://telemetry.frequency.xyz/submit
- [ ] preimage (Local, Rococo, and [Mainnet](https://github.com/LibertyDSNP/frequency/blob/main/runtime/frequency/src/lib.rs#L385)
    - [x] ManagerOrigin: *TechnicalCouncil Or Root*
        - An origin that can request a preimage be placed on-chain without a deposit or fee, or manage existing preimages.
        - Note you can use [EitherOfDiverse](https://paritytech.github.io/substrate/master/frame_support/traits/struct.EitherOfDiverse.html)
    - [x] MaxSize: `4096 * 1024`
        - Max size allowed for a preimage.
    - [x] BaseDeposit: `deposit(10, 64);`
        - The base deposit for placing a preimage on chain.
        - Polkadot `deposit(2, 64);`
    - [x] ByteDeposit: `deposit(0, 1);`
        - The per-byte deposit for placing a preimage on chain.
        - Polkadot `deposit(0, 1);`
- [x] scheduler (Local, Rococo, and [Mainnet](https://github.com/LibertyDSNP/frequency/blob/main/runtime/frequency/src/lib.rs#L371)
    - [x] ScheduleOrigin: *FrequencyCouncil Or Root*
        - Required origin to schedule or cancel calls.
    - [x] MaxScheduledPerBlock = `50`
        - The maximum number of scheduled calls in the queue for a single block. 
    - [x] NoPreimagePostponement = `Some(5 * MINUTES)`
        - If `Some` then the number of blocks to postpone execution for when the item is delayed.
    - [x] MaximumWeight = `Perbill::from_percent(10) * RuntimeBlockWeights::get().max_block`
    - [x] `Preimage` Map to the preimage pallet
    - [x] `OriginPrivilegeCmp = EqualPrivilegeOnly`

### Pushed to Other Issues / Answered
- how many collators #341 
- what initial accounts and how much token for each (do not document that here) #272 
- Token Name #302 
- any other pre-defined, DSNP-related things like initial schema, MSAs, etc.
    - These will be set after chain launch
- is the foundation/treasury key multisig
    - No, but the slot key (that registers the paraId) is
- Sudo account setting: #484

Related:
- #350 
- #264 
- #270 
- #271 
- #272
- #341
- #302

**Comment by wilwade** [comment]
Closed with final piece (Existential Deposit)  with https://github.com/LibertyDSNP/frequency/pull/498
