### ISSUE TITLE
List of initial collators

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/frequency#264]
Blocked Pending Final Collator Aura and Session Keys

For launch on mainnet we'll need to create collator accounts.

- [x] Generate list of potential partners
- [x] Create Node list for Genesis
- [x] Set Mainnet aura keys for `invulnerables`

Related: #341 

- Unfinished Labs Collator 1
    - Controller: `0x40c0cf083ba1d081fce7c1f38f5344a4eba4ee5c13e1dddcb9cc6acf74559710`
    - Session: `0x7c63b545dc15066a4867f5d127b554d2bad49eab73303f550e99ea11d9ab123c`
- Unfinished Labs Collator 2
    - Controller: `0x1e5dc06d8418a0dd695bf3a23ecdc219103a149a863c1977396bf0697a474015`
    - Session: `0xa0e9a263e02d8b504808a67abbab811cb14fb376c0f79f5b7d6f7c2e7dcb585d`
- Unfinished Labs Collator 3
    - Controller: `0x7eb4de08f44e6077ed072e2fc357aac007150e3b73373434c47ec56323b52a75`
    - Session: `0x8062ffd04e84549b541668e4974f37f79f490ea846321e8a613c3406fceff565`
- OnFinality Collator 1
    - Controller: `0x3c9ea854901c1b36bd203400c90c31a69367316f7deaeeb14037f2be44bcb118`
    - Session: `0xb615416b0c34c5f3d1451a5d44390325832154ea20196b152ea5fa49346f5a30`
- External Collator `I`
    - Controller: `0x3c33f8c4c1155958d60d4d52a5181677da96052493d876b747272311b52cfe61`
    - Session: `0xbe16ebba3525a83e5f5e49cea331d5bc15c723d1dff7319b42837524b40c5970`
- External Collator `O`
    - Controller: `0x36523fba06e0f31f35dd904386a0ebe25d505ef09af4d39041afa1d994a23f5d`
    - Session: `0x8415832dcab4bcc60023222bbef2e222082ba69d53c9a870129e1c858a9ff87a`

**Comment by wilwade** [comment]
Closed by #665
