### ISSUE TITLE
[Upgrade] Establish & document change management process

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/frequency#267]
This is specifically for deciding how changes go into main. We need to make sure everyone within and outside of the Unfinished organization knows how to submit PRs and what is expected in PRs. For example, we may reject any PRs that do not have an Issue for them.  These things need to be documented.  We already have PR templates with checklists, so we should review that and make sure each type of PR (bug, enhancement, feature...) makes clear what's required in that PR.

## Notes
- Documented Some in the Wiki: https://github.com/LibertyDSNP/frequency/wiki/Frequency-Git-Workflow#change-management
- Migration changes might be different than non-migration related PRs
- How is the Hotfix flow different than normal
     - How is a client hotfix different from a release
     - Backporting
     - Limited
- Dependency changes?
- Project dependency deployment notes
- Code owners? Should we use these to help force reviews?
- Using tags for enforcing who should be reviewing code?
- Tagging runtime related issues/prs

**Comment by shannonwells** [comment]
Let's discuss specifically what deliverables we want for this story

**Comment by wilwade** [comment]
Love to see:

- General review guidelines

**Comment by p5150j** [comment]
closing per @wilwade we can revisit and add more as time permits
