### ISSUE TITLE
[Governance] Determine governance features

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/frequency#276]
We will need a list of things for "Governance v0" 
- are we just doing Sudo?
   - No. Sudo + Councils 
- If not, what democracy support are we expected to have?
  - Switching from Sudo + councils to no Sudo asap
  - Later switching to council elections
- Are we allowing a smaller number of people to "pause" the chain?
  - Basic Idea: A pallet that allows n members of the Frequency Council to throw a flag that stops any non-governmental actions
  - Answer: Moved discussion to #370 

Related: #117, #248 

- democracy config: #350 
- councils config: #347 
- treasury config: #348 
- preimage #263
- scheduler #263

**Comment by wilwade** [comment]
All questions answered or moved to other issues.
