### ISSUE TITLE
Determine collator reference hardware

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/frequency#279]
- Q: Are collators expected to use Polkadot's own reference hardware?
   A: Yes, see #354, we are going with the recommended configuration, which uses x86

- Either way it needs to be documented and then used to generate new weights
- [x] @shannonwells to run the current weights on the `c6id.2xlarge` to see what the numbers currently look like.
  - [x] Messages
  - [x] Schema
  - [x] MSA
  - [x] ORML Vesting
  - [x] Scheduler

**Comment by wilwade** [comment]
I propose we just use the Polkadot Validator requirements (most common to use across other parachains as well)

https://wiki.polkadot.network/docs/maintain-guides-how-to-validate-polkadot/#requirements

**Comment by shannonwells** [comment]
We haven't yet; I'm about to check in some weights generated on the Polkadot reference hardware for helping make that decision.

**Comment by wilwade** [comment]
Chosen Reference Hardware (Copied from Polkadot Validator Reference hardware on 2022-08-23)

    CPU
        x86-64 compatible;
        Intel Ice Lake, or newer (Xeon or Core series); AMD Zen3, or newer (EPYC or Ryzen);
        4 physical cores @ 3.4GHz;
        Simultaneous multithreading disabled (Hyper-Threading on Intel, SMT on AMD);
        Prefer single-threaded performance over higher cores count. A comparison of single-threaded performance can be found [here](https://www.cpubenchmark.net/singleThread.html).
    Storage
        An NVMe SSD of 1 TB (As it should be reasonably sized to deal with blockchain growth). An estimation of current chain snapshot sizes can be found [here](https://paranodes.io/DBSize). In general, the latency is more important than the throughput.
    Memory
        16GB DDR4 ECC.
    System
        Linux Kernel 5.16 or newer.
    Network
        The minimum symmetric networking speed is set to 500 Mbit/s (= 62.5 MB/s). This is required to support a large number of parachains and allow for proper congestion control in busy network situations.


Chosen versions on Common Cloud Platforms
- Google Cloud Platform (GCP): `c2d-highcpu-8`
-  Amazon Web Services (AWS): `c6id.2xlarge`

**Comment by aramikm** [comment]
@wilwade RocksDB tries to do sequential writes to storage. So it's optimized for HDD and not SSD. I think there are some rocksdb flags that optimizes it for SSD. Based on this it's hard to tell if we should use HDD or SSD. Maybe we can ask Parity.

**Comment by wilwade** [comment]
Parity says they have done a lot of optimization around RocksDb, so we likely shouldn't have to do any more.
