### ISSUE TITLE
[Documentation] Clean up and update README, templates & other GitHub markdown docs in the repo

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/frequency#283]
Need to review the following docs, check for content, update as needed keeping in mind the target audience and increased eyeballs on the project:

- [ ] README / #307
    - [ ] Need section (or wiki page) about how to go about updating Substrate
- [ ] PR template
   - [ ] Add item to checklist to increment spec version if needed (i.e. after run time upgrades?) 
- [ ] Issue template(s)
- [ ] Contributing guide
- [ ] Code of Conduct
- [ ] License
- [ ] Anything I forgot
- [ ] If we're lacking a document or it belongs elsewhere or something, please file a new issue for it

**Comment by rlaferla** [comment]
The Prerequisites section should have headings for Software as well as Hardware.  Under Software, there should be subsections for macOS, Linux, Windows.  For macOS, Homebrew should be listed along with the commands to install jq, etc...

**Comment by wilwade** [comment]
Archive
