### ISSUE TITLE
Update Provider Registration Design Doc

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#290]
Various Updates are needed to the Provider Design Doc to align with current thinking.

https://github.com/LibertyDSNP/frequency/blob/main/designdocs/provider_registration.md

## Known Updates
- [x] Registration Fee is Burned instead of staked
- [x] Registration Fee amount should be set by governance
- [x] Only Providers can be delegated to
- [x] Only Providers can have Capacity (This might be more part of the capacity design doc, but should be mentioned)
- [x] Providers v1 does **not** allow the Provider MSA to be retired. Move references to being able to retire a Provider MSA to the alternatives. Remove `deregister_provider`
- [x] User **does not** "stakes balance to become a provider" Instead, the user merely pays the registration fee.
- [x] It should be mentioned in the alternatives that instead of or in addition to a fee payment, that the provider could be required to post a bond.

**Note:** Also check for other updates that are needed.

**Comment by mehtaishita** [comment]
Even though a provider cannot be retired and removed from the provider registry, can a provider still request to revoke any associated delegations?
