### ISSUE TITLE
Improve readme instructions

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#296]
Following the [Readme](https://github.com/LibertyDSNP/frequency/blob/main/README.md) on a brand new laptop (M1 Pro) I ran into these issues:

### 1. Executable cannot be found
```sh
$ curl https://sh.rustup.rs -sSf | sh
$ ./scripts/init.sh install-toolchain
---
(Error complaining about rustup executable not being found)
```

This was fixed by restarting the terminal. I believe the missing step is to reinit interactive environment with something like `source ~/.profile` before running `./scripts/init.sh install-toolchain`. 💡 Need to account for most common shells, of course (zsh, fish, etc.)

### 2. Missing dependencies

Running `cargo build --release` fails on a new laptop since some deps are missing (e.g. `cmake`, `yarn`). Need to add a note about this.

### 3. Failed to start frequency node under Docker

```sh
# Docker
./scripts/init.sh start-frequency-docker
Starting frequency container with Alice...
Building collator_frequency
[+] Building 116.2s (13/18)                                                                                                                                                                                
 => [internal] load build definition from Dockerfile       
...
 => ERROR [ 8/13] RUN file ./target/release/frequency &&     ./target/release/frequency --version                                                                                                     0.4s 
------                                                                                                                                                                                                     
 > [ 8/13] RUN file ./target/release/frequency &&     ./target/release/frequency --version:                                                                                                                
#13 0.380 ./target/release/frequency: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|PIE|HAS_TLV_DESCRIPTORS>                                               
#13 0.383 /bin/sh: 1: ./target/release/frequency: Exec format error  
```

### 4. Move node table further down

Needs to be displayed after all nodes are up or at the very bottom

![Screen Shot 2022-08-03 at 3 40 14 PM](https://user-images.githubusercontent.com/4452412/182735699-d8859ba0-17f8-46ad-9711-bad0b6c1f70f.jpg)

### 5. Outdated links

The links in "Additional Resources" section appear to be obsolete.

Please let me know if you would like me to submit a PR for this. I'll update the description if I run into any more issues. 
 
### Misc

- [x] Running `source .env` after tests returns  ".env: No such file or directory" error
- [ ] Add a note about `cargo build --release` taking a long time (up to 40m)
- [x] Make it clear that running docker is a prerequisite for starting chains that rely on it
- [x] Replace `:9945` with `:9944` and update polkadot.js explorer URL to https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944#/explorer
- [ ] Add example command for streaming logs, ex. `./scripts/logs.sh alice|bob`
- [x] Need to make it clear that if running for the first time, then generating a spec file should be right before running `./scripts/init.sh start-frequency`
- [x] Step 4 in "Generating a new spec file" says commit, but there is nothing to commit since `./res/` dir is git ignored. Remove.
- [ ] Move stuff that doesn't belong in README to Wiki (e.g. glossary, local dev env diagram, etc.)
- [x] Is Local Testnet and Devnet the same thing?
- [x] Remove references to "devnet" from Readme
- [x] Document 2 ways to run the chain in local environment (see [this comment](https://github.com/LibertyDSNP/frequency/issues/296#issuecomment-1209709617))
- [x] `cargo +nightly fmt` does nothing for me, but `TARGET=lint ./ci/build.sh` seems to lint

**Comment by shannonwells** [comment]
Thanks, please go ahead & submit a PR if you're inclined.  Make sure to reference M1 Macs for context.

**Comment by wilwade** [comment]
@demisx Good catch. Those are out of date.

Those are out of date. "Generating a new spec file" is now just `./scripts/generate_specs.sh 2000 build-local`
- `2000` is the paraId 
- `build-local` could also be `build-testnet` if you are trying to build as a parachain on the real Rococo

Note there is also a Makefile so that autocomplete works if you prefer that. `make specs-local`

**Comment by saraswatpuneet** [comment]
@demisx  please sync your branch with main I have updated the location of file and also have updated the scripts

**Comment by saraswatpuneet** [comment]
@demisx  also you need to run make specs-local to generate the specs for local

**Comment by saraswatpuneet** [comment]
Also yes readme is gravely outdated now :eyes:
