### ISSUE TITLE
Add weights for substrate pallets

### ISSUE THREAD

**Issue by enddynayn** [LibertyDSNP/frequency#297]
Acceptance Criteria
- Add weights to substrate pallets
- Configure the runtime to use the new weights
- Verify that the weights are being used

Note: Weights that are included in pallets are used for testing purposes. Add the weights by running benchmarks for substrate pallets. For additional information visit [stackexchnage](https://substrate.stackexchange.com/questions/295/how-to-generate-weightinfo-for-pallets).

**Comment by wilwade** [comment]
Duplicate
