### ISSUE TITLE
Research & Test IPFS Latency

### ISSUE THREAD

**Issue by saraswatpuneet** [LibertyDSNP/frequency#303]
I have seen some claims that new pinned files on IPFS can take a while before they are generally available. (aka available via infura or cloudflare gateways) We need to see what the actually numbers are on these either from finding someone who has done it, or testing it ourselves.

## Acceptance Criteria
- [x] Statistics on time to availability of new IPFS files
- [x] Ways (if any) to speed up availability on the most common IPFS gateways (Cloudflare and Infura)
    - For example, can we notify those gateways that the file exists?

## Goal

- 95 percentile or better at 30 seconds
    - This means that the request should not fail for 95% of requests as long as that request is started at 30s since being pinned. If that request takes another 60s that is fine as long as it does not fail.

**Comment by saraswatpuneet** [comment]
https://github.com/saraswatpuneet/ipfs_latency_research

**Comment by wilwade** [comment]
May open new issues in the future for
- Pinning in larger areas
- Additional testing around IPFS gateways
