### ISSUE TITLE
[Provider Registration] Register as a Provider

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#319]
As a service, I want to be able to register my MSA as a Provider so that others can see that I am one and still be able to be delegated to once the limit is imposed (#320).

## Design Doc
- https://github.com/LibertyDSNP/frequency/blob/main/designdocs/provider_registration.md

## Acceptance Criteria
- [x] Assume that an MSA with one or more keys already exists.
- [x] I should be able to call an extrinsic on the MSA pallet that allows me to register my MSA as a provider
  - [x] I should be able to set a utf-8 name for my provider (*non-unique*)
- [x] Registration of a provider MSA must be from a key associated with the MSA
- [ ] Limit the name to 16 bytes (4-16 UTF-8 Chars)
- [x] Benchmarks and weights

## Arch Notes
- [Extrinsic definition in Design Doc](https://github.com/LibertyDSNP/frequency/blob/main/designdocs/provider_registration.md#register_providerorigin-registration_params)
- This is a token transaction
- Storage
  - key: msa_id
  - Value: ProviderMetadata { name }
- Code should be added into the msa_pallet
- Errors
  - Cannot register the same provider twice Naming should take https://github.com/LibertyDSNP/frequency/pull/308/files#r942482857 into account
  - Origin not associated to an MSA
  - Metadata Parameter out of bounds

## Related Stories
- #321 
- #322 
- #320 
- #344

**Comment by enddynayn** [comment]
can we separate adding an RPC into a different story?

**Comment by enddynayn** [comment]
is there a bound on how many providers can register?

**Comment by wilwade** [comment]
> what information about the registration should we be storing?

This is just that "name" that is mentioned in the story.

> Is there a bound on how many providers can register?

No... Well I guess it is the number of MSAs technically.
