### ISSUE TITLE
[Provider Registration] Limit delegation to Registered Providers

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#320]
As the network, we want to limit delegation to providers only, so that delegations are limited.

## Related Work
- #319 

## Acceptance Criteria
- [x] Given that I have a user and a provider, the user should be able to call `add_provider_to_msa` successfully
- [x] Given that I have a user and a provider, the provider should be able to call `create_sponsored_account_with_delegation` successfully
- [x] If I use a non-provider MSA as a provider it should be rejected
    - [x] `add_provider_to_msa`
    - [x] `create_sponsored_account_with_delegation`

## Error

- `ProviderNotRegistered`

## Design Doc
- https://github.com/LibertyDSNP/frequency/blob/main/designdocs/provider_registration.md

**Comment by rlaferla** [comment]
Proposed implementation:

Add `ProviderNotRegistered` error to `api-augment-errors.ts`, `lookup.ts` and `types-lookup.ts`
Check `ProviderRegistry` that MSA is registered using `get_provider_metadata()` function in MSA pallet.

**Comment by wilwade** [comment]
@rlaferla 

Most of the data in `js/api-augment` is generated on the fly unless you are dealing with a custom RPC, so that stuff just needs to be re-generated at the end. (#382 will remove the need to manually do that re-gen, but it is low priority currently)

> Check ProviderRegistry that MSA is registered using get_provider_metadata() function in MSA pallet for add_provider_to_msa() and create_sponsored_account_with_delegation().

This sounds correct to me.

**Comment by rlaferla** [comment]
Other unit tests will need to be updated as a result of this change as the provider must have a MSA in order to be registered.
