### ISSUE TITLE
[Security] Prevent Replay Attacks on MSA Signed Actions

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#327]
## People to reach out to
- @enddynayn has some ideas around some more structural setups to handle this
- @wilwade has a lot of the context around how to execute these replays

## Mutli PR

- [x] RPC and state (@shannonwells)
    -  [x] Refactor the storage for get_msa_keys and add a struct with the nonce and the keys (that is MSA_Id -> `{ nonce, keys }`)  (@shannonwells)
    - [x] Add a get_msa_nonce RPC call  (@shannonwells)
- [x] Secure add_provider_to_msa (proof)
- [x] Secure add_key_to_msa (Proof)
- [ ] Secure revoke_msa_key (Call) 
- [ ] Secure revoke_msa_delegation_by_delegator (Call)

## Goal

Prevent replay attacks against MSA "signed" (signed by a key on the MSA) actions that are not Token transactions
- add_provider_to_msa (proof)
- add_key_to_msa (Proof)
- Delegate Permissions Update (Future) (Proof)
- revoke_msa_key (Call) 
- revoke_msa_delegation_by_delegator (Call)

Does NOT cover `create_sponsored_account_with_delegation` that is https://github.com/LibertyDSNP/frequency/issues/349

## Current Working Solution
- Add a piece of state that is MSA_Id -> nonce
    -  Refactor the storage for get_msa_keys and add a struct with the nonce and the keys
- Require that the nonce match for the above actions
- Increment the nonce on any of the above actions
- Add `msa_nonce` to the signed payload (for proofs) or the extrinsic (for calls) of each of the above items
- Add a get_msa_nonce RPC call
- Open Question:
    - Should we add a Signed Extension that checks this nonce? No
- General Rule:
  -  This nonce should be used for MSA signatures when that signature is not connected to tokens or capacity.

## Discussion Notes

 Questions
 1. Do we need a nonce?
 2. (assuming yes) Where does the nonce live?
 3. Is it the same nonce for each of our three signed proofs?
     - How can we make sure that this solution assists with solving future
       via a generic or standard structure?

 Problems:
 1. When you sign a payload, that payload should not be able to be used again.
     - If I add someone as a service provider with a signature, that
       signature should not be able to be used to re-add them again.
     - If I sign to allow a key to be added to an MSA, that exact signature should
       not be able to be used to re-added to the MSA
 2. When you sign a payload, the service provider should have to use it within
    a given time frame.
 3. A revoked key that is compromised key should not be able to be added back
    to the MSA
 Situations:
 1. Action is taken with a key that the chain knows about (KeyInfo)
 2. Action is taken with a key that the chain does NOT know about (add/remove key)

 Potential Solutions
 1. Do nothing except the expireBlock
 2. Add a nonce to the MSA
    - Con: Harder to add several providers in a row
    - Con: Requires always fetching the data from the chain first
 3. Add (keep) a nonce on each key (KeyInfo)
    - ALSO do something around add_key replay
 4. Have a nonce on the delegation
    - Do something else around add_key replay
 5. Add a total key counter on the MSA (effectively a nonce just for key additions)
    - Do something different around delegations

## Particular Situations

 create_sponsored_account_with_delegation replay with an expire block (Provider Attack)
 1. create_sponsored_account_with_delegation
 2. add_key_to_msa
 3. delete_key_from_msa (key from Step 1)
 4. The Provider from #1 can create a NEW MSA with (key from Step 1)
 5. Transaction 1-4 all executed before Step 1 payload expireBlock

 add_key_to_msa replay with an expire block
 1. add_key_to_msa
 2. revoke_msa_key (key from Step 1)
 3. Anyone can use the payload from Step 1
 4. Transaction 1-3 all executed before Step 1 expireBlock

 revoke_msa_key replay with an expire block
 1. add_key_to_msa
 2. User calls: revoke_msa_key (key from Step 1)
 3. User re-adds key from Step 1 via add_key_to_msa
 4. Anyone can replay the transaction in Step 2
 5. Transaction 1-4 all executed before Step 2 expireBlock

 add_provider_to_msa replay with an expire block (Provider Attack)
 1. add_provider_to_msa
 2. revoke_msa_delegation_by_delegator
 3. The Provider from Step 1 can add themselves back by re-using the proof from the step 1 and `add_provider_to_msa`
 4. Transaction 1-3 all executed before Step 1 payload expireBlock

**Comment by enddynayn** [comment]
I have been thinking about why we decided to add those payloads in the first place. We did this so that we shift the cost of the transaction. What if we rethink our cost shifting strategy.
