### ISSUE TITLE
MSA Retirement should be Free

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#340]
## Related
- https://github.com/LibertyDSNP/frequency/issues/44

Should be able to follow the pattern from https://github.com/LibertyDSNP/frequency/pull/323 

As a user, I want to be able to retire my MSA, even if I have _zero_ tokens.

## Acceptance Criteria
- [x] Given that an MSA has **one** key, I should be able to retire my MSA without any tokens.

## Notes
- #44
- #205
- #229 
- https://github.com/LibertyDSNP/frequency/pull/323

**Comment by rlaferla** [comment]
Since MSA retirement does have a resource utilization cost but we are making it free for the user, how is the cost accounted for?  Do we charge the provider who created the account for the user for retirement (at the time of creation and not at the time of retirement)?

**Comment by rlaferla** [comment]
What is the weight/cost for users who call the `retire_msa()` extrinsic but are (1) not the owner and (2) the owner but they didn't first delete/remove their other accounts for the MSA first?
