### ISSUE TITLE
[Config] Democracy Config

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#350]
Note @shannon worked on the config from https://github.com/LibertyDSNP/frequency/pull/313.

## Notes
- Should use [`prod_or_fast!`](https://paritytech.github.io/polkadot/doc/polkadot_runtime_common/macro.prod_or_fast.html) with a fast version a reasonable value
- Each of these should have a comment with a description of what it is and means

## Config
- [x] `EnactmentPeriod` = `8 * DAYS`
    - The period between a proposal being approved and enacted.
    - Polkadot uses `28 * DAYS`
- [x] `LaunchPeriod` = `7 * DAYS`
    - How often (in blocks) new public referenda are launched.
    - Polkadot uses `28 * DAYS`
- [x] `VotingPeriod` = `7 * DAYS`
    - How often (in blocks) to check for new votes.
    - Polkadot uses `28 * DAYS`
- [x] `VoteLockingPeriod` = `EnactmentPeriod`
    - The minimum period of vote locking.
    - Polkadot uses `EnactmentPeriod` aka `28 * DAYS`
- [x] `MinimumDeposit` = `10 * DOLLARS`
    - The minimum amount to be used as a deposit for a public referendum proposal.
    - Polkadot uses `100 DOT`
- [x] `ExternalOrigin` = 
```
EitherOfDiverse<
		pallet_collective::EnsureProportionAtLeast<AccountId, FrequencyCouncilCollective, 1, 2>,
		frame_system::EnsureRoot<AccountId>,
	>;
```
    - Origin from which the next tabled referendum may be forced. This is a normal "super-majority-required" referendum.
    - Polkadot uses `50% of Council`
- [x] `ExternalMajorityOrigin` = 
```
EitherOfDiverse<
		pallet_collective::EnsureProportionAtLeast<AccountId, FrequencyCouncilCollective, 3, 5>,
		frame_system::EnsureRoot<AccountId>,
	>;
```
    - Origin from which the next tabled referendum may be forced; this allows for the tabling of a majority-carries referendum.
    - Polkadot uses `60% of Council`
- [x] `ExternalDefaultOrigin` = 
```
EitherOfDiverse<
		pallet_collective::EnsureProportionAtLeast<AccountId, FrequencyCouncilCollective, 1, 1>,
		frame_system::EnsureRoot<AccountId>,
	>;
```
    - Origin from which the next tabled referendum may be forced; this allows for the tabling of a negative-turnout-bias (default-carries) referendum.
    - Polkadot uses `100% of Council`
- [x] `FastTrackOrigin` = 
```
EitherOfDiverse<
		pallet_collective::EnsureProportionAtLeast<AccountId, TechnicalCouncilCollective, 2, 3>,
		frame_system::EnsureRoot<AccountId>,
	>;
```
    - Origin from which the next majority-carries (or more permissive) referendum may be tabled to vote according to the `FastTrackVotingPeriod` asynchronously in a similar manner to the emergency origin. It retains its threshold method.
    - Polkadot uses `66% of the Technical Council`
- [x] `InstantOrigin` = 
```
EitherOfDiverse<
		pallet_collective::EnsureProportionAtLeast<AccountId, TechnicalCouncilCollective, 1, 1>,
		frame_system::EnsureRoot<AccountId>,
	>;
```
    - Origin from which the next majority-carries (or more permissive) referendum may be tabled to vote immediately and asynchronously in a similar manner to the emergency origin. It retains its threshold method.
    - Polkadot uses `100% of the Technical Council`
- [x] `InstantAllowed` = `true`
    - Indicator for whether an emergency origin is even allowed to happen. Some chains may want to set this permanently to `false`, others may want to condition it on things such as an upgrade having happened recently.
    - Polkadot uses `true`
- [x] `FastTrackVotingPeriod` = `3 * HOURS`
    - Minimum voting period allowed for a fast-track referendum.
    - Polkadot uses `3 * HOURS`
- [x] `CancellationOrigin` = 
```
EitherOfDiverse<
		pallet_collective::EnsureProportionAtLeast<AccountId, FrequencyCouncilCollective, 2, 3>,
		EnsureRoot<AccountId>,
	>;
```
    - Origin from which any referendum may be cancelled in an emergency.
    - Polkadot uses ``
- [x] `BlacklistOrigin` = `EnsureRoot<AccountId>`
    - Origin from which proposals may be blacklisted.
    - Polkadot uses `EnsureRoot`
- [x] `CancelProposalOrigin` = 
```
EitherOfDiverse<
		pallet_collective::EnsureProportionAtLeast<AccountId, TechnicalCouncilCollective, 1, 1>,
		EnsureRoot<AccountId>,
	>;
```
    - Origin from which a proposal may be cancelled and its backers slashed.
    - Polkadot uses `100% of the Technical Council`
- [x] `VetoOrigin` = `pallet_collective::EnsureMember<AccountId, TechnicalCouncilCollective>;`
    - Origin for anyone able to veto proposals.
    - Polkadot uses `Any member of the Technical Council`
- [x] `CooloffPeriod` = `7 * DAYS`
    - Period in blocks where an external proposal may not be re-submitted after being vetoed.
    - Polkadot uses `7 DAYS`
- [x] `PreimageByteDeposit` = Same as pallet_preimage (See #263)
    - The amount of balance that must be deposited per byte of preimage stored.
    - Polkadot uses `0.001 DOT`
- [x] `OperationalPreimageOrigin` = `pallet_collective::EnsureMember<AccountId, FrequencyCouncilCollective>`
    - An origin that can provide a preimage using operational extrinsics.
    - Polkadot uses `Member of the Council`
- [x] `Slash` = `()` Burn it. We don't want to incentivize the council to reject
    - Handler for the unbalanced reduction when slashing a preimage deposit.
    - Polkadot uses `Treasury`
- [x] `Scheduler` = `pallet_scheduler`
    - The Scheduler.
    - Polkadot uses `pallet_scheduler`
- [x] `PalletsOrigin` = `OriginCaller`
    - Overarching type of all pallets origins.
    - Polkadot uses `OriginCaller`
- [x] `MaxVotes` = 100
    - The maximum number of votes for an account.
    - Polkadot uses `100`
- [x] `MaxProposals` = 100
    - The maximum number of public proposals that can exist at any time.
    - Polkadot uses `100`

**Comment by enddynayn** [comment]
@wilwade is this only for Rococo runtime?

**Comment by wilwade** [comment]
@enddynayn This is Rococo and Mainnet.

**Comment by wilwade** [comment]
@enddynayn With the `prod_or_fast!` for local rococo and local

**Comment by saraswatpuneet** [comment]
@wilwade  for local we keep the original values that substrate uses, and the suggested values above for Rococo and Mainnet i.e. prod in prod_or_local_env
