### ISSUE TITLE
Idea: Emergency Pause

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#370]
Context: We are planning on launching with a basic governance and removing sudo asap. However, one of the sudo protections is to correct issues that are immediate problems.

To get around this, we can construct a system that enables an emergency pause so that the group responsible for the emergency pause has very limited power instead of full sudo power.

This emergency stop power would also eventually go away, but could provide some protections.

### Option A: Full Stop
- n members of a collective must call the emergency stop extrinsic
- Once the threshold is reached, the only transactions possible are governance transactions

### Option B: Transfer Stop
- n members of a collective must call the emergency stop extrinsic
- Once the threshold is reached, the balance pallet is blocked

### Option C: Pallet Specific Stops
- n members of a collective must call the emergency stop extrinsic with what pallets they wish to shut down (balance, msa, schemas, messages, etc...)
- Once the threshold is reached, just that pallet or pallets is blocked

## Options for Getting out of an Emergency Stop

These are not exclusive options

1. The members revoke the emergency stop, re-starting the flow of transactions
2. Governance clears the stops

### Collator Based

Each of the collators could reject transactions of certain types or from certain people before full collator decentralization, but as we expect to decentralize collators quickly, it might be more difficult to setup and providing a system that allows collators to easily block some transactions is likely to have abuse.

### Governance Changes

In situations that are not super time urgent, existing governance systems are enough. We could also alter the time for proposals from the technical council to allow for faster responses. Usually  That said, it is then open for a different form of potential abuse.

See https://github.com/LibertyDSNP/frequency/issues/350 for what configuration options are already available.

### Nothing

Governance is already enough to stop or correct any issues that arise.

**Comment by saraswatpuneet** [comment]
Some parachains does this
https://github.com/parallel-finance/parallel/blob/master/pallets/emergency-shutdown/src/lib.rs

Though Governance can also pitch in, unless we need a switch for dire situations

**Comment by wilwade** [comment]
We do not need this for launch.
