### ISSUE TITLE
Document Frequency Project directory structure

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#374]
Document the purpose of main directories and files, so it's easier for developers to understand what code goes where, thus keeping the structure cleaner and easier to maintain. 

I will capture the structure in the Wiki section first https://github.com/LibertyDSNP/frequency/wiki/Directory-Structure, but it can be later moved to the [Frequency documentation site](https://docs.frequency.xyz/), if more appropriate.

**Comment by wilwade** [comment]
@demisx It likely needs to mention the [Polkadot JS API library](https://www.npmjs.com/package/@polkadot/api) as it doesn't really do anything without that.

**Comment by wilwade** [comment]
That works. Perhaps a link to the [Readme](https://github.com/LibertyDSNP/frequency/tree/main/js/api-augment#readme) as well?
