### ISSUE TITLE
Move @dsnp/frequency-api-augment to @frequency-chain/api-augment

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#389]
## Acceptance Criteria/ Tasks
- [x] Update the deployment of `@dsnp/frequency-api-augment` to `@frequency-chain/api-augment`
    - [x] `@next`
    - [x] `@latest`
    - May require @wilwade pushing once to create the npm repo
- [x] Update example-client-frequency to use the new package
- [x] Update schemas to use the new package
- [x] Update Readme (frequency/js/api-augment/example-client)
    - [x] Documentation
    - [x] Badges
   
<img width="979" alt="image" src="https://user-images.githubusercontent.com/1135694/191866752-a61648f6-8199-45d9-99b9-8f75ec4a65bd.png">

**Comment by saraswatpuneet** [comment]
Note: 
* Reach out to Wil to branch our and release to npm
* Another story automates #382

**Comment by rlaferla** [comment]
Just want to confirm that we are renaming this package to `frequency-chain/api-augment` and not to `@dsnp/frequency-chain/api-augment`. Correct?

**Comment by rlaferla** [comment]
Note:

By default, the **@latest** tag is used by npm to identify the current version of a package, and `npm install` (without any @ or @ specifier) installs the latest tag. Typically, projects only use the **@latest** tag for stable release versions, and use other tags for unstable versions such as prereleases.

The **@next** tag is used by some projects to identify the upcoming version.

**Comment by wilwade** [comment]
Reopening for the additional updates of other packages

**Comment by rlaferla** [comment]
Which other packages?  The client example has already been updated.

**Comment by rlaferla** [comment]
Closing as example-frequency-client was updated a few days ago.

**Comment by rlaferla** [comment]
Closing as example-frequency-client was updated a few days ago.
