### ISSUE TITLE
[Design Doc] Capacity and Refills

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#39]
**Notes:**
- Capacity usage and refill system
- Does NOT include anything about how to get Capacity outside of a `sudo` call for now (That is [tbd] design doc)
- Should include how to handle the balance adjustment at the block level

Early notes: https://docs.google.com/document/d/1-OKRZuoWmpuFzNcaft5nQ4VCCfsWofBeCIn_a3_j3rU/edit?usp=sharing

**Comment by shannonwells** [comment]
closing by request of @enddynayn
