### ISSUE TITLE
Cleanup: Remove `res` Folder

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#390]
- Move `res/rococo-local.json` to new `resources` dir
- We want to keep the generated files separate from the spec files we want to save
- Check to see if we need to update `rococo-local.json`
- Once that is done:
    - Move the needed parts of res/genesis/readme to the root readme
    - delete `res`
    - add `res` to the gitignore
    - update generate spec scripts to mkdir as needed.
- Update [Directory Structure Wiki page](https://github.com/LibertyDSNP/frequency/wiki/Directory-Structure) about folders (don't remove res, just note that it is ignored and add the new one if any)
- Open to also renaming `res` for clarity

**Comment by dopatraman** [comment]
How will we know whether we need to update `rococo-local.json`?

**Comment by wilwade** [comment]
@dopatraman I think the we do need to. You can regen the rococo-local.json by running polkadot (matching our version) with `polkadot  build-spec --chain rococo-local --disable-default-bootnode` Then test it against the current version. My guess is that there are updates.

**Comment by dopatraman** [comment]
Blocked by #429
