### ISSUE TITLE
[Design Doc] Staking for Capacity

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#40]
**Notes:**
- This is be an early version without other enhancements
* Token Accounts can stake any amount of tokens to any Message Source Account (MSA)
* Staking will give Capacity at a fixed ratio to the MSA beginning with the _next_ Capacity Epoch.
    * There is NO way to gain more Capacity in the current Capacity Epoch
* Staked tokens may NOT be transferred
* Staked tokens may NOT alter the staking target MSA without first being unstaked
* Staked tokens have several pieces of information:
    * What Account Id staked the tokens (the owner of the tokens)
    * What ratio the tokens were staked at
    * What MSA Id the tokens were staked to
    * What block number tokens were staked at
* Staking tokens costs a standard transaction fee
* Staked tokens are staked until actively unstaked
* Unstaking
    * Triggering the unstaking of tokens costs a standard transaction fee
    * Unstaking will take a number of blocks
    * Users can unstake partial amounts
    * Unstaking will always result in the SAME number of tokens as were staked (less fees)
    * Unstaking takes a set number of blocks
        * Open Possibilities:
            * Unstaking could be gradual (10% of the n blocks to unstake and you have access to 10%)
            * Unstaking could be shorter for those who have staked for longer
            * Unstaking faster could be possible for a fee
            * Unstaking takes less time when you unstake only a portion
                * Unstake only 10%, and access it in 10% of the time
    * Tokens being unstaked are locked
        * Non-transferable
        * Do not provide Capacity
    * Open Questions
        * Can I stake 100% of my holdings?
            * Aka can you stake the existential deposit?
            * Aka can unstaking fees be paid for with unstaked tokens?
        * Should we have value in being staked longer?
* Open Ideas/Questions:
    * Bonus capacity for minimum lock lengths
        * No unstake possible for 2 years
    * Path for altering staking target without having to wait for unstake to complete
        * Users who just want to switch who they are staking to
    * How do staked tokens interact with voting in governance?
        * Or perhaps only staked tokens matter for governance?
        * Does the MSA get the votes or the Token Account?
    * Could staking produce a network reward?

**Comment by p5150j** [comment]
@wilwade ive linked this in the capacity Epic and I would think that 

- https://github.com/LibertyDSNP/frequency/blob/main/designdocs/capacity.md 
- https://docs.google.com/document/d/1ZOjqopTiU5vnpPywSeSJlYwyrXuDgzz4LAZV7Z9Un6Q/edit#
- https://docs.google.com/document/d/1ux9CszdE_mZ-tBcZmrDyjt5Y9zRxoJpXtD9KXnavFCw/edit#heading=h.8auc4upv27f2

Think we can close this one out?
