### ISSUE TITLE
Metadata Portal / Parity Signer

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#404]
We need to have a metadata portal so users of Parity Signer can add and update the Frequency Metadata.

## Acceptance Criteria
- Users can visit metadata.frequency.xyz and update their parity signer to new or upcoming metadata.

## Notes
- Static GitHub Pages Site
- metadata.frequency.xyz
- fork of https://github.com/paritytech/metadata-portal
- Getting metadata via cli: https://libertydsnp.github.io/frequency/frequency_cli/struct.ExportMetadataCmd.html
- https://github.com/paritytech/parity-signer/blob/master/docs/src/tutorials/Add-New-Network.md
- https://github.com/paritytech/parity-signer/issues/1099
- https://github.com/nova-wallet/metadata-portal

### Suggested Flow
- Release is cut in the frequency repo
- That release triggers an action in the metadata portal
- That action then builds and signs and deploys the updated metadata for the portal

### See Also:
#601 Add Frequency to the web3 font

**TODO:**
- [ ] Is  [Frequency CI flow diagram](https://github.com/LibertyDSNP/frequency/wiki/CI)  up-to-date?

**Comment by rlaferla** [comment]
Can we use GitHub Pages?

_**Prohibited uses**
GitHub Pages is not intended for or allowed to be used as a free web-hosting service to run your online business, e-commerce site, or any other website that is primarily directed at either facilitating commercial transactions or providing commercial software as a service (SaaS). GitHub Pages sites shouldn't be used for sensitive transactions like sending passwords or credit card numbers._

**Comment by rlaferla** [comment]
Where should we put the metadata fork?  `https://github.com/LibertyDSNP/frequency/metadata` or `https://github.com/LibertyDSNP/metadata` or other?

**Comment by rlaferla** [comment]
Once the GitHub Page is up, we need to ask DevOps to add a DNS entry for `metadata.frequency.xyz`

```
% nslookup metadata.frequency.xyz
Server:		1.1.1.1
Address:	1.1.1.1#53

** server can't find metadata.frequency.xyz: NXDOMAIN

```

**Comment by rlaferla** [comment]
https://core.tetcoin.org/docs/en/knowledgebase/runtime/metadata

**Comment by wilwade** [comment]
> Once the GitHub Page is up, we need to ask DevOps to add a DNS entry for metadata.frequency.xyz

@sbendar can do that for the repo once it is all setup on github pages.

**Comment by rlaferla** [comment]
The portal uses an icon next to each network name.  Who will decide what the name and icon will be?  The icon should be 48x36. Where is the icon hosted?  GitHub?  Is it using the one from the chain itself?

**Comment by rlaferla** [comment]
Additional tasks per 11/9 meeting:
- Wil needs to generate a key pair and give us the public key to use as the verifier for the portal.  Who will be the official holder(s) of the key pair?
- Research the name of the chain that is displayed in Parity Signer when first scanning the QR bar code.  e.g. frequency-rococo-sr-25519.  Explore changing it to just frequency-rococo
- Check w/graphic designer regarding Frequency logo (SVG) and test display of logo in Parity Signer app.
- Cleanup display of chain names in portal sidebar.
- Add Frequency favicon.ico

**Comment by rlaferla** [comment]
https://github.com/LibertyDSNP/frequency/issues/601

**Comment by rlaferla** [comment]
Additional task per 11/17 meeting w/Wil:

- Automate signing process in GitHub workflow

**Comment by rlaferla** [comment]
To automate the signing process, we will create a new CLI command and Workflow action.  It will use the data scraped from the repository and live nodes to generate the signed QR barcode images directly.

**Comment by rlaferla** [comment]
@demisx:
> Just a heads-up, I am maintaining the [Frequency CI flow diagram](https://github.com/LibertyDSNP/frequency/wiki/CI) amongst the others. Ideally, any non-trivial changes to the existing Frequency project CI should originate from this diagram, reviewed/commented, and then implemented upon consensus. This way we are all on the same page and CI is easier to maintain as the jobs keep on growing.

Absolutely.  We will keep you in the loop.  Please take a look at our documentation to see what to incorporate into the main Frequency CI flow diagram if you haven't already.  https://github.com/LibertyDSNP/metadata-portal/blob/main/docs/NOTES.md

**Comment by rlaferla** [comment]
UPDATE: A new requirement was added last week to have the workflow automatically sign the data.  This feature was non-trivial but is now working.  There is a new CLI command that generates auto-signed QR barcodes for both network specs and metadata.  Additional changes to integrate this are now underway.

**Comment by rlaferla** [comment]
PNG `zTXt` chunk holds specs/metadata source:  https://dev.exiv2.org/projects/exiv2/wiki/The_Metadata_in_PNG_files

**Comment by rlaferla** [comment]
We had considered using `subkey` to sign and create the QR bar codes but it only supports retrieving data from a live node via RPC with no support for extracting the data from a WASM in a GitHub release.

**Comment by saraswatpuneet** [comment]
@rlaferla for that our collator nodes will have to support some sort of wasm runtime, I think @wilwade mentioned about some conference talk on separation of relay node embedded in substrate node.

Because that sort of an implementation will create a crisp separation of concern between relay nodes and parachain node and subsequent parathreads 🐙

But again for now it's a limitation I understand

**Comment by rlaferla** [comment]
<img width="879" alt="image" src="https://user-images.githubusercontent.com/1135694/205374586-68a0a278-c79b-4383-93f3-f0a875b69963.png">

**Comment by rlaferla** [comment]
The _GitHub_ CI workflow will change to no longer run the updater.  Instead, it will _auto-sign_ from the node first which will create the specs and metadata barcodes then will run _auto-sign_ from _GitHub_ to create only metadata barcodes.  Finally, it will run the _collector_ to create the `data.json` file that the _React_ UI uses to display everything.

**Comment by rlaferla** [comment]
Important... With the new _autosigner_, whenever the secret phrase changes, the corresponding public key must also be updated in the `config.toml `configuration file.

**Comment by rlaferla** [comment]
Important:  We have deliberately made this process semi-automatic by requiring the user to review and commit the PR whenever new barcodes and data are updated.  This is both a way to prevent runaway automation and as a security check.
