### ISSUE TITLE
Fix local collator node start error on Apple Silicon M1/M2 (arm64)

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#432]
## To Do
- [ ] Fix make commands that use docker that need `--platform linux/amd64`
- [ ] Update docker file readmes and other docker documentation to mention ^ for easy reference

## Original Issue

Starting local collator node via docker results in the following error on M1 (see below). Works on an Intel Mac. 

```
$ make start-frequency-docker
---
Attaching to frequency
frequency  | curl: (7) Failed to connect to relay_alice port 9933: Connection refused
frequency  | failed to get id for relay_alice
frequency  | curl: (7) Failed to connect to relay_bob port 9933: Connection refused
frequency  | failed to get id for relay_bob
frequency exited with code 1
```

## Solution Notes

The fix here is one of these:
1. Set the platform in the docker command to force it to use `--platform linux/amd64`
2. arm64 images Related: #779 

Since it is not an issue to have `--platform linux/amd64` even on linux amd64, it is a straightforward fix.

**Comment by p5150j** [comment]
closing duped
