### ISSUE TITLE
As a user, I should be able to retire my MSA

### ISSUE THREAD

**Issue by enddynayn** [LibertyDSNP/frequency#44]
As a current user of Frequency, I want to be able to remove myself from Frequency so that I can remove my association with Frequency.

# Description
Users should be able retire an MSA so that it cannot be used again.

## Notes
- Garbage collection of messages will be addressed in a different story. #128
- Fee:No - this is handled by #340 
- First attempt: https://github.com/LibertyDSNP/frequency/pull/252

# Acceptance Criteria
- [x] The user should be able to call the extrinsic that retires an MSA from the polkadot js ui
- [x] If the delegator does not have a MSA yet, the extrinsic should fail with `NoKeyExists`
- [x] All delegations should be revoked when calling the RPC to get delegations by MSA
- [x] I should not be able to call this unless there is only one key reference in `MsaInfoOf` and that is the key I am using to call from.
- [x] An event should be emitted to notify about the retirement Suggested: `MSARetired(msa_id)`
- [x] The `KeyRemoved` event should be triggered for the last key
- [x] I should not be able to call this if the MSA is a registered provider
- [ ] Benchmarks
- [x] Unit tests
- [x] New transactions associated with the MSA must be rejected
  - [x] FAIL: Add new key
  - [x] FAIL: Add new delegation
  - [x] FAIL: Modify delegation permissions
  - [x] FAIL: Add Message

## State Maps for Deletion
- [x] MSA -> u8 (references) deleted `MsaInfoOf`
- [x] Key -> MSA (Only one will be left) `MessageSourceIdOf`
- [x] MSA -> Provider deleted `ProviderInfoOf` (Should have none left)

## Work that doesn't need to be done
- `ProviderInfoOf` should already be emptied
- No new errors, as once `MessageSourceIdOf` deletion happens `NoKeyExists` should be triggered already.
- Pays::No is in #340 
- Garbage collection of messages will be addressed in a different story. #128

## Arch Notes
- Retire MSA extrinsic Signature: `retire_msa(origin: OriginFor<T>) -> DispatchResult`

## Other Notes
- Does not need DispatchResultWithPostInfo as we enforce that all the keys but one and all delegations are revoked.

**Comment by mehtaishita** [comment]
Since the current User is retiring their MSA, they still need to have at least one key active to sign the transaction. So does that mean we have to first retire the MSA, and then also revoke the key used to sign the transaction? 

What if they try to retire the MSA after they have revoked all their keys?

**Comment by mehtaishita** [comment]
Regarding: 
- [ ] get_msa_keys should return an empty list 

Is our intention to revoke keys (mark them as expired) or to completely delete them (from maps KeyInfoOf and MsaKeysOf)

**Comment by wilwade** [comment]
> Regarding:
> 
>     * [ ]  get_msa_keys should return an empty list
> 
> 
> Is our intention to revoke keys (mark them as expired) or to completely delete them (from maps KeyInfoOf and MsaKeysOf)

Good catch. It should mark them as expired. So that acceptance criteria is incorrect. It should be all keys in `get_msa_keys` should return as expired. I'll update.

**Comment by saraswatpuneet** [comment]
We should also add that while all delegation is revoke it should do the same process of removing grants on schemas, the path should remain the same as undelegation

**Comment by mehtaishita** [comment]
Pausing work to address:

  1. What happens with revoked keys - do we expire them, and also delete them. If we are deleting them, can this work be merged with the related story?
  2. Revoking keys and delegations is an unbounded transaction. How do we address the limits on resources and block size.

**Comment by rlaferla** [comment]
For the item, "_The user should be able to call the extrinsic that retires an MSA from the polkadot js ui_", there is currently no extrinsic, correct?  If so, it would look something like this.  Is there a cost to invoke it?  What should be the weight?

```
#[pallet::weight((T::WeightInfo::retireMSA(20_000), DispatchClass::Normal, Pays::No))]
		pub fn retireMSA(
			origin: OriginFor<T>,
			delegator: MessageSourceId,
		) -> DispatchResult 
	        }
```

**Comment by rlaferla** [comment]
For the task, "_I should not be able to call this unless there is only one key reference in `MsaInfoOf` and that is the key I am using to call from._", the following checks should be made:

```
		pub fn retireMSA(
			origin: OriginFor<T>,
			delegator: MessageSourceId,
		) -> DispatchResult
		   // let who = ensure_signed(origin)?;
		   // Self::ensure_msa_owner(&who, msa_id)?;
		   // Assert `get_msa_key_count(msa_id) == 1`
	        }
```

**Comment by rlaferla** [comment]
For the task, "_I should not be able to call this if the MSA is a registered provider_",

In `retireMSA`():

`				Self::is_registered_provider(msa_id),
`

**Comment by rlaferla** [comment]
For the task, "_New transactions associated with the MSA must be rejected_", checks need to be added for:

`add_key_to_msa()
`

**Comment by rlaferla** [comment]
For the task, "Unit tests":
 
```
fn test_retire_msa_success()
fn test_retire_msa_fails_if_registered_provider()
```

**Comment by rlaferla** [comment]
For "_State Maps for Deletion_",

The call to` delete_key_for_msa()` addresses MSA -> u8 (references) deleted MsaInfoOf.

**Comment by rlaferla** [comment]
For the task, "_New transactions associated with the MSA must be rejected_", what errors should each return?

**Comment by wilwade** [comment]
> For the task, "_New transactions associated with the MSA must be rejected_", what errors should each return?

The same error it would return for MSA or delegation not found.

**Comment by rlaferla** [comment]
This?

```
		/// The operation was attempted with an unknown delegation
		DelegationNotFound,
```

**Comment by wilwade** [comment]
@rlaferla That works!

**Comment by rlaferla** [comment]
@wilwade The API is using `NoKeyExists`

**Comment by rlaferla** [comment]
As for the "Add Message" check, @saraswatpuneet thinks that we don't need to check it individually as there are tests in messages that already test if you can add a message to an invalid MSA.
