### ISSUE TITLE
MSA tests should not use hard-coded numbers

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/frequency#442]
# Problem
We've been passing 1u64 and 2u64 for MSA ids directly when testing, but this could get us into trouble if there is a refactor or a behavior change, whereby somehow the MSAs created/needed are swapped and there could be one or more tests that are passing but shouldn't.

# Solution
Whenever we create MSAs in test, if we need the MSA then we should fetch it from storage and not assume the value (even if it seems like it will obviously be the value).  This will also allow us to later abstract some test helpers, to do table tests more easily, and help prevent a potential bad bug.

**Comment by allanperlee** [comment]
Hi again @shannonwells! This issue seems solvable, can I attempt this one too?

**Comment by shannonwells** [comment]
@allanperlee yes, please go ahead, sorry for the tardy response.

**Comment by allanperlee** [comment]
It's all good @shannonwells! Should I complete this in a different pull-request?
