### ISSUE TITLE
Make some test helpers for pallets (MSA mostly)

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/frequency#443]
# Problem
There is a lot of copy-paste code that could be abstracted into helper functions, particularly in the msa pallet.  We already have a good start with test_public and test_origin_signed, and create_account.  

It would make the code more readable, easier to maintain and easier for writing new tests if we could find a good abstraction for some of the keypair, account, MSA creation and any other things that are repeated in numerous (4+ ?) places.  Also see if current tests can use existing test functions.

## Details
There are several places in the Msa pallet tests where we generate two key pairs, set an account variable to the public key of one of them, and use that to call `Msa::create_account`, [like this test](https://github.com/LibertyDSNP/frequency/blob/84aa8d7593f9db87ec8d91c1c5fecd67728b121c/pallets/msa/src/tests.rs#L262). 3 of them begin with "it_throws_error".

Tests like these might be good to convert to a Table Test pattern, useful for concisely defining and running several very similar tests.  Define a test case struct with one or two setup parameters, and an expected result parameter, declare a vec with your cases in it, then iterate over each and call the same code with different parameters.   Here is a simple example (note the use of generics):
```rust
struct TestCase<T> {
	schema: Vec<u8>,
	expected: T,
}

#[test]
fn test_require_validated_schema_size_errors() {
  new_test_ext().execute_with(|| {
    let test_cases: [TestCase<Error<Test>>; 3] = [
      TestCase { schema: vec![], expected: Error::TooShortSchema },
      TestCase { schema: Vec::from("foo".as_bytes()), expected: Error::TooShortSchema },
      TestCase { 
        schema: 
      Vec::from("foo,bar,bazz,way,wayway,foo,bar,bazz,thisiswaywaywaywaytoolong".as_bytes()),
        expected: Error::TooLongSchema,
      },
    ];
    for tc in test_cases {
      let err = AnnouncementPallet::require_validated_schema(tc.schema).unwrap_err();
        assert_eq!(tc.expected, err)
    }
  })
}

```

Other tests may not be similar enough to work with a Table Test pattern, but it's possible this type of code in the tests could be encapsulated into a function by itself, depending on where any of these variables are reused:
```rust
    let (key_pair, _) = sr25519::Pair::generate();
    let (key_pair_2, _) = sr25519::Pair::generate();

    let account = key_pair.public();
    let (new_msa_id, _) = Msa::create_account(account.into(), EMPTY_FUNCTION).unwrap();

    let new_key = key_pair_2.public();
```

**Comment by allanperlee** [comment]
Hi @shannonwells, this is an interesting task. Can an outsider work this?

**Comment by shannonwells** [comment]
Please go ahead, thank you!

**Comment by allanperlee** [comment]
Can you show me an example of the repeated code?

**Comment by shannonwells** [comment]
@allanperlee yes I've updated the description, hope it helps. Please feel free to ask for more clarification.  Also if you have a better/different ideas that's great, we're looking for improved readability and more concise, reusable code in the tests.  My suggestion is to stick with the Msa pallet for now.  Thank you!

**Comment by allanperlee** [comment]
@shannonwells I just compiled the repository correctly after struggling with the dependencies. Sorry about the delay!
