### ISSUE TITLE
Modularize lib.rs

### ISSUE THREAD

**Issue by rlaferla** [LibertyDSNP/frequency#460]
**PROBLEM**:  The `lib.rs` files tend to be long and complicated.  This makes it more likely that there will be merge conflicts, slower compiles, and harder to manage/read code.

Key metrics:
```
    #LINES FILENAME
    1082 pallets/msa/src/lib.rs
    1065 runtime/frequency/src/lib.rs
    1042 runtime/frequency-rococo/src/lib.rs
```

**PROPOSAL**:  In the retro meeting, we discussed how we could break up `lib.rs` into modules.  Using a well defined pattern from other languages, we can break up the file into discrete sections (e.g. calls, config, storage) using the naming convention below.  The main `lib.rs` remains and includes all the discrete section files plus anything else that doesn't fit in a discrete module.  It will also include a comment at the top of the file describing this structure.

```
lib.rs
pallet.rs
lib_config.rs
lib_errors.rs
lib_events.rs
lib_storage.rs
```

**Comment by wilwade** [comment]
Archive
