### ISSUE TITLE
Fix compile warnings in node/cli/src/command.rs

### ISSUE THREAD

**Issue by rlaferla** [LibertyDSNP/frequency#464]
Fix warnings in `node/cli/src/command.rs`:

```
warning: unused import: `service`
 --> node/cli/src/command.rs:2:37
  |
2 | use frequency_service::{chain_spec, service};
  |                                     ^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused imports: `BenchmarkCmd`, `SUBSTRATE_REFERENCE_HARDWARE`
 --> node/cli/src/command.rs:7:30
  |
7 | use frame_benchmarking_cli::{BenchmarkCmd, SUBSTRATE_REFERENCE_HARDWARE};
  |                              ^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

**Comment by saraswatpuneet** [comment]
It's fine, we expect that when you not build with specific feature 

You should use make check and make build to build warning free

**Comment by saraswatpuneet** [comment]
This issue can be closed

**Comment by saraswatpuneet** [comment]
Running simply cargo check and cargo build will show these warnings

**Comment by aramikm** [comment]
We can refactor it in a way that all these warnings will go away. I think if we had some extra time we should do it. Having no warnings gives extra prestige to our repo even if it's merely for optics.

**Comment by saraswatpuneet** [comment]
I tried with defaults but did not work always compiled the default 

So it will be more of a stretch 

I will add to the stretch goals

**Comment by rlaferla** [comment]
https://doc.rust-lang.org/reference/conditional-compilation.html

**Comment by rlaferla** [comment]
Perhaps use [conditional compilation](https://doc.rust-lang.org/reference/conditional-compilation.html).

**Comment by saraswatpuneet** [comment]
We do conditional compilation, make file lists specific build/check steps to do conditional builds with all features as default

**Comment by rlaferla** [comment]
```
   Compiling frequency-service v0.1.0 (/Users/robertlaferla/src/unfinished/frequency/node/service)
warning: unreachable call
   --> node/cli/src/command.rs:93:2
    |
93  |       Ok(match id {
    |  _____^^_-
    | |     |
    | |     unreachable call
94  | |         #[cfg(feature = "frequency")]
95  | |         "frequency" => Box::new(chain_spec::frequency::frequency()),
96  | |         #[cfg(feature = "frequency-rococo-local")]
...   |
157 | |         },
158 | |     })
    | |_____- any code following this `match` expression is unreachable, as all arms diverge
    |
    = note: `#[warn(unreachable_code)]` on by default

warning: `frequency-cli` (lib) generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 7m 34s

```

**Comment by saraswatpuneet** [comment]
@rosalinekarr  a separate PR was waiting for that, it is fixed now

**Comment by rosalinekarr** [comment]
@rlaferla, pretty sure @saraswatpuneet meant to ping you. happy to see LibertyDSNP is still going strong! 👋

**Comment by saraswatpuneet** [comment]
😱 sorry about that @rosalinekarr  I did not check after typing first R lol

@rlaferla yes it is done 😅
