### ISSUE TITLE
[Spike] on offchain storage and query

### ISSUE THREAD

**Issue by saraswatpuneet** [LibertyDSNP/frequency#474]
Time bound research on:
* Offchain workers
* Offchain storage , query and types of storage
* Propose for story #418 

https://docs.substrate.io/fundamentals/offchain-operations/#:~:text=Offchain%20indexing%20is%20an%20optional,complements%20the%20on%2Dchain%20state.

**Comment by rlaferla** [comment]
### PROPOSAL

Create an off-chain worker in the **MSA** pallet.  This worker will be invoked automatically in a separate WASM environment to process each block in the chain to create maps for each MSA id to a list of account ids.  This process occurs as each block is finalized, it will keep track of the last block number that completed processing and store that block number in the off-chain storage.  This ensures that the maps are valid up to and including the last block processed.

```
fn offchain_worker(block_number: T::BlockNumber) {
}
```

In the worker, it is important to check if the node is a validator using `sp_io::offchain::is_validator()`, otherwise any changes to storage will not be stored.

Determine whether **local** or **persistent** storage will be used.  **Persistent** survives node restarts whereas **local** does not.  Are there security/performance tradeoffs between the two modes?  Initially, we will use **persistent** mode to prevent reprocessing.

Create a **Rust** module for handling off-chain storage that the `offchain_worker()` function will use to store and retrieve the data.

1. `last_processed_block_number`

The value is of type `BlockNumber`

2.  The maps of MSA ids to account ids.  As off-chain storage only has `StorageValueRef`, there needs to be a way to store maps.  This can be accomplished by generating a unique key that is the concatenation of a prefix plus the MSA id as follows:

```
	fn key_for_msa_id(msa_id: MessageSourceId) -> String {
		// e.g.  msa::m2a-1, msa::m2a-2, msa::m2a-5000, etc...
		return format!("msa::m2a-{}", msa_id)
	}
```

The value for the map should be a unique set of account ids.

`BTreeSet<AccountId> accountIds;`

As the **WASM** environment is deterministic and cannot use random data, traditional structures like `HashMap` cannot be used.  Instead, the implementation can use `BTreeMap` and `BTreeSet`.

`use sp_std::collections::{btree_map::BTreeMap,btree_set::BTreeSet};
`

`pub fn add_account_to_msa_id(&mut self, msa_id: MessageSourceId, acct_id: AccountId) {}
`

Lastly, a RPC endpoint needs to be created:

Create RPC `get_account_ids_for_msa_id`() which take a MSA id as input and returns an array of account ids and the last processed block number.

**Comment by wilwade** [comment]
Notes:

- I wonder if we mean archive node over validator node?
- It would be great if there were a way that this could work on full nodes, not just archive nodes (but that might need to be a future change)
- We talked some about lite nodes, but don't worry about those for now.
- Might be worth understanding off-chain indexers as well

Testing Ideas
- You can spin-up rococo local with a second node, just have to remap ports for the nodes

**Comment by rlaferla** [comment]
I am going to update the proposal to use MSACreated events.

**Comment by aramikm** [comment]
A couple of things:

1. I'm not sure you would need to run this on every block, it can be every `N` number of blocks and we can decide about N and how much lag is bad.
2. Last time I've checked `local` was not implemented and it errored out. Maybe they did it now.
3. You would need some kind of locking related key when you are running the process, since the process might kicked off more than one in the same block

**Comment by rlaferla** [comment]
@aramikm  I have updated the proposal. Indeed, this is not necessarily run on every block, it will use **persistant** storage and not **local** and locking strategy has been outlined but not detailed.

**Comment by wilwade** [comment]
@rlaferla Questions:

1. Is there a way to only have the off-chain worker run if RPCs are enabled? Or perhaps behind a flag? Be nice if the collators and those not running RPCs could skip the load.
2. Don't quite understand about the check for `sp_io::offchain::is_validator()` and how that applies to this need.
3. I assume that `delete_msa_key` would just trigger a removal?
4. Is there an order guarantee? So if in a block I were to remove a key then add it back, would that still evaluate correctly?

**Comment by rlaferla** [comment]
With regards to question 2, I did further research and found that it is not necessary.

**Comment by saraswatpuneet** [comment]
I like the fact we check if RPCs are enabled on a collator

**Comment by rlaferla** [comment]
@saraswatpuneet One solution that Parity offered was to disable the off-chain worker on nodes running the RPC interface.  While this works for this specific case, there may be other functionality that uses off-chain workers.  Do you see that as a potential problem or would we always disable off-chain workers for collators?

**Comment by rlaferla** [comment]
Updated to draft 3 to include event processing and end-to-end testing.

**Comment by rlaferla** [comment]
@wilwade 
> @rlaferla Questions:
> 3. I assume that `delete_msa_key` would just trigger a removal?
> 4. Is there an order guarantee? So if in a block I were to remove a key then add it back, would that still evaluate correctly?
When a block is processed, the events are obtained and processed one by one, triggering an action to add/remove an account for a MSA.  It is unclear (due to lack of documentation) if there is any implied ordering of those events in Substrate.  To my knowledge, events do not have a timestamp.

**Comment by rlaferla** [comment]
I updated/corrected the events section of the proposal as there are actually only two events that we're interested in.

**Comment by rlaferla** [comment]
Updated the spike proposal to draft 4 because of the major clarification on events and added a security section to present topics for discussion.

**Comment by rlaferla** [comment]
@aramikm wrote:
 >* I'm not sure you would need to run this on every block, it can be every `N` number of blocks and we can decide about N and how much lag is bad.
 
 I think it has to be run on every block in order because it needs the MSA events for each.  Unless, there is a way to access previous blocks and their events, I don't see how this would be possible.

**Comment by rlaferla** [comment]
The alternative solution is not possible given the implementation details.

**Comment by saraswatpuneet** [comment]
I believe it is fine, given it is public information, persistence type will ensure we have all the data at our collators
> Persistent off-chain storage mode will be used because it survives node restarts whereas local does not. Are there security/performance tradeoffs between the two modes? The persistent mode is used to prevent reprocessing if the node is restarted.

**Comment by saraswatpuneet** [comment]
Just need to know this key should be unique in k-v db assuming there are no collisions  or we use some protocol type convention ```msa://``` 
> 	fn key_for_msa_id(msa_id: MessageSourceId) -> String {
> 		// e.g.  msa::m2a-1, msa::m2a-2, msa::m2a-5000, etc...
> 		return format!("msa::m2a-{}", msa_id)
> 	}

**Comment by rlaferla** [comment]
Also, the `format!()` macro is `std` so we will need an alternative for `no_std`.  https://stackoverflow.com/questions/50200268/how-can-i-use-the-format-macro-in-a-no-std-environment/50200528#50200528

**Comment by aramikm** [comment]
We don't need any dependency, you can just do the following
```
let mut id: Vec<u8> = vec![];
id.extend(b"msa::m2a-");
let mut buff = [0u8; 30];
id.extend(msa_id.numtoa(10, &mut buff));
```

**Comment by shannonwells** [comment]
Q: under what conditions does the off-chain worker run? Apparently it's not "guaranteed" to be run after every block, OTOH do we care, and is it important to do the indexing work after every block (regardless of state) or only when there is state change (as in the MSA example)?

@aramikm 's comment in chat was:
> Offchain indexing can be used to set trigger condition from inside extrinsic. But you don’t need events, you can get the map from state and reverse it, keeping it updated would it tricky without events

**Comment by rlaferla** [comment]
The _timestamp_ inherent and any other extrinsics will trigger the _offchain_worker()_.

```
2022-11-13 22:49:48 debug: validate_transaction(TransactionSource::InBlock, UncheckedExtrinsic(None, Call::Timestamp(Call::set { now: 1668397788005 })), 0xa77d8940e4d29903748a3279adf85f7dcc239f5d8dcdd4b6ebcd4d6349b8bc1c)    
2022-11-13 22:49:48 debug: check(UncheckedExtrinsic(None, Call::Timestamp(Call::set { now: 1668397788005 })))    
2022-11-13 22:49:48 debug: check_weight::validate_unsigned(DispatchInfo { weight: Weight { ref_time: 158080000 }, class: DispatchClass::Mandatory, pays_fee: Pays::Yes }, 11)    
2022-11-13 22:49:48 debug: offchain_worker() 
```

**Comment by saraswatpuneet** [comment]
@rlaferla 
https://github.com/jimmychu0807/substrate-offchain-worker-demo/blob/95fbbb52dc92a67a4de3459f8ddd2c362f51cec1/pallets/example-offchain-worker/src/lib.rs#L166

Something I tried long back so it came to my mind

**Comment by aramikm** [comment]
If we are able to get events from previous blocks we don't even need to use offchain indexing. I think since it is not guaranteed that offchain worker will run on every block. we need to store when was the last time the worker ran and get all events from that `block_number + 1` until `current block` and if there are events that we are interested then apply those events to your local index.

**Comment by rlaferla** [comment]
From looking at the _Substrate_ code, the offchain worker is called on `on_block_imported()` in `OffchainWorkers`.

**Comment by p5150j** [comment]
needs an update @p5150j @aramikm

**Comment by saraswatpuneet** [comment]
good read for anyone https://substrate.recipes/off-chain-workers/indexing.html

Its worth experimenting with offchain indexing
* reading events is mostly enabled in std or benchmark env in substrate, probably its not safe and using non recommended events_no_consensus is advisable to be looked into before using it for production. Still would look in it

* Now in most docs its generally offchain indexing floating around, I think the general idea there is
   - Save data in offchain storage via storage ref, collators probably need to start with specific flags to enable persistent storage
   - Read is mostly performed in offchain workers, I haven't seen any write(io) on the worker and probably not advisable.
   - **Question:** will my weights be affected if I am simply storing in offchain storage (local or persistent), probably not that much?

> 			// Off-chain indexing allowing on-chain extrinsics to write to off-chain storage predictably
> 			// so it can be read in off-chain worker context. As off-chain indexing is called in on-chain
> 			// context, if it is agreed upon by the blockchain consensus mechanism, then it is expected
> 			// to run predicably by all nodes in the network.
> 			//
> 			// From an on-chain perspective, this is write-only and cannot be read back.
> 			//
> 			// The value is written in byte form, so we need to encode/decode it when writting/reading
> 			// a number to/from this memory space.

**Comment by saraswatpuneet** [comment]
Suggestions
* Collect the msa-key mapping in a local storage(still persistent but offchain and temp)
* Do the heavy insert from msa-Vec<keys> on offchain_worker into a persistent storage manner and continue cleanup temp  storage
* So most reverse mapping logic will go in offchain_worker while that temp storage will act like a queue , also preventing us from filtering down to events of msa pallet level and figure out if something happened or not

**Comment by saraswatpuneet** [comment]
* Need to make sure that write on offchain_work to msa: keys is locked and protected
* read is fine and onchain write to local storage should be fine too (few things I am trying)

**Comment by saraswatpuneet** [comment]
Probably events as we have one to many relationships like multiple keys added to msa in same block, so we cannot use offchain_index but it sure will be useful in private graph 

Going with 
https://substrate.stackexchange.com/questions/805/errore0599-no-function-or-associated-item-named-events-found-for-struct-fr/807#807

**Comment by aramikm** [comment]
>   * Read is mostly performed in offchain workers, I haven't seen any write(io) on the worker and probably not advisable.

I'm not sure about above sentence, it seems like writing on offchain DB from worker should be fine, am I missing something?

>   * **Question:** will my weights be affected if I am simply storing in offchain storage (local or persistent), probably not that much?

I think it should be really fast since this write is just on the node itself and it should not be on merkle tree.

**Comment by aramikm** [comment]
> * Collect the msa-key mapping in a local storage(still persistent but offchain and temp), we will make sure what key prefixes should be to find them and process them

Do you think about using offchain-indexing to store data into this temp queue or how do you think this might work?

**Comment by aramikm** [comment]
> Probably events as we have one to many relationships like multiple keys added to msa in same block, so we cannot use offchain_index but it sure will be useful in private graph
> 
> Going with https://substrate.stackexchange.com/questions/805/errore0599-no-function-or-associated-item-named-events-found-for-struct-fr/807#807

Based on comments in that page it seems like maybe using `read_events_no_consensus()` from offchain worker should be fine.

> This can be helpful for scenarios like an offchain worker reading into the events, which would be okay since this would not appear as a storage read in the [PoV for a parachain](https://substrate.stackexchange.com/questions/518/what-does-pov-stand-for/519#519).

**Comment by rlaferla** [comment]
Additional off-chain worker resources (video):

https://www.youtube.com/results?search_query=substrate+offchain+worker

**Comment by saraswatpuneet** [comment]
Keeping this here for thoughts

Now that I think about it maybe it might make sense to have a block_number level offchain lock instead of msa level lock for 3 reasons

From user perspective we only want to check to see if this reverse map is updated up to which block number for all inputs but the way we are storing the block number of storage per msa it's hard to tell that if there are more events after this block number that didn't get indexed yet.
since we are removing this storage before processing all the events, there is always that possibility that node might die and there is no trace in offchain DB to continue the process.
Having point number 2 in mind we will need to be able to process unprocessed events from previous block numbers also. Since we are not sure that the offchain worker will run on every block number and we might need to resume process for a failed one.
I don't think we might need these at this point but it's some nice to haves.

Member
Author
@[saraswatpuneet](https://github.com/saraswatpuneet) saraswatpuneet [now](https://github.com/LibertyDSNP/frequency/pull/943#discussion_r1084825067)
Getting the indexed data for a given msa, we get the block_number which is the last updated. Not sure about the overhead
Agree a little chance that node crashed before offchain_worker was called, in low transaction world it is instantaneous but i am sure there will be lags. However yes if we can reproduce that else would be worth keeping eye on though we never expect mainnet to stall
Yep we can think of some manual trigger to process missing blocks, but will keep it for laters
Awesome thanks for the amazing review, I will add some unit tests since benchmarks are fairly straightforward

**Comment by saraswatpuneet** [comment]
Branch with this implementation

https://github.com/LibertyDSNP/frequency/tree/spike/offchain_indexing

**Comment by p5150j** [comment]
resolved
