### ISSUE TITLE
Update SS58 prefix in Runtime

### ISSUE THREAD

**Issue by enddynayn** [LibertyDSNP/frequency#481]
You can use the public key to derive multiple account addresses in Substrate-based chains.
For example using `0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d` the following address one can generate multiple addresses for each chain.

Update the [runtime](https://github.com/LibertyDSNP/frequency/blob/main/runtime/frequency/src/lib.rs#L287) and set it to 90 if available after completing [issue-365](https://github.com/LibertyDSNP/frequency/issues/365). 

Note that the prefix 90 is chosen because it starts with the letter `f` and it is currently available. However, this is not finalized and is open for discussion.

References:
SS58:
https://docs.substrate.io/fundamentals/accounts-addresses-keys/

Picking a prefix:
https://substrate.stackexchange.com/questions/2311/how-to-create-custom-ss58-address-format

Address converter:
https://polkadot.js.org/apps/#/utilities

**Comment by wilwade** [comment]
Remember to only do it for mainnet

**Comment by wilwade** [comment]
Added to #365
