### ISSUE TITLE
Add PR Template

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#49]
Example from the spec repo: https://github.com/LibertyDSNP/spec/blob/main/.github/PULL_REQUEST_TEMPLATE.md

We need to add a Checklist section (example):
```markdown
# Checklist
- [ ] Chain spec updated
- [ ] Updated the js/rpc code if a custom RPC added/changed 
- [ ] Design doc(s) updated
- [ ] Tests added
- [ ] Benchmarks added
- [ ] Weights updated
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have performed a self-review of my own code
- [ ] [Others?]
```

Perhaps add a section to the top asking for related design docs?

WW: to check to see if we can make sure we have all those things checked off before merging

**Comment by aramikm** [comment]
I think the commented and self review sections should be obvious and we might not need it like this. One other thing that is crucial is checking any overflows stuff like that.
