### ISSUE TITLE
Generated Rust documentation does not display function details

### ISSUE THREAD

**Issue by rlaferla** [LibertyDSNP/frequency#503]
The `cargo-doc` generated Rust documentation does not display function details:

https://libertydsnp.github.io/frequency/pallet_msa/index.html

<img width="924" alt="image" src="https://user-images.githubusercontent.com/1135694/195422035-47f20816-7da6-417a-b190-029bb67bbb73.png">

For example, the Substrate documentation displays details for functions:

<img width="985" alt="image" src="https://user-images.githubusercontent.com/1135694/195421836-033737f3-5309-49b1-b4bd-108c60dcbf70.png">

**Comment by wilwade** [comment]
@rlaferla I think that is just our header information. It does build out the rest of the information, but you have to dig deeper: https://libertydsnp.github.io/frequency/pallet_msa/pallet/struct.Pallet.html for example

That said we should look into what we need to update about our docs, and those should link to the fuller docs at a minimum.

**Comment by rlaferla** [comment]
Indeed, it's buried under the Call and Pallet links.
