### ISSUE TITLE
External Naming Consistency Check

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#508]
We want to have consistent naming, and external naming in particular.

## Outside Naming Assistance
- https://rust-lang.github.io/api-guidelines/naming.html
- `rust fmt`

## Hard Rules
- Careful when adding code that is indexed. Should ALWAYS be the last one. Do NOT mess with prior indexes
  - Pallet Indexes
  - Events
  - Errors
  - Extrinsics
  - Argument order
-  (after this issue is closed) Changes in name or type to an external interface MUST occur in a two step process
  - 1. Create a new one and deprecate the old
  - 2. ~6 months later, remove the deprecated one. 

## Rules of Thumb
- Avoid single words
- Governance managed variables should be prefaced by `governance`
- State `StorageMap` Naming
  - [map key]To[map value]
- State `DoubleMap` Naming
  - [map key]And[map key 2]To[map value]

## General Naming Question
- `key` vs `account`?
  - Current
    - `key`: This refers to public keys that are attached to an MSA (internally as `AccountId` Type)
    - `address` The "public key" in ss58 format
    - `account`: The refers to the keypair or multisig account when holding a Balance

# State Storage
- [x] Messages `blockMessages`, `get_block_messages`
- [x] Messages `messages`, `get_messages`
- [x] Schemas `governanceSchemaModelMaxBytes`, `get_schema_model_max_bytes`
- [x] Schemas `schemas`, `get_schema`
- [x] Schemas `SchemaCount`, `schema_count`
  - `CurrentSchemaIdentifierMaximum`, `get_current_schema_identifier_maximum`
    - MUST make sure that we increment BEFORE using in a clear single function  `get_next_schema_id`
- [x] https://github.com/LibertyDSNP/frequency/pull/531 MSA `MsaIdentifier`, `get_identifier`
    - `CurrentMsaIdentifierMaximum`, `get_current_msa_identifier_maximum`
    - MUST make sure that we increment BEFORE using in a clear single function `get_next_msa_id`
    - **In Code Review**
- [x] https://github.com/LibertyDSNP/frequency/pull/532 MSA `providerRegistry`, `get_provider_metadata`
  - MSA `providerToRegistryEntry`, `get_provider_registry_entry`
    - Update Type: `ProviderMetadata`, ProviderRegistryEntry`
    - **In Code Review**
- [x] https://github.com/LibertyDSNP/frequency/pull/533 MSA `providerInfoOf`, `get_provider_info`
  - MSA `delegatorAndProviderToDelegation`, `get_delegation` Is the delegation
  - Also change Type `ProviderInfo` -> `Delegation`
    - **In Code Review**
- [x] https://github.com/LibertyDSNP/frequency/pull/534 MSA `messageSourceIdOf`, `get_msa_by_account_id`
  - MSA `publicKeyToMsaId`, `get_msa_by_public_key`
- [x] https://github.com/LibertyDSNP/frequency/pull/535 MSA `msaInfoOf`, `get_msa_key_count`
  - MSA `publicKeyCountForMsaId`, `get_public_key_count_by_msa_id`
    - **In Code Review**

## Questions/Patterns
- Name of the "getter" function
  - Should be prefixed with `get_` as it is a generated getter function
- Map Naming
  - [map key]To[map value]
  - [map value]For[map key]
- DoubleMap Naming
  - [map key]And[map key 2]To[map value]

# Constants
- [x] Messages `MaxMessagePayloadSizeBytes`
- [x] Messages `MaxMessagesPerBlock`
- [x] Schemas `MaxSchemaRegistrations`
- [x] Schemas `MinSchemaModelSizeBytes`
- [x] Schemas `SchemaModelMaxBytesBoundedVecLimit`
- [x] https://github.com/LibertyDSNP/frequency/pull/536 MSA `MaxKeys`
  - MSA `MaxPublicKeysPerMsa`
- [x] MSA `MaxProviderNameSize`
- [x] https://github.com/LibertyDSNP/frequency/pull/536 MSA `MaxSchemaGrants`
  - MSA `MaxSchemaGrantsPerDelegation`

## Questions/Patterns
- Rule of thumb? Be verbose.
- [Max/Min][Foo]Per[Bar]

# Extrinsics
- [x] Messages `add_ipfs_message`
- [x] Messages `add_onchain_message`
- [x] Schemas `register_schema`
  - Schemas `create_schema`?
- [x] Schemas `set_max_schema_model_bytes` (Gov only)
- [x] MSA `create`
- [x] MSA `create_sponsored_account_with_delegation`
- [x] MSA https://github.com/LibertyDSNP/frequency/pull/539
  - MSA `create_provider`
- [x] MSA https://github.com/LibertyDSNP/frequency/pull/540
  - MSA `grant_delegation`
- [x] MSA https://github.com/LibertyDSNP/frequency/pull/541
  - MSA `revoke_delegation_by_delegator`
- [x] MSA `revoke_delegation_by_provider`
- [x] MSA https://github.com/LibertyDSNP/frequency/pull/542
  - MSA `add_public_key_to_msa`
- [x] MSA https://github.com/LibertyDSNP/frequency/pull/543
  - MSA `delete_msa_public_key`
- [x] MSA `retire_msa`
- [x] MSA  ? `revoke_schema_permission` 
- [x] MSA  ? `grant_schema_permission`

## Questions/Patterns
- Verbs
  - `set`: Change a value to a new value
  - `add`: Append to a list of something
  - `create`: Creating something new that might have other things added to it
  - `register`: REPLACE WITH `create` Something already created that needs to be setup/augmented elsewhere
  - `grant/revoke`: Permission oriented terms
  - `delete`: Never about permissions, forget about something
  - `retire`: Not quite forget about it, but the next best thing
  - `remove`: (Used in Events) Replace with delete?
- Junctions
  -  `with`
  - `by`

# RPCs
- [x] https://github.com/LibertyDSNP/frequency/pull/551
  - `messages_getBySchemaId`
- [x] `msa_checkDelegations`
- [x] https://github.com/LibertyDSNP/frequency/pull/545
  - `msa_grantedSchemaIdsByMsaId`?
- [x] `schemas_checkSchemaValidity`
- [x] `schemas_getBySchemaId`

## Questions/Patterns
- `getBy`
- `check` vs `is` vs `has` vs `verify`
  - `is` and `has` MUST return a bool.
  - `check` returns "results"
- `get` vs `` (aka `msa_grantedSchemaIds` vs `msa_getGrantedSchemaIds`)
  - `get` -> No, `getBy` -> Yes ?

# Events

Also evaluate if we should just delete any of these events.

- [x] Messages `MessagesStored`
- [x] Schema `SchemaRegistered`
- [x] Schema `SchemaMaxSizeChanged`
  - Delete? No need to.
- [x] MSA `MsaCreated`
- [x] MSA https://github.com/LibertyDSNP/frequency/pull/546
  - `PublicKeyAdded`
- [x] MSA https://github.com/LibertyDSNP/frequency/pull/547
  - `PublicKeyDeleted`
- [x] MSA https://github.com/LibertyDSNP/frequency/pull/548
  - MSA `DelegationGranted`
- [x] MSA https://github.com/LibertyDSNP/frequency/pull/549
  - MSA `ProviderCreated`
- [x] MSA `DelegatorRevokedDelegation`
- [x] MSA `ProviderRevokedDelegation`

## Questions/Patterns
- Past tense verbs

**Comment by rlaferla** [comment]
MSA `add_key_to_msa`
MSA `delete_msa_key` -> `remove_key_from_msa`

**Comment by rlaferla** [comment]
`revoke_schema`?  Should it be `remove_schema`?  Depends on the functionality.

**Comment by rlaferla** [comment]
Should we simplify `create_sponsored_account_with_delegation` to `create_account_by_delegation`?

**Comment by rlaferla** [comment]
`messageSourceIdOf` -> `accountIdToMSAId`

**Comment by rlaferla** [comment]
`MsaInfoOf` -> `MsaIdToAccountIdCount`

**Comment by rlaferla** [comment]
The names _key_ and _account_id_ are seemingly used interchangeably in one place.  _key_ is **general** term but is not helpful in understanding what type you are dealing with.  Whereas _account_id_ is **concrete** and tells the developer that it's using an account (for use as a key.)

**Comment by rlaferla** [comment]
`get_schema` -> `get_schema_by_id`

**Comment by rlaferla** [comment]
We don't have a good term for an account without a balance.  I think it should simply be an account.  Whether it has a balance or not is a separate issue.  It's still the same thing.  It's an `AccountId` or `AccountId32` internally.  We are using the term "key" for it in places like _add_key_to_msa_.  To the user of the API, it's not explaining what the key is when we are expecting them to supply an AccountId.  `add_account_to_msa` or `add_acct_to_msa` are better possibilities.

**Comment by rlaferla** [comment]
`ProviderRegistry` -> `MsaIdToProviderMetadata`

**Comment by rlaferla** [comment]
`ProviderInfoOf` -> `MsaIdToProviderInfo`

**Comment by rlaferla** [comment]
`get_next_msa_id` and `set_msa_identifier` are not consistent.  Perhaps, `set_msa_identifier` should be `set_current_msa_id` or `set_last_msa_id`

**Comment by wilwade** [comment]
@rlaferla 
> I think `MsaKeyRemoved` and `MsaKeyDeleted` would be very confusing as it could mean that the MSA (id/key) was removed rather than the Account (id/key) for that MSA.

An MSA Id is != to an MSA key.  So I'm not sure how `MsaKey_____` can refer to an MSA Id.

**Comment by rlaferla** [comment]
@wilwade That's not what I am saying.  I understand fully that a MSA id != MSA key.  I am saying that to an outsider, they may read it as "MSA id" removed.
