### ISSUE TITLE
Switch to use Rayon for check_delegations

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#519]
Blocked By: Substrate v0.9.31/32

[`check_delegations`](https://github.com/LibertyDSNP/frequency/blob/be72f52d8fb2d84451ba5bf55224f6c07ca3b2c5/pallets/msa/src/rpc/src/lib.rs#L68-L88) uses an `iter`, but we want to use a Rayon `par_iter`, however that currently panics. It is corrected in a [Merged PR](https://github.com/paritytech/substrate/pull/12502), but it is not in a release yet.

https://substrate.stackexchange.com/questions/5329/panic-when-using-rayon-with-runtime-api-in-a-custom-rpc/5373#5373

**Comment by rlaferla** [comment]
https://github.com/paritytech/polkadot/releases/tag/v0.9.32 is now available.

**Comment by saraswatpuneet** [comment]
Worked!
