### ISSUE TITLE
[Frequency Message Store] Validate message against schema on add_message

### ISSUE THREAD

**Issue by aramikm** [LibertyDSNP/frequency#52]
Blocked #67 

As a consumer of messages on the chain, I don't want to ever read a message that doesn't work with the declared schema.

We need to validate schema when adding a message

Use [SchemaValidity struct](https://github.com/LibertyDSNP/mrc/blob/main/designdocs/SCHEMA.md#schema-primitives) to store schema validity state.

Acceptance Criteria:

- [ ] use schema pallet via loosely coupling
- [ ] validate schema in add extrinsic and reject if it fails
- [ ] modify tests
- [ ] modify benchmarks
- [ ] generate new spec

**Comment by wilwade** [comment]
Archive
