### ISSUE TITLE
Create Process for Reporting Security vulnerabilities

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#559]
Add a SECURITY.md file and a note in the README to direct people to https://github.com/LibertyDSNP/frequency/security

- Reporting security vulnerabilities in Polkadot: https://github.com/paritytech/polkadot/blob/master/SECURITY.md

**Comment by shannonwells** [comment]
another site to consider is [HackerOne](https://www.hackerone.com/)

**Comment by wilwade** [comment]
Still need a SECURITY.md and note in README, but we now have a process via: https://github.com/LibertyDSNP/frequency/security
