### ISSUE TITLE
Review use of unwrap() in non-test and non-benchmark code.

### ISSUE THREAD

**Issue by rlaferla** [LibertyDSNP/frequency#561]
The use of Rust's `unwrap() `on `Result<T,E>` and `Option<T>` will return `T` in the case of a `Ok` for `Result()` and `Some()` for `Option` but will **panic** otherwise.  A panic causes the process to abort.  This is fine for _unit tests_ and _benchmarks_ but not generally in other code.  i.e.  exceptions exist perhaps for CLI code or possibly chain specs.

Need to review these files:

```
common/helpers/src/avro.rs
pallets/messages/src/lib.rs
pallets/messages/src/types.rs
pallets/messages/src/rpc/src/lib.rs
pallets/msa/src/lib.rs
pallets/msa/src/rpc/src/lib.rs
runtime/frequency/src/lib.rs
runtime/frequency-rococo/src/lib.rs
```

**Comment by rlaferla** [comment]
For code where we don't care if it panics but may want to display a reason, we could use `expect()`

**Comment by saraswatpuneet** [comment]
We should also check if there are negative tests for this function

https://github.com/LibertyDSNP/frequency/blob/d7b80331a3d6c3db60cd27b511681ede74397f35/pallets/messages/src/types.rs#L52

Ideally we should have a story to write tests for all rpc in pallets or have 3 stories to do so 
Thoughts @wilwade ?

**Comment by shannonwells** [comment]
I'll take a look at some of the rest of these.

**Comment by aramikm** [comment]
Reopening for a minor fix
