### ISSUE TITLE
Create Network Diagrams for Rococo and Mainnet

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#576]
Per conversation with @wilwade, create both network diagrams based on the note and recording captured during the meeting.

- Draft Diagram: https://app.diagrams.net/#G1DhH7BNuOM8w3RUZaQZUTk0uqhAn-b5K5 (use different tabs)
- Recording: https://unfinished.zoom.us/rec/share/3SmTh7DBTWqD_78-bHxy0HggMj9m1f8d8NAQt78sKaaEP-0T6Wq5gYNTzID9L5ql.3Xohx2HBFczLBDM0

**Comment by wilwade** [comment]
Reviewed with DevOps. All Good.
