### ISSUE TITLE
Schema Creation Limits

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#578]
As Frequency, we don't want just anyone able to register schemas.

## Acceptance Criteria

- Only a simple majority frequency council member can approve a Schema Creation
- Local and rococo also allow anyone to do Schema Creation
- Documentation updated to reflect

## Notes

This is the same as #321 with these exceptions:
- Needs approval of a simple majority of the Frequency Council
- Does NOT matter who is asking for the schema to be created (aka no MSA needed or proof)
- Is likely somewhat longer term in solution
- More ok for users to go through the referendum process, although that is slow for protocols that have a lot of schemas.

**Comment by shannonwells** [comment]
Ideas to investigate:
* can you make proposers bond additional token or charge an extra fee even. 
* just make createSchema check ensureRoot and let the referenda system take care of the rest (insofar as approving schemas for creation) 
* Adjust passing percentages for specific extrinsics or specific types of extrinsics - putting certain types of referenda in tracks is Polkadot Governance 2.0 feature - could this be used and how?

**Comment by rlaferla** [comment]
Two new extrinsics will be added:

`request_to_create_schema()` 
- Available in all three environments, any account can request to create a schema.  A council proposal will be generated.  When approved by a simple majority of the council, the schema will be created.

`create_schema_via_governance()`
- This extrinsic will be called upon approval of a council proposal to create a schema.

The current extrinsic will be modified:

`create_schema()` 
- The origin will be `EnsureNever<AccountId>` for _mainnet_ (restricting schema creation to council governance only) and `EnsureSigned<AccountId>` for _rococo_ and _local_ (allowing any user to create a schema without the need for governance).

**Comment by rlaferla** [comment]
Which documentation exactly needs to be updated?

**Comment by rlaferla** [comment]
Blocked by #1077
