### ISSUE TITLE
 Understand Security issues of Pays::No, and pre-dispatch validation for options to enable pallet_utility

### ISSUE THREAD

**Issue by enddynayn** [LibertyDSNP/frequency#599]
Spike: Understand Security issues of Pays::No, and pre-dispatch validation for options to enable pallet_utility

**Comment by wilwade** [comment]
@enddynayn I just checked and it does cost a transaction fee to use Utility.batch even when calling a `Pays::No` extrinsic. I think that makes it safe. Unless there was a different way you were thinking about it.

## Process Followed
1. Transfer 5 UNIT to Account A.
2. Account A Balance: 5 UNIT
3. Account A: `Msa.create`
4. Account A Balance: 4.9806 UNIT
5. Account A: `Utility.batch` with `Msa.retire`
6. Account A Balance: 4.9661 UNIT <-- Cost incurred

**Comment by enddynayn** [comment]
@wilwade at the moment this spans the network and fills up the block at a very low cost.

**Comment by saraswatpuneet** [comment]
We can limit number of batch calls 
https://github.com/paritytech/substrate/blob/59da38b3a07b4ddf380ff9b01a5874fd883138a9/frame/utility/src/lib.rs#L133

**Comment by wilwade** [comment]
@saraswatpuneet Perhaps that is enough? It allows us to raise the "cost per Pays::No" used in a Utility batch call at least.

**Comment by saraswatpuneet** [comment]
Apparentely if one calls fails 

> sends a batch of calls to be dispatched and atomically execute them. If one of the calls fail, the entire transaction will rollback and fail. The number of calls must not exceed the [limit](https://docs.moonbeam.network/builders/pallets-precompiles/pallets/utility/#constants)

**Comment by p5150j** [comment]
@wilwade @enddynayn @saraswatpuneet in an effort to groom and get quality acceptance criteria 

Questions:
- What is a reasonable/expected number of calls in a batch?
- When the batch fails, what does that mean exactly what is the impact on the chain (block-size, security, performance)
- What should the cost be for the consumer calling a batch (in particular free tx)

**Comment by wilwade** [comment]
@p5150j 
> @wilwade @enddynayn @saraswatpuneet in an effort to groom and get quality acceptance criteria
> 

Hmm... Thinking about if we can deprioritize this and instead extend the call filter to block it on Rococo as well.

@enddynayn / @saraswatpuneet any reason we need to have the pallet asap? It would limit Pseudonymal dispatch, but I don't think we are using that anyway for now.

Jumping a head a bit, I think the best solution is to completely disallow any `Pays::No` transaction from batches. This is the safest course of action and resolves any potential issues around pre-dispatch check issues.

**Comment by p5150j** [comment]
changing this to a spike editing to:
Spike: Understand Security issues of Pays::No, and pre-dispatch validation for options to enable pallet_utility

**Comment by rlaferla** [comment]
> Apparently the number is hardcode by parity for some specific reason related to wasm , are we goodf with
> 
> * 1024 CALLs in a batch

The limit is actually not 1024 but much less.  The 1024 is the size of the call in bytes (1kb).  The function is doing a calculation based on that call size.  I think it's because the size could be different between native and WASM so it's trying to keep it constant.

**Comment by shannonwells** [comment]
Another idea: 
implement RuntimeCall for pallet_utility so that it excludes Pays::No txns,
Or, so that it allows only certain specific pallets/pallet txns

**Comment by saraswatpuneet** [comment]
One possible way based on Shannon's suggestion and some digging is using `UnfilteredDispatchable` and implement it for specific pallets, this can reside in common runtime, 


https://github.com/paritytech/substrate/blob/6f0f5a92739b92199b3345fc4a716211c8a8b46f/frame/support/src/traits/dispatch.rs#L291

**Comment by saraswatpuneet** [comment]
One way of doing it

* Expand base filter for utility call check and reject batches with selective `Pays::No` extrinsics from frequenyc (`msa` and `handles`)
https://github.com/LibertyDSNP/frequency/compare/main..599_utility_batch
