### ISSUE TITLE
Add Optional Schema Check to `msa_checkDelegations`

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#600]
As a consumer, I want to be able to check not just that a delegation exists, but that a specific schema id is delegated.

## Acceptance Criteria
Given: MSA A has granted 1,2,3 and MSA B has granted 3. Each to Provider X. MSA C hasn't delegated at all.
- [ ] I should be able to call the RPC `msa_checkDelegations` _with_ a schema id and it test down to the schema id (`X, [A,B,C], block, 3` -> `(A,true), (B,true), (C,false)`)
- [ ] I should be able to call the RPC `msa_checkDelegations` _without_ a schema id to test general delegation existence (`X, [A,B,C], block` -> `(A,true), (B,true), (C,false)`)

## Remember
- [x] Update the Custom RPC definition in js/api-augment
- [ ] Keep as much logic out of the runtime as possible
- [x] Block number is now required

## Updated RPC Interface
```
fn check_delegations(
  &self,
  delegator_msa_ids: Vec<MessageSourceId>,
  provider_msa_id: MessageSourceId,
  block_number:BlockNumber,
  schema_id: Option<SchemaId>,
) -> RpcResult<Vec<(MessageSourceId, bool)>>;
```

**Comment by rlaferla** [comment]
Also, the function:

```
fn ensure_valid_delegation(
		provider: Provider,
		delegator: Delegator,
		block_number: Option<Self::BlockNumber>,
	) -> Result<
		Delegation<Self::SchemaId, Self::BlockNumber, Self::MaxSchemaGrantsPerDelegation>,
		DispatchError,
	>;
```
	
	will change to:
	
```
	fn ensure_valid_delegation(
		provider: Provider,
		delegator: Delegator,
		block_number: Option<Self::BlockNumber>,
		schema_id:Option<SchemaId>,
	) -> Result<
		Delegation<Self::SchemaId, Self::BlockNumber, Self::MaxSchemaGrantsPerDelegation>,
		DispatchError,
	>;
```

**Comment by rlaferla** [comment]
After exploring various options, I think the best approach is to alter just `has_delegation()` to check for the optional schema id because it already retrieved the delegation map and checked the block number.   There is no need to modify `ensure_valid_delegation()`

**Comment by rlaferla** [comment]
How does the second acceptance criterium differ from the first?

**Comment by rlaferla** [comment]
The criteria should show that the result is actually a vector of tuples (msa id, bool)   e.g. _I should be able to call the RPC `msa_checkDelegations` with a schema id and it test down to the schema id (X, [A,B,C], block, 3) -> (A, true), (B, true), (C, false)_

**Comment by rlaferla** [comment]
The third acceptance criterium should read:   _I should be able to call the RPC msa_checkDelegations without a schema id to test general delegation existence `(X, [A,B,C], block, None) -> (A,true), (B,true), (C,false)`_ where None indicates no schema id.

**Comment by rlaferla** [comment]
`ensure_valid_schema_grant()` currently does not check for revocation and should be updated as well.

**Comment by rlaferla** [comment]
This issue depends on #627
