### ISSUE TITLE
Local Runtime Upgrade Documentation and Scripts

### ISSUE THREAD

**Issue by saraswatpuneet** [LibertyDSNP/frequency#63]
As a developer I want to be able to run a local command to update the running chain's wasm.

## Acceptance Criteria
- [x] Documentation on how to do this to the Readme
- [x] Add/update scripts to trigger the upgrade `make upgrade-forkless-local` see scripts/onboard.js for example call methods

## Help

Reach out to @enddynayn and/or @shannonwells

**Comment by enddynayn** [comment]
resources:
[docs](https://docs.substrate.io/reference/how-to-guides/parachains/runtime-upgrade/) 
[stackexchange](https://substrate.stackexchange.com/questions/1061/what-is-the-proper-way-of-executing-a-runtime-upgrade-on-a-parachain)
