### ISSUE TITLE
Benchmarks Review

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#666]
Review benchmarks for mistakes and potential issues and improve accuracy, addressing concerns related to auditing.

Related issues:

- [x] #667 
- [x] #668
- [x] #669

**Comment by rlaferla** [comment]
Is there anywhere in the code that uses anything other than _DispatchClass::Normal_ but should?   i.e.  _DispatchClass::Operational_ or _DispatchClass::Mandatory_

**Comment by rlaferla** [comment]
We could use a document (or updated document if one exists) on benchmarking guidelines based on what was found in this review.
