### ISSUE TITLE
Spike: Avro On-Chain Methods

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#67]
## Can We:
- [ ] Have a method (without std) that checks that the data matches a given schema
  - [ ] If so, what is the cost?
- [ ] Have a method that deserializes Avro binary serialized messages?
  - [ ] If so, what is the cost?

**Comment by saraswatpuneet** [comment]
-  [ ] Validation on chain: which will require a no_std helper for avro schema, check parse_str 
-  [ ] Use SchemaZero to parse the raw schema and return error if fails (loop back on this one)

TODO
- [ ] Check out https://github.com/apache/avro/tree/master/lang/rust parse_str and figure out how serde_json is used in parsing
- [ ] Extract out a validation helper to implement parse_str for avro raw schema without using std libraries.
- [ ] Write some unit tests.

**Comment by saraswatpuneet** [comment]
- [ ] canonical_form function can be extracted out into no_std helper/validator as it uses serde which have no_std support

**Comment by wilwade** [comment]
Closing as not viable for now.
