### ISSUE TITLE
Add Runtimes info to GitHub release notes

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#674]
Similar to the Polkadot one below: https://github.com/paritytech/polkadot/releases

![Screen Shot 2022-11-14 at 7 55 15 AM](https://user-images.githubusercontent.com/4452412/201710782-cb586b33-a5ba-4ebe-994e-954e7bfc5aba.jpg)

Here is the sample output of `subwasm` command. Maybe we could use it here:

```sh
subwasm info frequency_runtime-v5.v1.0.0.compact.compressed.wasm 
```

![Screenshot 2023-01-17 at 8 15 24 AM](https://user-images.githubusercontent.com/4452412/212952826-8b4e70f9-7db0-4a0b-912f-db3af1723a2c.png)

References:
- [subwasm command](https://github.com/chevdor/subwasm)

**Comment by p5150j** [comment]
@demisx might re assign to BC team, feels like a quick win the team can pick up
