### ISSUE TITLE
Benchmarks Document

### ISSUE THREAD

**Issue by aramikm** [LibertyDSNP/frequency#675]
Create a benchmark document that explains some of the context and thinking behind how to create benchmarks and some of the more advanced topics like benchmarking dynamic weights dependent on storage.

**Comment by rlaferla** [comment]
The document should cover when and how to use `DispatchResult` vs `DispatchResultWithPostInfo`.

**Comment by rlaferla** [comment]
Need to discuss using VPN/Jenkins and how to run a single benchmark, all benchmarks in pallet/project.

**Comment by rlaferla** [comment]
Notes from video:

1.  Use max values at first, run benchmark, then replace with the actual value in the` #[pallet:weight]` for the function.

**Comment by rlaferla** [comment]
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/1135694/202027188-4036ff7d-8986-47cc-a7c5-f8d71b4b58dd.png">

**Comment by rlaferla** [comment]
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/1135694/202028047-6e7cf6d6-09a1-4f5e-8804-f7e21c284f79.png">

**Comment by rlaferla** [comment]
Can we make Aramik's video public and add it to the Wiki?
