### ISSUE TITLE
Handle Deleting Delegations over Expected Max in `retire_msa`

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#678]
## Force Removal of Delegations before Retirement

**Implementation Details**

- [x] `ensure_msa_can_retire` checks for zero delegations
- [x] Add error to `ensure_msa_can_retire` for existing delegations
- [x] Update `retire_msa` to not remove delegations
- [x] Remove unused code
- [x] Update benchmarks
- [x] Update tests

- Con: Takes time to retire
- Pro: Generally not a very used function
- Pro: Simple solution (aka force the user/client to deal with it)
- Pro: No need to track delegation count
- Pro: Generally understandable error
- Pro: We already require all but one key to be removed first
- Future: Could also be a pattern for requiring the user remove user storage items first as well.

### Rejected Options

**Require the user call `retire_msa` more than once**

- Just remove n delegations each time it is called until no delegations remain
- Con: Confusing errors from `retire_msa`

**Use on_initialize / on_idle to clean up**
- Con: Complexity of tracking what needs to be cleaned up
- User Pro: Chain does the work instead of the user
- Consensus Con: Chain does the work

1. Add the resource to delete in the end of a queue from extrinsic
2. `on_initialize` will get the first item in queue and try to delete SOME_DEFINED_MAX_NUMBER from it and check if there still exists more
2.1. If not then remove the top from queue
2.2. If there are more just leave it in the queue
3. Repeat step 2 on next block

**Comment by rlaferla** [comment]
One potential solution from @aramikm is to queue the deletions so that the operation occurs across multiple blocks rather than a single block.

**Comment by enddynayn** [comment]
This is a potential solution. However, pushing this to on_initialize only opens up more attack vectors.

**Comment by rlaferla** [comment]
> Additionally, we should consider adding a counter of how many delegates a user has if we don't already.

Do you mean providers?  If we can track the # of providers, we just make this a limit but it would require using more block space.

**Comment by rlaferla** [comment]
Another possible solution is to submit an inherent to remove remaining delegations for a given delegator.  The inherent would be executed by the collator node (they are prioritized) in a subsequent block.  This would avoid using `on_initialize()`.

**Comment by rlaferla** [comment]
> 



> I believe we should let it handled at provider side by providing them necessary Lego pieces to do so I agree on_initialize or finalize is not meant for heavy lifting

How would it work?

**Comment by aramikm** [comment]
While I agree that it would be great to push this to provider side, there is no guarantee that there would be no leftover keys in storage.

**Comment by enddynayn** [comment]
What if the user who wants to delete the account makes multiple calls to delete an MSA?

**Comment by saraswatpuneet** [comment]
@enddynayn you mean keep deleting keys until all are exhausted then remove the msa ? So let multiple deletes be called till msa not found ?

**Comment by saraswatpuneet** [comment]
I see what you mean, I agree if there is a way to do without touching on_initialize would be ideal
