### ISSUE TITLE
[CI] Block the release if version of frequency tomls do not match tag

### ISSUE THREAD

**Issue by saraswatpuneet** [LibertyDSNP/frequency#686]
To prevent version mismatch between a release and binary, release CI path should make sure the [version](https://github.com/LibertyDSNP/frequency/blob/2cc01c4f3da651e079168d9e97de60f12a18bbf4/runtime/frequency/Cargo.toml#L9) of package in runtime toml and others, matches the tag

`./frequency --version` === `git tag`

**Comment by wilwade** [comment]
@demisx The `--version` will, but it gets extended with a git sha if it can. So for example for the `v0.9.29-2` tag the response from that command might look like:
```
$ ./target/production/frequency --version
frequency 0.9.29-2-1e15407cce9
```
