### ISSUE TITLE
Run benchmarks and update weights for pallet_collective once benchmarks are fixed for external pallets

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#706]
The following Benchmarks in pallet versions 0.9.29 are failing:
1. pallet_collective - A [PR is merged](https://github.com/paritytech/substrate/pull/12454), don't know what branch it will go in

We need to keep an eye out for these fixes, run the benchmarks for the pallets and then use our  weights in the relevant next frequency update.

**Comment by enddynayn** [comment]
Do we need to wait for a new release from substrate?

**Comment by rlaferla** [comment]
Benchmarking for both pallets appears to be still failing.  I am researching what (if anything) we can do about it.

`pallet_collective` (from _Substrate_)
```
2023-01-17 13:19:42 New members count (10) exceeds maximum amount of members expected (3).    
2023-01-17 13:19:42 New members count (10) exceeds maximum amount of members expected (3).    
Starting benchmark: pallet_collective::disapprove_proposal
Starting benchmark: pallet_collective::set_members
Running Benchmark: pallet_collective.set_members(3 args) 63/150 1/1
Starting benchmark: pallet_collective::execute
Starting benchmark: pallet_collective::propose_execute
Starting benchmark: pallet_collective::propose_proposed
Running Benchmark: pallet_collective.propose_proposed(3 args) 10/150 1/1
Running Benchmark: pallet_collective.propose_proposed(3 args) 126/150 1/1
Starting benchmark: pallet_collective::vote
Error: Input("`low` cannot be higher than `high`")
❌ 💔
```

`pallet_collator_selection` (from _Cumulus_)
```
2023-01-17 13:40:16 max > T::MaxCandidates; you might need to run benchmarks again    
2023-01-17 13:40:16 panicked at 'called `Result::unwrap()` on an `Err` value: <wasm:stripped>', .../cumulus-59522f43471fa161/6abd385/pallets/collator-selection/src/benchmarking.rs:103:86    
Error: Input("Error executing and verifying runtime benchmark: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\nWASM backtrace:\n\n
```

**Comment by rlaferla** [comment]
I increased the maximum number of tech committee members from 3 to 10 (same as max council members) which fixed the benchmarking.

**Comment by rlaferla** [comment]
As this issue is for the _collective_ pallet, I will not re-enable the _collator selection_ pallet benchmarks.  That can be a separate issue if desired.

**Comment by rlaferla** [comment]
The PR was missing a couple of items which should now be fixed in the next PR.
