### ISSUE TITLE
Unify versions across runtimes

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#714]
Move Runtime VERSIONS to common runtime

* [x] We would want a unified version release for both rococo/mainnet runtimes
* [x] For the same move RuntimeVersion from individual runtimes to common-runtime 
* [ ] Update PR template to including check point for version update

**Comment by saraswatpuneet** [comment]
Looks like its not straightforward. RUNTIME version is deliberately made rigid by parity

https://github.com/paritytech/substrate/blob/9428b0ea492d405f320753fcd93bc59ebb3bf33b/primitives/version/src/lib.rs#L89

Looking for alternatives

**Comment by saraswatpuneet** [comment]
We are not setting update to spec version in PR template might as well just do it one time before release avoiding more confusion for devs
