### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by NachoPal** [LibertyDSNP/frequency#734]
Links to Substrate documentation not working in:
- https://github.com/LibertyDSNP/frequency/blob/main/designdocs/MESSAGE_STORAGE.md
- https://github.com/LibertyDSNP/frequency/blob/main/designdocs/SCHEMA.md (also internal link to Message Store)

**Comment by p5150j** [comment]
validate this has been resolved

**Comment by wilwade** [comment]
Did a quick check and still found at least one 404
