### ISSUE TITLE
Potential Replay Attack: Unprevented Edge Case

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#735]
File: `pallets/msa/src/lib.rs`

Currently a signature registry is implemented to prevent replay attacks. The registry would delete all the signatures registered in a virtual bucket N using reset_virtual_bucket_if_needed(), when switching from the virtual bucket N to the next virtual bucket (i.e., the bucket N+1). Replay attack could happen if a signature is used near the end of the virtual bucket N, and the signature_expires_at falls within the bucket N+1.

## Scenario
1. Assume that MortalityWindowSize == 10, NumberOfBuckets == 10, and current_block == 9.
2. Alice signed a signature sig where signature_expires_at == 13 for Bob to transfer funds from Alice to Bob.
3. Bob successfully used sig when current_block == 9, and the chain registered sig.
4. Later when current_block == 10, the chain called reset_virtual_bucket_if_needed() and removed the previously registered sig.
5. Bob successfully used sig when current_block == 11, and the chain registered sig again.

**Comment by saraswatpuneet** [comment]
Check out bucket tests for clarity, write a scenario in the ticket

**Comment by dopatraman** [comment]
There is currently a check in place that prevents users from registering a signature that exceeds the Mortality Window Size:
```
let max_lifetime = Self::mortality_block_limit(current_block);
if max_lifetime <= signature_expires_at {
    Err(Error::<T>::ProofNotYetValid.into())
}
```

If I understand correctly, this check will protect us from this sort of replay attack.
