### ISSUE TITLE
Potential Denial of Service Through Vec<SchemaId> Parameters

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#736]
`pallets/msa/src/lib.rs`

There are many extrinsics within the MSA pallet that accept a parameter of type Vec<SchemaId>. However, the weight associated with many of these extrinsics is not linked to the length of the Vec<SchemaId>, and is rather a constant weight. Malicious users may attempt to create many transactions which use large SchemaId vectors with relatively low costs. For example, a malicious user may attempt to grant many schema permissions through a call to grant_schema_permissions() whose weight does not depend on the number of schemas, as shown below:

All the following extrinsics should potentially have weights that depend on the length of their Vec<SchemaId> parameter:
1. create_sponsored_account_with_delegation()
2. grant_delegation()
3. grant_schema_permissions()
4. revoke_schema_permissions()

**Comment by saraswatpuneet** [comment]
#720 @enddynayn
