### ISSUE TITLE
move_messages_into_final_storage() Could Disable the Function and Cause Duplication of Data

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#737]
`pallets/messages/src/lib.rs`

The code logic on L389 will stop move_messages_into_final_storage() immediately whenever bounded_vec.is_empty() == true, and this code logic will keep stopping move_messages_into_final_storage() from working normally until the data (i.e., the (schema_id, messages) pair) in BlockMessages causing bounded_vec.is_empty() == true is removed. In addition, if the schema_id of the data that is causing this problem is not the first schema_id processed by for (schema_id, messages) in map, the Messages::<T>::insert() on L391 will lead to duplication of data in Messages since there is no roll back mechanism implemented currently.

**Comment by saraswatpuneet** [comment]
https://github.com/LibertyDSNP/frequency/blob/69d9a9a1d3017b2be638dbd315617a1a77b3c091/pallets/messages/src/lib.rs#L389

**Comment by aramikm** [comment]
This was fixed in https://github.com/LibertyDSNP/frequency/pull/653/commits/f8465cd1a6fbd849df687510f6701c4758333a92
