### ISSUE TITLE
Potential Weight issue with  `message.index`

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#740]
`pallets/messages/src/lib.rs`

It is noticeable that message.index is used in add_ipfs_message()(L225) and add_onchain_message()(L285). This is not a common way of calculating costs for a node to process a request since the message.index will just keep going up regardless of the cost of the request.

Note: Please make sure this is intended by design, and alter the code if it is not.

**Comment by aramikm** [comment]
I'm not convinced that there is a particular issue with this pattern. There are examples in substrate for this such as https://github.com/paritytech/substrate/blob/master/frame/collective/src/lib.rs#L375-L382 which the weight depends on the number of old members. 

In case if we want to keep the weight as average, it is possible but it will decrease the TPS which I'm not a fan of. Other way as we discussed is custom conversion of weights to fees for certain extrinsic such as this one. 

@enddynayn An example of temporary storage pattern can be found in https://github.com/paritytech/substrate/blob/master/frame/transaction-storage/src/lib.rs.
