### ISSUE TITLE
Potential issue with `ensure_valid_delegation`

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#741]
`pallets/msa/src/lib.rs`

The `ensure_valid_delegation()` function should return an error when a valid delegation is not found for the provided parameters. However, **no error is returned if there is a delegation with no valid schema grants**. The function only checks whether a non-revoked delegation exists. However, it is unclear whether a delegation with no valid schema grants should be considered valid.

Note: This may have been fixed between `0.9.29-rc2` and `0.9.29`.

**Comment by enddynayn** [comment]
This PR addresses checking that a delegation and having a schema grant.
https://github.com/LibertyDSNP/frequency/pull/628/files
