### ISSUE TITLE
Code Documentation Fixes

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#742]
- [x] `runtime/common/src/constants.rs`: a typo in: "Generates 'an' balance based on amount of items and bytes".
- [x] `designdocs/capacity.md`: "The is no limit on the amount that you can schedule" should be "There is no limit on the amount that you can schedule" instead.
- [x] There are several functions, such as try_mutate_delegation() that take another function as a parameter. It would improve code readability if code comments were added to describe the expectations of what the function parameter should do.
- [x] Check Runtime configuration files for missing documentation (may have already been improved)

**Comment by rlaferla** [comment]
Which runtime config files is this issue referring to exactly?

**Comment by rlaferla** [comment]
@wilwade Do we want to document each storage operation as described above or not?

**Comment by wilwade** [comment]
> @wilwade Which runtime config files is this issue referring to exactly?

`runtime/frequency/src/lib.rs` would be the main file.  Some things like `pallet_treasury::Config` are well documented, but others are a bit lacking.

**Comment by wilwade** [comment]
> @wilwade Do we want to document each storage operation as described above or not?

I think it would be good to do if we can. It should be relatively straightforward right?

**Comment by rlaferla** [comment]
> > @wilwade Which runtime config files is this issue referring to exactly?
> 
> `runtime/frequency/src/lib.rs` would be the main file. Some things like `pallet_treasury::Config` are well documented, but others are a bit lacking.

So these are configurations and not configuration files?  Did Nacho elaborate on this?

**Comment by wilwade** [comment]
@rlaferla 

> So these are configurations and not configuration files? Did Nacho elaborate on this?

This was from the other review. The runtime files (at tag `v0.9.29-rc2`) covered there were:

- `runtime/frequency/src/lib.rs`
- `runtime/common/src/constants.rs`
- `runtime/common/src/extensions/check_nonce.rs`
