### ISSUE TITLE
Document complexity for each storage operation

### ISSUE THREAD

**Issue by rlaferla** [LibertyDSNP/frequency#770]
Each storage operation should be documented with the relative complexity of interacting with that storage.
Do we want to do this? Is there an easier way to document it?

https://en.wikipedia.org/wiki/Big_O_notation

Originally in issue:
https://github.com/LibertyDSNP/frequency/issues/742

**Comment by rlaferla** [comment]
@wilwade It would be useful to see examples of how other chains address it.

**Comment by aramikm** [comment]
Some examples https://github.com/search?q=repo%3Aparitytech%2Fsubstrate+%60O%28&type=code

**Comment by rlaferla** [comment]
@aramikm  Thanks but can you point me to a specific example in that list?  I don't see any.

**Comment by aramikm** [comment]
https://github.com/paritytech/substrate/blob/15cfd9c5dbbfa1f3ed49623eb55b67354d1645e9/frame/collective/src/lib.rs#L557

Voting is a StorageMap

**Comment by wilwade** [comment]
Archive
