### ISSUE TITLE
Requiring IPFS CIDs as multibase-encoded strings with CIDv1

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#786]
To make it more likely that our IPFS CIDs are correct and stored efficiently, we should require IPFS CIDv1s for `add_ipfs_message`.

Note: Expected to expand to CIDv2+ as they come out with the only change being the ensure statement assuming v2+ still follow `base32` encoding.

Related:
- #738 
- #787
- CID Spec: https://github.com/multiformats/cid
- CID Inspector: https://cid.ipfs.tech
- JS for multiformats https://github.com/multiformats/js-multiformats/blob/master/src/cid.js

## Acceptance Criteria
- [x] `add_ipfs_message` should ensure CIDv1
- [x] NEW Error: `Unsupported CID version` Supplied CID is v0
- [x] NEW Error: `Invalid CID` Supplied CID value cannot be decoded as a CID
- [x] Calling `add_ipfs_message` with CIDv1 should succeed:
    - SUCCESS (string)`bafybeihdwdcefgh4dqkjv67uzcmw7ojee6xedzdetojuzjevtenxquvyku`
    - FAIL: hex: `0x01701220e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`
    - FAIL (utf-8 to hex) `0x516d64665462427142505137564e785a4559456a3134566d52755a426b714662697752656f674a6753317a52316e0x626166796265696864776463656667683464716b6a763637757a636d77376f6a6565367865647a6465746f6a757a6a657674656e78717576796b75`
- [x] Calling `add_ipfs_message` with CIDv0 should always fail:
    - `QmdfTbBqBPQ7VNxZEYEj14VmRuZBkqFbiwReogJgS1zR1n`
    - Failing UTF-8 Hex encoding of: `0x516d64665462427142505137564e785a4559456a3134566d52755a426b714662697752656f674a6753317a52316e`
    - Failing v0 Bytes: `0x1220e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`
- [x] Better method documentation around the format required for IPFS:
    - [x] https://libertydsnp.github.io/frequency/common_primitives/schema/enum.PayloadLocation.html#variant.IPFS
    - [x] https://libertydsnp.github.io/frequency/pallet_messages/pallet/struct.Pallet.html#method.add_ipfs_message

**Comment by JoeCap08055** [comment]
@wilwade (or anyone): when adding CID format validity check, should we add it as a no-cost `pre_dispatch` validity check like we have in the `msa` pallete? Seems like a valid case to me...

**Comment by JoeCap08055** [comment]
@wilwade -- looking for some clarification on the acceptance criteria defined above. Based on my testing, it looks like what we receive in the extrinsic is a UTF-8 byte array representing a multibase-encoded string of the CID. Is this what you were expecting? It appears to work, but I wanted to make sure that the format of the data the tests are calling the method with is the same that it will be receiving from a client. Or should we be doing additional checks on the data in case we're passed a binary byte array instead of UTF-8?

**Comment by JoeCap08055** [comment]
> 

Resolved at standup. No need to add `pre-dispatch` no-cost validity checks for now; may revisit later.
