### ISSUE TITLE
Improve `on_initialize` benchmarks for MSA

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#795]
### Description: 
When updating benchmark `MaxSignaturesPerBucket` it took like 8 hours.
Improve the time take takes to run CI `on_intialize` benchmarks for MSA for cleaning sig.

### Notes:
- this could be indicator to review the implementation and might be addreses by —- [this](https://github.com/LibertyDSNP/frequency/issues/785)

- Blocked by :[Spike](https://github.com/LibertyDSNP/frequency/issues/785)
- Ref link: [PR](https://github.com/LibertyDSNP/frequency/pull/791) Took like 8 hours

**Comment by aramikm** [comment]
This is addressed at #791
