### ISSUE TITLE
[OpenRPC] Translate metadata to OpenRPC document

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#806]
## Description:
Generate an OpenRPC document from Frequency/Substrate metadata.

Former OpenAPI project document:
Ref doc [link](https://docs.google.com/document/d/1cdoc5bH8xgi2rZn1ghT5ZgkaxSCgLSYCE6sri8p8YrU/edit#)

### Acceptance criteria 
- Valid OpenRPC document that includes all RPC methods
- Code should be open source with the possibility of contributing changes to Parity.
- Future: #851

### Implementation

The implementation will be a fork of Parity's _typegen_ utility which is part of the PolkaDot JS API suite.  The tool will download metadata from a Frequency node and generate an OpenRPC document from it.

**OpenRPC**
https://spec.open-rpc.org

**@polkadot{.js} _typegen_**
https://github.com/polkadot-js/api/tree/master/packages/typegen

** Repository **
https://github.com/LibertyDSNP/polkadot-js-openrpc

### Alternatives to look at if this option fails

- https://github.com/slatedocs/slate

**Comment by rlaferla** [comment]
The non-trivial issue with this project, regardless of implementation/approach, is the mapping of complex Rust/Substrate types to OpenAPI types.  OpenAPI has a handful of primitive types with Schema Objects for more complex/object types.  It's unclear how the Substrate runtime can automatically perform this mapping.  This is distinct from the overall serialization of the document.  See also: https://spec.openapis.org/oas/v3.1.0#data-types and https://spec.openapis.org/oas/v3.1.0#schemaObject

**Comment by rlaferla** [comment]
Is the resulting OpenAPI document limited to just _Frequency_ pallets (_msa_/_messages_/_schemas_) or to the entire runtime?

**Comment by rlaferla** [comment]
Additionally, the Substrate metadata doesn't appear to contain any RPC methods.  Therefore, we would need to obtain them separately.

`curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "rpc_methods"}' http://localhost:9933/ > rpc_methods.json`

**Comment by rlaferla** [comment]
I asked OpenAI and here's what it said:

Parity Substrate is a blockchain development platform that allows you to build custom blockchains and decentralized applications (DApps). It provides a runtime environment and modular architecture for building and deploying decentralized applications.

OpenAPI (formerly known as Swagger) is a specification for building APIs that enables you to describe the structure and behavior of your APIs in a machine-readable format. It provides a way to document your APIs in a way that is easy for developers to understand and use.
To map Parity Substrate runtime types to OpenAPI types, you will need to consider the data types and structures used in your Parity Substrate runtime and map them to the corresponding OpenAPI types.

Here are some examples of common mappings between Parity Substrate runtime types and OpenAPI types:

Parity Substrate **u32** (unsigned 32-bit integer) maps to OpenAPI **integer** with a format of **int32**.
Parity Substrate **i32** (signed 32-bit integer) maps to OpenAPI **integer** with a format of **int32**.
Parity Substrate **u64** (unsigned 64-bit integer) maps to OpenAPI **integer** with a format of **int64**.
Parity Substrate **i64** (signed 64-bit integer) maps to OpenAPI **integer** with a format of **int64**.
Parity Substrate **bool** maps to OpenAPI **boolean**.
Parity Substrate **Vec<T>** (vector of elements of type **T**) maps to OpenAPI array with the **items** field set to the appropriate OpenAPI type for T**.**
You will need to map any other custom types or structures used in your Parity Substrate runtime to the appropriate OpenAPI types as well.

It may be helpful to reference the OpenAPI specification and the documentation for the data types and structures used in your Parity Substrate runtime to determine the appropriate mappings.

**Comment by rlaferla** [comment]
OLD/OBSOLETE NOTES

- Implementation: [example](https://github.com/saraswatpuneet/subxt-extra/blob/9a8b53855fee1e5fc1b98ed41cd61baaf50b9716/codegen/src/swagger/generator.rs#L62)
- Extending codegen tool to create a swagger type [generator](https://github.com/saraswatpuneet/subxt-extra/blob/9a8b53855fee1e5fc1b98ed41cd61baaf50b9716/codegen/src/api/mod.rs#L114)
- Specifically actual logic to convert metadata to document [generate_swagger_from_url,](https://github.com/saraswatpuneet/subxt-extra/blob/9a8b53855fee1e5fc1b98ed41cd61baaf50b9716/codegen/src/swagger/generator.rs#L56) where metadata is read from live chain url (example code)
- If needed support generating swagger using metadata file similar to [codegen](https://github.com/saraswatpuneet/subxt-extra/blob/9a8b53855fee1e5fc1b98ed41cd61baaf50b9716/codegen/src/api/mod.rs#L60)
- Checkout a [simple unit test](https://github.com/saraswatpuneet/subxt-extra/blob/9a8b53855fee1e5fc1b98ed41cd61baaf50b9716/codegen/src/swagger/types.rs#L935) creating a swagger document

**Comment by p5150j** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blockchain-Team-638f7004a2c37722fe2850e8/issues/LibertyDSNP/frequency/806?planning-poker) with Zenhub @rlaferla

**Comment by rlaferla** [comment]
If this is going to eventually be included in the GitHub CI workflow, perhaps we should also obtain the metadata directly from a WASM release asset?

**Comment by rlaferla** [comment]
We should create a RPC on the chain to return the OpenRPC document:

```
{
  "methods": [
    {
      "name": "rpc.discover",
      "description": "Returns an OpenRPC schema as a description of this service",
      "result": {
        "name": "OpenRPC Schema",
        "schema": {
          "$ref": "https://raw.githubusercontent.com/open-rpc/meta-schema/master/schema.json"
        }
      }
    }
  ]
}
```

**Comment by rlaferla** [comment]
OpenRPC types utilize JSON Schema types as specified:

[4.2.1. ](https://json-schema.org/draft/2020-12/json-schema-core.html#section-4.2.1)[Instance Data Model](https://json-schema.org/draft/2020-12/json-schema-core.html#name-instance-data-model)
JSON Schema interprets documents according to a data model. A JSON value interpreted according to this data model is called an "instance".

An instance has one of six primitive types, and a range of possible values depending on the type:

**null**:
A JSON "null" value
**boolean**:
A "true" or "false" value, from the JSON "true" or "false" value
**object**:
An unordered set of properties mapping a string to an instance, from the JSON "object" value
**array**:
An ordered list of instances, from the JSON "array" value
**number**:
An arbitrary-precision, base-10 decimal number value, from the JSON "number" value
**string**:
A string of Unicode code points, from the JSON "string" value

**Comment by rlaferla** [comment]
Should we specify servers in the document?  If so, should it include Rococo in addition to Mainnet?  Or should we do a separate document for each (because they could differ)?

**Comment by rlaferla** [comment]
We need to understand what the valid format is for the `result` section of a _method_ in the OpenRPC JSON document.

**Comment by rlaferla** [comment]
We can possibly include Errors in the OpenRPC document.  It needs to be researched and evaluated.

**Comment by rlaferla** [comment]
We need to have a discussion around the description fields in the OpenRPC document which is derived from Rust library comments.  We may need to sanitize and better format the comments in the Rust code.

**Comment by rlaferla** [comment]
The initial implementation is working but needs more refinement and testing.

**Comment by rlaferla** [comment]
There a handful of minor finishing touches that can be implemented:

- Output just the `openrpc.json` file (no output directory) if the `--openrpc` option is specified.
- Add a CLI option for chain title/version
- Fill out a few more of the less commonly used complex types for completeness

**Comment by rlaferla** [comment]
After some discussion with @wilwade, we are going to see if we can develop a more comprehensive set of types using the TS defs script rather than the TX script that was initially used.
