### ISSUE TITLE
Optimization of error messages

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#812]
As the Frequency Network, which wants to maximize block space, I want to ensure that transactions that fail are precise on how much resources are consumed.

Currently, transactions that fail consume the worst-case scenario weight regardless of how much actual resources are consumed.

Review all extrinsic and see if there are places where we can save block space by returning a more accurate weight for the error.

Note:
This requires to create benchmarks for those error cases.

**Comment by aramikm** [comment]
An example implementation is suggested in https://github.com/LibertyDSNP/frequency/pull/717

**Comment by wilwade** [comment]
Closing for a future time. Added to #59
