### ISSUE TITLE
Frequency Rococo and Mainnet do not have the correct Genesis

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#847]
## Bisect results:
- Mainnet: #726, Commit: `8354a41603e9f3bab192e5f2bf0fcb9ea24199cf`
- Rococo: #682, Commit: `950691e2aa381155fe563f3325464b05c956f218` (Oddly enough, not the one ^)

## How To Reproduce

1. Checkout `v0.9.29`
2. `make build-rococo`
3. `./target/release/frequency --tmp`
4. See these log messages:
  ```
  2022-12-22 21:34:20 📋 Chain specification: Frequency Rococo
  ...
  2022-12-22 21:42:33 [Parachain] Bootnode with peer id `12D3KooWArmKDbY8Y6XXHGodosWAjRWWxSw5YxWEjSZTBNjJXVSC` is on a different chain (our genesis: 0x0134…0abb theirs: 0x0c33…8e72)
  ```

## Ideas and Thoughts
- How is this possible if the json spec files are being used? Unknown.
- Tested with release and production. That is not the issue (so release is easier).
- Frequency Rococo has had an update already and is on spec_version 2
- Frequency Rococo is on 0.9.29-rc3. Apparently when we built `resources/frequency-rococo.json` we did it wrong
- Check out the `-rc3` release or subwasm can likely be used to get the original wasm to update `resources/frequency-rococo.json` so that it has the same stuff. (Remember that wasms are only deterministic with `srtool`, but it is possible that the original wasm is not an srtool wasm).
- Did a git bisect and got this when testing mainnet:

```
8354a41603e9f3bab192e5f2bf0fcb9ea24199cf is the first bad commit
commit 8354a41603e9f3bab192e5f2bf0fcb9ea24199cf
Date:   Thu Dec 1 11:28:52 2022 -0600

    Chore/unify runtimes (#726)
```

**Comment by saraswatpuneet** [comment]
And I believe since we unified runtimes we should have re-generated with genesis too, but not sure if that would mean we have to stick to it, however this should only be reflective in rococo, given mainnet was launched with unified runtimes

**Comment by saraswatpuneet** [comment]
Or:
* Before unified runtime we were producing wasms without feature flags turned on
* As a result we saw rococo const such as LaunchPeriod etc had mainnet values
* _With the fix the wasm must have changed?  Probably yes_

**Comment by saraswatpuneet** [comment]
I get different genesis hash locally when i changed the code to no read the spec file but generate spec on load

`Bootnode with peer id `12D3KooWArmKDbY8Y6XXHGodosWAjRWWxSw5YxWEjSZTBNjJXVSC` is on a different chain (our genesis: 0x7c77…eb8f theirs: 0x0c33…8e72)  `

**Comment by saraswatpuneet** [comment]
What is puzzling me more:
* Genesis hash is read from the files : spec files in resources
* If file is not specified we would read from code itself (which we changed to reading from files)
* So since rococo we are always reading from the spec files then why the live nodes dont read the same 

This puzzles me

**Comment by saraswatpuneet** [comment]
On .9.29 Branch

2022-12-28 11:57:16 [Parachain] 🔨 Initializing Genesis block/state (state: 0x7ed0…0cf9, header-hash: 0x0134…0abb)    
2022-12-28 11:57:17 [Relaychain] 🔨 Initializing Genesis block/state (state: 0x8ad9…f0da, header-hash: 0x6408…063e)    


On main Branch

2022-12-28 14:25:21 [Parachain] 🔨 Initializing Genesis block/state (state: 0x8ea1…7d13, header-hash: 0xa2d3…57e4)    
2022-12-28 14:25:22 [Relaychain] 🔨 Initializing Genesis block/state (state: 0x8ad9…f0da, header-hash: 0x6408…063e)    


I see the state and head-heah has changed

**Comment by saraswatpuneet** [comment]
Notes:

https://stackoverflow.com/questions/66554685/substrate-genesis-blocks-not-matching

**Comment by saraswatpuneet** [comment]
After testing quite a bit, 

* Hashes changed after runtimes were merged
* Tried setting spec_name and impl_name = frequency-rococo still saw the hash has changed
* Will have to dive me how generis_hash is computed from spec files, there must be additional information or details

**Comment by rlaferla** [comment]
I also noticed that the peer id of the boot node appears to be invalid.  I believe that it should start with Qm instead of 12.

`“bootNodes”: [
    “/dns4/0.boot.rococo.frequency.xyz/tcp/30333/ws/p2p/12D3KooWArmKDbY8Y6XXHGodosWAjRWWxSw5YxWEjSZTBNjJXVSC”
  ],`

**Comment by wilwade** [comment]
@saraswatpuneet 

Changing the `spec_version` is what triggers the change.

That said, I have no idea why that would happen.
