### ISSUE TITLE
Enforce consistent source code formatting

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#858]
We currently don't have a cross repo code formatting and enforcement. We do check for Rust code format, but not JS/TypeScript. At least not consistently as differently formatted integration tests have been making into the repo. Need a good strategy for:

1. Enable code formatting in local dev environment. Ideally, most formatting issues should be caught here before they are attempted to be committed to the repo.
2. Fail the "Verify PR CI workflow" if source code formatting is not as expected. This applies to Rust, JS, TypeScript, YML and other source code.

**Architect Notes**:
- Consider leveraging full potential of prettier. It supports multiple formats
- Additional formatters can be added for whatever prettier does not support
- Consider enabling auto-formatting on save, so we don't have to remember dev to do it manually
- The prevailing editor at this point is VS Code. 
- [Nx.dev](https://nx.dev/recipes/adopting-nx/manual#formatting) does a good job at enforcing formatting across its mono-repos. Maybe some configs can be borrowed from it.

**Comment by wilwade** [comment]
Archive
