### ISSUE TITLE
[Vulnerabilities]Dependabot alerts: Wasmtime may have data leakage between instances

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#860]
Please see:
[Wasmtime may have data leakage between instances in the pooling allocator](https://github.com/LibertyDSNP/frequency/security/dependabot/17)

Blocked by https://github.com/paritytech/substrate/issues/12986

**Comment by wilwade** [comment]
Will be fixed in #1332

**Comment by wilwade** [comment]
Fixed by https://github.com/LibertyDSNP/frequency/pull/1590
