### ISSUE TITLE
[Vulnerabilities]Dependabot alerts: Wasmtime out of bounds

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#864]
See:
[Wasmtime out of bounds read/write with zero-memory-pages configuration](https://github.com/LibertyDSNP/frequency/security/dependabot/16)

Blocked. Will be resolved upon upgrade to Polkadot v0.9.40

**Comment by wilwade** [comment]
Still blocked, but now will be resolved upon the upgrade to Polkadot v0.9.40.

**Comment by wilwade** [comment]
Fixed by https://github.com/LibertyDSNP/frequency/pull/1590
