### ISSUE TITLE
[Capacity] Epoch time to claim my un-staked tokens

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#869]
### Description:

Implementation of how to Replenish Replenishable means that all Capacity is replenished after a fixed period called an Epoch Period. An Epoch Period is composed of a set number of blocks. In the example below, the Epoch Period is three blocks. The initial Epoch Period will be around 100 blocks. 

![image.png](https://images.zenhubusercontent.com/5c128028ea8fd844ba2fcc52/b08f5b7f-5c7d-499e-9bdf-88be642bbde4)

Acceptance criteria :
- Must be able to query epoch number in storage
- After a fixed number of blocks, a new Epoch Period begins.
- At the start of a new Epoch Period, `EpochNumber` storage is increased by 1.
- At the start of a new block, `CurrentBlockUsedCapacity` storage is reset.
- Benchmark for `on_initialize`

**Comment by shannonwells** [comment]
Notes from discussions:

Revise interfaces in DesignDoc:
* Remove Number, _number from the names, i.e. `EpochProvider, Epoch, current_epoch, set_epoch`
```
pub trait EpochNumberProvider {
  /// Type of `EpochNumber` to provide.
  type EpochNumber: Codec + Clone + Ord + Eq + AtLeast32BitUnsigned;

  /// Provides an abstraction over an arbitrary way of providing the
  /// current epoch number.
  fn current_epoch_number() -> Self::EpochNumber;

  /// It allows for setting the block number that will later be fetched
  /// This is useful in case the block number provider is different from than System
  #[cfg(feature = "runtime-benchmarks")]
  fn set_epoch_number(_block: Self::EpochNumber) {}
}
```

**Comment by johnmela** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blockchain-Team-638f7004a2c37722fe2850e8/issues/LibertyDSNP/frequency/869?planning-poker) with Zenhub @johnmela
