### ISSUE TITLE
Remove Pallet Call Filters

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency#877]
To bring full feature availability to mainnet, we need to remove most of the call filters.

Note: This requires coordination with others. @wilwade for details.
As per https://github.com/LibertyDSNP/frequency/issues/952 leave call filter
Continue to filter the vesting pallet.

**Comment by p5150j** [comment]
@rlaferla please connect with @wilwade on the call filters...

**Comment by wilwade** [comment]
@rlaferla / @p5150j I think this is blocked by:
- #578 
- #321 
- #599

**Comment by rlaferla** [comment]
Per my discussion w/@wilwade this is currently blocked by an issue he is working on.

**Comment by rlaferla** [comment]
Add call filters for Capacity and Private Graph.
