### ISSUE TITLE
[Design Doc] Update Delegation Design Docs

### ISSUE THREAD

**Issue by aramikm** [LibertyDSNP/frequency#88]
# Acceptance Criteria
- [x] Design docs should be updated with following suggestions

# Some details around required updates
- I don't know that we want to support delegate replacing.
- Permissions are shifted to a different setup (https://github.com/LibertyDSNP/mrc/issues/20)
- Some of the stuff about creating an MSA doesn't really need to be in there now.
- Meaning an MSA must "register" or mark themselves as able to be delegated to before it can be delegated to (or staked to)

# Question
- what are the use-case for self delegation?

# Proposed updates
- Remove reference to Ethereum in Problem Statement
- Link to provider permissions design doc in Goals and non Goals section https://github.com/LibertyDSNP/frequency/blob/main/designdocs/provider_permissions.md
- References to "Message Sourcing Account" -> "Message Source Account"
- API (Extrinsics)
  - Rename create_account_with_provider -> create_sponsored_account_with_delegation 
    - Update Parameters and Event
    - Remove Restrictionssection
  - Remove add_self_as_provider
  - Remove replace_provider_with_self
  - Remove update_provider_self
  - Rename remove_provider_self -> remove_delegation_by_provider
    - Add Parameters and Event
  - Rename create_msa_id -> create  
    - Add Parameters and Event
  - Remove update_provider
  - Rename remove_provider -> revoke_msa_delegation_by_delegator
    - Add Parameters and Event
    - Remove Restrictions
  - Remove remove_msa_id
 - Custom RPC Endpoints
   - Rename get_account_ids -> get_msa_keys
   - Remove validate_provider
   - Rename validate_provider_for_ids -> check_delegations
     - check_delegations -> validate_provider_for_ids
       - Check how this RPC functions and reword description and return values to match
       - Update the parameter list
- Remove "Related Pallet configuration, constants and enumerations" section 
- Storage
  - Delegates -> ProviderInfoOf
    - Update parameters to match  
- All references to announce, announcer, announcements should be refactored to message, messager, messages

**Comment by johnmela** [comment]
Resolved by #364
