### ISSUE TITLE
[Capacity] integration tests for transacting 

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#889]
AC
- [x] When a user does not have enough capacity to pay for the transaction fee and is NOT eligible to replenish Capacity, it should error and be dropped from the transaction pool.
- [x] When a user attempts to pay for a non-capacity transaction with Capacity, it should error and drop the transaction from the transaction-pool.
- [x] When Capacity has withdrawn an event CapacityDeducted is emitted.
- [x] When a user is not a registered provider and attempts to pay with Capacity, it should error with InvalidTransaction::Payment.
- [x] Integration test and manual test. A registered provider with Capacity but no tokens associated with the key should still be able to use polkadot UI to submit a capacity transaction.
- [x] Token transactions should not be affected by supporting Capacity transactions.

**Comment by shannonwells** [comment]
let's come up with specific tests we want to write

**Comment by p5150j** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blockchain-Team-638f7004a2c37722fe2850e8/issues/LibertyDSNP/frequency/889?planning-poker) with Zenhub @enddynayn @johnmela @shannonwells

**Comment by enddynayn** [comment]
I added some specific tests but kept the need details label as a reminder to add more if needed.

**Comment by p5150j** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blockchain-Team-638f7004a2c37722fe2850e8/issues/LibertyDSNP/frequency/889?planning-poker) with Zenhub @mattheworris
