### ISSUE TITLE
[Capacity] integration tests for replenish capacity 

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#890]
Integration tests for replenishing capacity 

AC

- [ ] fails when you don't have enough capacity
- [ ] Capacity should not be replenished more than once per epoch.
   - Start with full capacity ( someone staked).
   - Empty out Capacity ( used all capacity during current epoch)
   - Capacity should not replenish until the next epoch.
- [ ] Capacity is replenished when the user's last replenished epoch is less than the current epoch. 
- [ ] When a user does not have enough capacity to pay the transaction fee and is eligible to replenish Capacity, it should refill Capacity and successfully transact.
- [ ] @shannonwells scenario for last replenish test here

**Comment by shannonwells** [comment]
let's come up with a minimal list of what tests to write

**Comment by p5150j** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blockchain-Team-638f7004a2c37722fe2850e8/issues/LibertyDSNP/frequency/890?planning-poker) with Zenhub @enddynayn @johnmela @shannonwells
