### ISSUE TITLE
[Capacity] make it simpler to configure the msa pallet to use as a testing dependency 

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#892]
needs to be groomed

**Comment by shannonwells** [comment]
Needs some more concrete requirements

**Comment by p5150j** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blockchain-Team-638f7004a2c37722fe2850e8/issues/LibertyDSNP/frequency/892?planning-poker) with Zenhub @enddynayn @johnmela @shannonwells

**Comment by p5150j** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blockchain-Team-638f7004a2c37722fe2850e8/issues/LibertyDSNP/frequency/892?planning-poker) with Zenhub @mattheworris

**Comment by p5150j** [comment]
closing as not part of phase 1
