### ISSUE TITLE
Research dedicated GitHub organization for GitHub Actions 

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#928]
Due to governance we are switching and changing repo locations it would be nice to have audited GitHub Actions that we use in a organization that is allow listed.

**Comment by wilwade** [comment]
The pinning has been working ok and is supported by Dependabot.

See https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions for more information about that
