### ISSUE TITLE
Create Retention Policy for Frequency Releases

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#931]
The release assets we publish right now are going to add up over time. The 3 AMD64 binaries we post at the moment  take up 310MB alone. 

Per @harry-evans suggestion, we'd need to introduce a release retention policy at some point with, perhaps, the mainnet artifacts retained longer than the rococo ones. Unless we want to keep each previously published release atomic (i.e. exactly as it was published) and only archive an entire release as a whole since a release contains all network artifacts.

**Comment by wilwade** [comment]
Archive
