### ISSUE TITLE
[Capacity] replace currency trait with fungible trait 

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#942]
After talking speaking with Parity they are going to replace the currency trait with fungible trait.

**Comment by p5150j** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blockchain-Team-638f7004a2c37722fe2850e8/issues/LibertyDSNP/frequency/942?planning-poker) with Zenhub @enddynayn @shannonwells @johnmela

**Comment by p5150j** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Blockchain-Team-638f7004a2c37722fe2850e8/issues/LibertyDSNP/frequency/942?planning-poker) with Zenhub @mattheworris

**Comment by wilwade** [comment]
https://github.com/paritytech/substrate/pull/12951

**Comment by shannonwells** [comment]
This can't be worked on because the Substrate PR hasn't been merged yet.

**Comment by shannonwells** [comment]
Chatted with @enddynayn  - not all of the fungible traits that we want are in polkadot-v0.9.36, but they're in master.  I have something almost working, that adds our own traits to replace them and only one compile error, but we want to wait until we're caught up with a version of substrate that includes all the traits we need.  Branch is [replace-currency-with-fungible-trait-#942](https://github.com/LibertyDSNP/frequency/tree/feat/replace-currency-with-fungible-trait-%23942)
