### ISSUE TITLE
Architectural overview diagram (specific modules)

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#955]
As a retrospective item:
>I wish we had an architectural overview diagram for Frequency with documents for specific modules and how they interoperate.  e.g.  node service, pallets, etc...

https://github.com/LibertyDSNP/frequency/tree/main/designdocs or more detailed?

Ideas/Thoughts
- Better Readmes (or lib.rs docs) for each crate?
- How the things tie together all the dependencies and the customizations
- How to get the big picture

Libs that might be helpful :
- https://lib.rs/crates/rudg 
- https://jonathansteyfkens.com/posts/visualizing-rust.html

**Comment by rlaferla** [comment]
One aspect of this is to explain which components we are using and why:  _Substrate_, _Cumulus_, _Polkadot_, _ORML_, _Avro_, _Parquet_, etc...

**Comment by rlaferla** [comment]
Another aspect is a diagram (or set of diagrams) showing principal use-cases for both end-users and providers:

- User obtaining an account (how does that transaction get processed, by which pallets, what is the validation process, events/errors)
- User posting on-chain and off-chain messages
- Provider paths

**Comment by wilwade** [comment]
Archive
