### ISSUE TITLE
Update docker hub overview pages to pin image version

### ISSUE THREAD

**Issue by demisx** [LibertyDSNP/frequency#958]
The current docker run examples shown in the Docker Hub README page are using the `latest` docker image. The recommended approach is to run with specific version image. Update instructions to reflect that. 

For example, in https://hub.docker.com/repository/docker/frequencychain/parachain-node-mainnet/general:

```
docker run -p 9944:9944 -p 9933:9933 -p 30333:30333 frequencychain/parachain-node-mainnet \
    --base-path=/chain-data \
    ...
```

should be

```
docker run -p 9944:9944 -p 9933:9933 -p 30333:30333 frequencychain/parachain-node-mainnet:<version.tag> \
    --base-path=/chain-data \
    ...
```

**Comment by Tejasbankar** [comment]
Hi @demisx,
Just to confirm, should they be `<version.tag>` or a specific version?
