### ISSUE TITLE
Make chain event types use consistent style

### ISSUE THREAD

**Issue by JoeCap08055** [LibertyDSNP/frequency#961]
So I had been curious as to why, in our TS integration tests, we can do something like:
`msaId = msaCreatedEvent.data.msaId;`
...with all events except for SchemaCreated and SchemaMaxSizeChanged, which require you to do something like:
`schemaId = schemaCreatedEvent.data.1;`

Turns out it's because the Events in Rust are defined using C-like structures for all events in all pallets, except for the schema pallet. Compare:
```
	#[pallet::event]
	#[pallet::generate_deposit(pub(super) fn deposit_event)]
	pub enum Event<T: Config> {
		/// Messages are stored for a specified schema id and block number
		MessagesStored {
			/// The schema for these messages
			schema_id: SchemaId,
			/// The block number for these messages
			block_number: T::BlockNumber,
			/// `DEPRECATED` - Number of messages in this block for this schema
			/// Value does not reflect the actual count and it will be removed in June 2023
			count: u16,
		},
	}
```

to

```
	#[pallet::event]
	#[pallet::generate_deposit(pub (super) fn deposit_event)]
	pub enum Event<T: Config> {
		/// Emitted when a schema is registered. [who, schemas id]
		SchemaCreated(T::AccountId, SchemaId),

		/// Emitted when maximum size for schema model is changed.
		SchemaMaxSizeChanged(u32),
	}
```

Goal:
Make Event definitions consistently use struct-like format in all pallets, like so:

```
pub enum Event<T: Config> {
   SchemaCreated {
      key: T::AccountId,
      schema_id: SchemaId
   },

   SchemaMaxSizeChanged {
      max_size: u32
   }
}
```

**Comment by rlaferla** [comment]
We found that the API augment script wasn't regenerating the Typescript interface files properly because it didn't run `clean:generated` before regeneration.   A fix for this will be included in the PR.
