### ISSUE TITLE
Parity/Substrate Upgrades issues

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#962]
@p5150j add all comments below and update description below  

Retro items:
- Tool to better compare the metadata versions at a type layer
- Better parsing of the Polkadot Releases
- Better release documentation 

As a company that has a dependency I need to know when to do a release with the dependency

Problem: 
- [ ] If you skip a dep release you run the risk of missing a migration
- [ ] Have to update for security releases 

Ideas:
- [ ] Ask sister vendor 1 what they do
- [ ] Ask sister vendor 2 what they do
- [ ] Issue checklist to see if we can

**Comment by shannonwells** [comment]
Notes:
compile checklist for each upgrade
track each upgrade as an issue
cross off each item

includes:
is there a storage migration
what is the urgency of the migration
can it be safely skipped (e.g. there is no security update, there is no storage migration or removal)
does it change scale encoding for major types, in other words, what is the downstream impact on

**Comment by rlaferla** [comment]
add to list:

is there a security issue that requires an upgrade?  what's the impact?  how urgent?

list of incompatibilities?

**Comment by shannonwells** [comment]
@demisx this works pretty well
@rlaferla the security issues as well as migrations and such are detailed in the linked Polkadot Substrate release notes
@p5150j do we think this is done-ish? When to discuss?

**Comment by wilwade** [comment]
Archive
