### ISSUE TITLE
CI should use Make rules

### ISSUE THREAD

**Issue by shannonwells** [LibertyDSNP/frequency#972]
As a developer, so that I can verify my changes and know that my work does not break things, I want to be using the same commands as CI.

Backstory:  CI doesn't use Make rules, and so when CI gets updated, often the Makefile gets out of date and this causes problems for development.  CI should be using Make rules so there is a single place where build, run, check, and test commands are kept up to date.

**Comment by shannonwells** [comment]
I'd like to make ^^ a separate issue

**Comment by wilwade** [comment]
Archive
