### ISSUE TITLE
The export-metadata /might/ not be producing correct metadata.

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#984]
The export-metadata /might/ not be producing correct metadata.

**Comment by p5150j** [comment]
Near end of day update on this.
Still in progress. Seeing other weird things that worry me, but likely just something I do not understand.
 @saraswatpuneet might try to pair with you tomorrow morning. The runtime version command is also suffering from some strange results.

no worries, I will have a look since we have those as custom commands they use client api (version ), it should work as it just reads from file, but maybe macros broke it
```
❯ ./target/release/frequency export-runtime-version
{"apis":[["0xdd718d5cc53262d4",1],["0xdf6acb689907609b",4],["0x37e397fc7c91f5e4",1],["0x40fe3ad401f8959a",6],["0xd2bc9897eed08f15",3],["0xf78b278be53f454c",2],["0xab3c0572291feb8b",1],["0xbc9d89904f5b923f",1],["0x37c8bb1350a9a2a8",2],["0xea93e3f16f3d6962",2],["0x54bef602b989d121",1],["0x02fadd88517cc081",1],["0x24d062f93a859f6f",1]],"authoringVersion":1,"implName":"frequency","implVersion":0,"specName":"frequency-rococo","specVersion":10,"stateVersion":1,"transactionVersion":1}
```

**Comment by rlaferla** [comment]
Would it be helpful if we took `subwasm` and added the ability to generate prettified JSON from a file vs. the network?  The level of effort would be minimal (~1 hr) and we could use this tool to diagnose and compare metadata.

**Comment by JoeCap08055** [comment]
> Would it be helpful if we took `subwasm` and added the ability to generate prettified JSON from a file vs. the network? The level of effort would be minimal (~1 hr) and we could use this tool to diagnose and compare metadata. We could contribute this back to Parity. We could also post this resulting JSON as a release asset.

I'm always in favor of additional tools in my belt :-)
