### ISSUE TITLE
Explore customer Instrumentation

### ISSUE THREAD

**Issue by p5150j** [LibertyDSNP/frequency#989]
As a provider what tools to I have access to so that I can self serve any issues I may arise regarding identity, capacity or graph related offerings.  

As Frequency we need to define a process and tools when a provider is unable to self serve and an escalation path is needed.

Open questions:
does parity have any tools that can off load the need for to to build things custom?

**Comment by wilwade** [comment]
Parity DevOps Guide: https://paritytech.github.io/devops-guide/overview.html

**Comment by p5150j** [comment]
Closing as any support that will be needed will be defined in public docs, and devops will be monitoring nodes.
